<?php

return [
    1 => ['name' => 'Dubai', 'region' => 'Dubai'],
    2 => ['name' => 'Abu Dhabi'],
    3 => ['name' => 'Sharjah'],
      3 => ['name' => 'Ajman'],
      4 => ['name' => 'Ras Al Khaimah'],
      5 => ['name' => 'Fujairah'],
      6 => ['name' => 'Umm Al Quwain'],
      7 => ['name' => 'Al Ain'],
      8 => ['name' => 'Khalifa City'],
      9 => ['name' => 'Mussafah'],
     10 => ['name' => 'Bani Yas'],
     11 => ['name' => 'Al Shamkha'],
     12 => ['name' => 'Madinat Zayed'],
     13 => ['name' => 'Liwa'],
     14 => ['name' => 'Ruwais'],
     15 => ['name' => 'Ghayathi'],
     16 => ['name' => 'Delma Island'],
     17 => ['name' => 'Al Dhafra'],
     18 => ['name' => 'Jebel Ali'],
     19 => ['name' => 'Deira'],
     20 => ['name' => 'Bur Dubai'],
     21 => ['name' => 'Jumeirah'],
     22 => ['name' => 'Al Barsha'],
     23 => ['name' => 'Al Nahda'],
     24 => ['name' => 'Al Qusais'],
     25 => ['name' => 'Al Karama'],
     26 => ['name' => 'Mirdif'],
     27 => ['name' => 'Al Warqa'],
     28 => ['name' => 'Dubai Marina'],
     29 => ['name' => 'Palm Jumeirah'],
     30 => ['name' => 'Business Bay'],
     31 => ['name' => 'Al Satwa'],
     32 => ['name' => 'Al Quoz'],
     33 => ['name' => 'Al Khail Heights'],
     34 => ['name' => 'DIFC'],
     35 => ['name' => 'Al Majaz'],
     36 => ['name' => 'Al Khan'],
     37 => ['name' => 'Muwaileh'],
     38 => ['name' => 'University City'],
     39 => ['name' => 'Al Dhaid'],
     40 => ['name' => 'Khor Fakkan'],
     41 => ['name' => 'Dibba Al Fujairah'],
     42 => ['name' => 'Dibba Al Hisn'],
     43 => ['name' => 'Masafi'],
     44 => ['name' => 'Hatta'],
     45 => ['name' => 'Al Jazirah Al Hamra'],
     46 => ['name' => 'Digdaga'],
     47 => ['name' => 'Ghalilah'],
     48 => ['name' => 'Al Hamra Village'],
     49 => ['name' => 'Al Nakheel'],
     50 => ['name' => 'Al Marjan Island'],
     51 => ['name' => 'Al Taawun'],
     52 => ['name' => 'Al Qurm'],
     53 => ['name' => 'Al Nahda Sharjah'],
     54 => ['name' => 'Al Majaz Sharjah'],
     55 => ['name' => 'Al Khan Sharjah'],
     56 => ['name' => 'Al Batayeh'],
     57 => ['name' => 'Al Zubair'],
     58 => ['name' => 'Al Heerah'],
     59 => ['name' => 'Al Badiyah'],
     60 => ['name' => 'UAE Locality 1'],
     61 => ['name' => 'UAE Locality 2'],
     62 => ['name' => 'UAE Locality 3'],
     63 => ['name' => 'UAE Locality 4'],
     64 => ['name' => 'UAE Locality 5'],
     65 => ['name' => 'UAE Locality 6'],
     66 => ['name' => 'UAE Locality 7'],
     67 => ['name' => 'UAE Locality 8'],
     68 => ['name' => 'UAE Locality 9'],
     69 => ['name' => 'UAE Locality 10'],
     70 => ['name' => 'UAE Locality 11'],
     71 => ['name' => 'UAE Locality 12'],
     72 => ['name' => 'UAE Locality 13'],
     73 => ['name' => 'UAE Locality 14'],
     74 => ['name' => 'UAE Locality 15'],
     75 => ['name' => 'UAE Locality 16'],
     76 => ['name' => 'UAE Locality 17'],
     77 => ['name' => 'UAE Locality 18'],
     78 => ['name' => 'UAE Locality 19'],
     79 => ['name' => 'UAE Locality 20'],
     80 => ['name' => 'UAE Locality 21'],
     81 => ['name' => 'UAE Locality 22'],
     82 => ['name' => 'UAE Locality 23'],
     83 => ['name' => 'UAE Locality 24'],
     84 => ['name' => 'UAE Locality 25'],
     85 => ['name' => 'UAE Locality 26'],
     86 => ['name' => 'UAE Locality 27'],
     87 => ['name' => 'UAE Locality 28'],
     88 => ['name' => 'UAE Locality 29'],
     89 => ['name' => 'UAE Locality 30'],
     90 => ['name' => 'UAE Locality 31'],
     91 => ['name' => 'UAE Locality 32'],
     92 => ['name' => 'UAE Locality 33'],
     93 => ['name' => 'UAE Locality 34'],
     94 => ['name' => 'UAE Locality 35'],
     95 => ['name' => 'UAE Locality 36'],
     96 => ['name' => 'UAE Locality 37'],
     97 => ['name' => 'UAE Locality 38'],
     98 => ['name' => 'UAE Locality 39'],
     99 => ['name' => 'UAE Locality 40'],
    100 => ['name' => 'UAE Locality 41'],
    101 => ['name' => 'UAE Locality 42'],
    102 => ['name' => 'UAE Locality 43'],
    103 => ['name' => 'UAE Locality 44'],
    104 => ['name' => 'UAE Locality 45'],
    105 => ['name' => 'UAE Locality 46'],
    106 => ['name' => 'UAE Locality 47'],
    107 => ['name' => 'UAE Locality 48'],
    108 => ['name' => 'UAE Locality 49'],
    109 => ['name' => 'UAE Locality 50'],
    110 => ['name' => 'UAE Locality 51'],
    111 => ['name' => 'UAE Locality 52'],
    112 => ['name' => 'UAE Locality 53'],
    113 => ['name' => 'UAE Locality 54'],
    114 => ['name' => 'UAE Locality 55'],
    115 => ['name' => 'UAE Locality 56'],
    116 => ['name' => 'UAE Locality 57'],
    117 => ['name' => 'UAE Locality 58'],
    118 => ['name' => 'UAE Locality 59'],
    119 => ['name' => 'UAE Locality 60'],
    120 => ['name' => 'UAE Locality 61'],
    121 => ['name' => 'UAE Locality 62'],
    122 => ['name' => 'UAE Locality 63'],
    123 => ['name' => 'UAE Locality 64'],
    124 => ['name' => 'UAE Locality 65'],
    125 => ['name' => 'UAE Locality 66'],
    126 => ['name' => 'UAE Locality 67'],
    127 => ['name' => 'UAE Locality 68'],
    128 => ['name' => 'UAE Locality 69'],
    129 => ['name' => 'UAE Locality 70'],
    130 => ['name' => 'UAE Locality 71'],
    131 => ['name' => 'UAE Locality 72'],
    132 => ['name' => 'UAE Locality 73'],
    133 => ['name' => 'UAE Locality 74'],
    134 => ['name' => 'UAE Locality 75'],
    135 => ['name' => 'UAE Locality 76'],
    136 => ['name' => 'UAE Locality 77'],
    137 => ['name' => 'UAE Locality 78'],
    138 => ['name' => 'UAE Locality 79'],
    139 => ['name' => 'UAE Locality 80'],
    140 => ['name' => 'UAE Locality 81'],
    141 => ['name' => 'UAE Locality 82'],
    142 => ['name' => 'UAE Locality 83'],
    143 => ['name' => 'UAE Locality 84'],
    144 => ['name' => 'UAE Locality 85'],
    145 => ['name' => 'UAE Locality 86'],
    146 => ['name' => 'UAE Locality 87'],
    147 => ['name' => 'UAE Locality 88'],
    148 => ['name' => 'UAE Locality 89'],
    149 => ['name' => 'UAE Locality 90'],
    150 => ['name' => 'UAE Locality 91'],
    151 => ['name' => 'UAE Locality 92'],
    152 => ['name' => 'UAE Locality 93'],
    153 => ['name' => 'UAE Locality 94'],
    154 => ['name' => 'UAE Locality 95'],
    155 => ['name' => 'UAE Locality 96'],
    156 => ['name' => 'UAE Locality 97'],
    157 => ['name' => 'UAE Locality 98'],
    158 => ['name' => 'UAE Locality 99'],
    159 => ['name' => 'UAE Locality 100'],
    160 => ['name' => 'UAE Locality 101'],
    161 => ['name' => 'UAE Locality 102'],
    162 => ['name' => 'UAE Locality 103'],
    163 => ['name' => 'UAE Locality 104'],
    164 => ['name' => 'UAE Locality 105'],
    165 => ['name' => 'UAE Locality 106'],
    166 => ['name' => 'UAE Locality 107'],
    167 => ['name' => 'UAE Locality 108'],
    168 => ['name' => 'UAE Locality 109'],
    169 => ['name' => 'UAE Locality 110'],
    170 => ['name' => 'UAE Locality 111'],
    171 => ['name' => 'UAE Locality 112'],
    172 => ['name' => 'UAE Locality 113'],
    173 => ['name' => 'UAE Locality 114'],
    174 => ['name' => 'UAE Locality 115'],
    175 => ['name' => 'UAE Locality 116'],
    176 => ['name' => 'UAE Locality 117'],
    177 => ['name' => 'UAE Locality 118'],
    178 => ['name' => 'UAE Locality 119'],
    179 => ['name' => 'UAE Locality 120'],
    180 => ['name' => 'UAE Locality 121'],
    181 => ['name' => 'UAE Locality 122'],
    182 => ['name' => 'UAE Locality 123'],
    183 => ['name' => 'UAE Locality 124'],
    184 => ['name' => 'UAE Locality 125'],
    185 => ['name' => 'UAE Locality 126'],
    186 => ['name' => 'UAE Locality 127'],
    187 => ['name' => 'UAE Locality 128'],
    188 => ['name' => 'UAE Locality 129'],
    189 => ['name' => 'UAE Locality 130'],
    191 => ['name' => 'UAE Locality 131'],
    192 => ['name' => 'UAE Locality 132'],
    193 => ['name' => 'UAE Locality 133'],
    194 => ['name' => 'UAE Locality 134'],
    195 => ['name' => 'UAE Locality 135'],
    196 => ['name' => 'UAE Locality 136'],
    197 => ['name' => 'UAE Locality 137'],
    198 => ['name' => 'UAE Locality 138'],
    199 => ['name' => 'UAE Locality 139'],
    200 => ['name' => 'UAE Locality 140'],
    201 => ['name' => 'Abu Dhabi (2)']
];