<?php

return [
    1 => ['name' => 'Vienna'],
    2 => ['name' => 'Graz'],
    3 => ['name' => 'Linz'],
    4 => ['name' => 'Salzburg'],
    5 => ['name' => 'Innsbruck'],
    6 => ['name' => 'Klagenfurt'],
    7 => ['name' => 'Villach'],
    8 => ['name' => 'Wels'],
    9 => ['name' => 'Sankt Pölten'],
    10 => ['name' => 'Dornbirn'],
    11 => ['name' => 'Wiener Neustadt'],
    12 => ['name' => 'Steyr'],
    13 => ['name' => 'Feldkirch'],
    14 => ['name' => 'Bregenz'],
    15 => ['name' => 'Leonding'],
    16 => ['name' => 'Klosterneuburg'],
    17 => ['name' => 'Baden bei Wien'],
    18 => ['name' => 'Wolfsberg'],
    19 => ['name' => 'Leoben'],
    20 => ['name' => 'Krems an der Donau'],
    21 => ['name' => 'Traun'],
    22 => ['name' => 'Amstetten'],
    23 => ['name' => 'Lustenau'],
    24 => ['name' => 'Kapfenberg'],
    25 => ['name' => 'Mödling'],
    26 => ['name' => 'Hallein'],
    27 => ['name' => 'Kufstein'],
    28 => ['name' => 'Schwechat'],
    29 => ['name' => 'Braunau am Inn'],
    30 => ['name' => 'Stockerau'],
    31 => ['name' => 'Saalfelden'],
    32 => ['name' => 'Ansfelden'],
    33 => ['name' => 'Tulln'],
    34 => ['name' => 'Hohenems'],
    35 => ['name' => 'Spittal an der Drau'],
    36 => ['name' => 'Ternitz'],
    37 => ['name' => 'Perchtoldsdorf'],
    38 => ['name' => 'Feldkirchen'],
    39 => ['name' => 'Bludenz'],
    40 => ['name' => 'Bad Ischl'],
    41 => ['name' => 'Eisenstadt'],
    42 => ['name' => 'Gmunden'],
    43 => ['name' => 'Bruck an der Mur'],
    44 => ['name' => 'Sankt Veit an der Glan'],
    45 => ['name' => 'Zwettl'],
    46 => ['name' => 'Vöcklabruck'],
    47 => ['name' => 'Waidhofen an der Ybbs'],
    48 => ['name' => 'Knittelfeld'],
    49 => ['name' => 'Lienz'],
    50 => ['name' => 'Villach'],
    51 => ['name' => 'Ried im Innkreis'],
    52 => ['name' => 'Schwaz'],
    53 => ['name' => 'Kitzbühel'],
    54 => ['name' => 'Lienz'],
    55 => ['name' => 'Judenburg'],
    56 => ['name' => 'Deutschlandsberg'],
    57 => ['name' => 'Hartberg'],
    58 => ['name' => 'Güssing'],
    59 => ['name' => 'Oberwart'],
    60 => ['name' => 'Mattersburg'],
     61 => ['name' => 'Austria Locality 1'],
     62 => ['name' => 'Austria Locality 2'],
     63 => ['name' => 'Austria Locality 3'],
     64 => ['name' => 'Austria Locality 4'],
     65 => ['name' => 'Austria Locality 5'],
     66 => ['name' => 'Austria Locality 6'],
     67 => ['name' => 'Austria Locality 7'],
     68 => ['name' => 'Austria Locality 8'],
     69 => ['name' => 'Austria Locality 9'],
     70 => ['name' => 'Austria Locality 10'],
     71 => ['name' => 'Austria Locality 11'],
     72 => ['name' => 'Austria Locality 12'],
     73 => ['name' => 'Austria Locality 13'],
     74 => ['name' => 'Austria Locality 14'],
     75 => ['name' => 'Austria Locality 15'],
     76 => ['name' => 'Austria Locality 16'],
     77 => ['name' => 'Austria Locality 17'],
     78 => ['name' => 'Austria Locality 18'],
     79 => ['name' => 'Austria Locality 19'],
     80 => ['name' => 'Austria Locality 20'],
     81 => ['name' => 'Austria Locality 21'],
     82 => ['name' => 'Austria Locality 22'],
     83 => ['name' => 'Austria Locality 23'],
     84 => ['name' => 'Austria Locality 24'],
     85 => ['name' => 'Austria Locality 25'],
     86 => ['name' => 'Austria Locality 26'],
     87 => ['name' => 'Austria Locality 27'],
     88 => ['name' => 'Austria Locality 28'],
     89 => ['name' => 'Austria Locality 29'],
     90 => ['name' => 'Austria Locality 30'],
     91 => ['name' => 'Austria Locality 31'],
     92 => ['name' => 'Austria Locality 32'],
     93 => ['name' => 'Austria Locality 33'],
     94 => ['name' => 'Austria Locality 34'],
     95 => ['name' => 'Austria Locality 35'],
     96 => ['name' => 'Austria Locality 36'],
     97 => ['name' => 'Austria Locality 37'],
     98 => ['name' => 'Austria Locality 38'],
     99 => ['name' => 'Austria Locality 39'],
    100 => ['name' => 'Austria Locality 40'],
    101 => ['name' => 'Austria Locality 41'],
    102 => ['name' => 'Austria Locality 42'],
    103 => ['name' => 'Austria Locality 43'],
    104 => ['name' => 'Austria Locality 44'],
    105 => ['name' => 'Austria Locality 45'],
    106 => ['name' => 'Austria Locality 46'],
    107 => ['name' => 'Austria Locality 47'],
    108 => ['name' => 'Austria Locality 48'],
    109 => ['name' => 'Austria Locality 49'],
    110 => ['name' => 'Austria Locality 50'],
    111 => ['name' => 'Austria Locality 51'],
    112 => ['name' => 'Austria Locality 52'],
    113 => ['name' => 'Austria Locality 53'],
    114 => ['name' => 'Austria Locality 54'],
    115 => ['name' => 'Austria Locality 55'],
    116 => ['name' => 'Austria Locality 56'],
    117 => ['name' => 'Austria Locality 57'],
    118 => ['name' => 'Austria Locality 58'],
    119 => ['name' => 'Austria Locality 59'],
    120 => ['name' => 'Austria Locality 60'],
    121 => ['name' => 'Austria Locality 61'],
    122 => ['name' => 'Austria Locality 62'],
    123 => ['name' => 'Austria Locality 63'],
    124 => ['name' => 'Austria Locality 64'],
    125 => ['name' => 'Austria Locality 65'],
    126 => ['name' => 'Austria Locality 66'],
    127 => ['name' => 'Austria Locality 67'],
    128 => ['name' => 'Austria Locality 68'],
    129 => ['name' => 'Austria Locality 69'],
    130 => ['name' => 'Austria Locality 70'],
    131 => ['name' => 'Austria Locality 71'],
    132 => ['name' => 'Austria Locality 72'],
    133 => ['name' => 'Austria Locality 73'],
    134 => ['name' => 'Austria Locality 74'],
    135 => ['name' => 'Austria Locality 75'],
    136 => ['name' => 'Austria Locality 76'],
    137 => ['name' => 'Austria Locality 77'],
    138 => ['name' => 'Austria Locality 78'],
    139 => ['name' => 'Austria Locality 79'],
    140 => ['name' => 'Austria Locality 80'],
    141 => ['name' => 'Austria Locality 81'],
    142 => ['name' => 'Austria Locality 82'],
    143 => ['name' => 'Austria Locality 83'],
    144 => ['name' => 'Austria Locality 84'],
    145 => ['name' => 'Austria Locality 85'],
    146 => ['name' => 'Austria Locality 86'],
    147 => ['name' => 'Austria Locality 87'],
    148 => ['name' => 'Austria Locality 88'],
    149 => ['name' => 'Austria Locality 89'],
    150 => ['name' => 'Austria Locality 90'],
    151 => ['name' => 'Austria Locality 91'],
    152 => ['name' => 'Austria Locality 92'],
    153 => ['name' => 'Austria Locality 93'],
    154 => ['name' => 'Austria Locality 94'],
    155 => ['name' => 'Austria Locality 95'],
    156 => ['name' => 'Austria Locality 96'],
    157 => ['name' => 'Austria Locality 97'],
    158 => ['name' => 'Austria Locality 98'],
    159 => ['name' => 'Austria Locality 99'],
    160 => ['name' => 'Austria Locality 100'],
    161 => ['name' => 'Austria Locality 101'],
    162 => ['name' => 'Austria Locality 102'],
    163 => ['name' => 'Austria Locality 103'],
    164 => ['name' => 'Austria Locality 104'],
    165 => ['name' => 'Austria Locality 105'],
    166 => ['name' => 'Austria Locality 106'],
    167 => ['name' => 'Austria Locality 107'],
    168 => ['name' => 'Austria Locality 108'],
    169 => ['name' => 'Austria Locality 109'],
    170 => ['name' => 'Austria Locality 110'],
    171 => ['name' => 'Austria Locality 111'],
    172 => ['name' => 'Austria Locality 112'],
    173 => ['name' => 'Austria Locality 113'],
    174 => ['name' => 'Austria Locality 114'],
    175 => ['name' => 'Austria Locality 115'],
    176 => ['name' => 'Austria Locality 116'],
    177 => ['name' => 'Austria Locality 117'],
    178 => ['name' => 'Austria Locality 118'],
    179 => ['name' => 'Austria Locality 119'],
    180 => ['name' => 'Austria Locality 120'],
    181 => ['name' => 'Austria Locality 121'],
    182 => ['name' => 'Austria Locality 122'],
    183 => ['name' => 'Austria Locality 123'],
    184 => ['name' => 'Austria Locality 124'],
    185 => ['name' => 'Austria Locality 125'],
    186 => ['name' => 'Austria Locality 126'],
    187 => ['name' => 'Austria Locality 127'],
    188 => ['name' => 'Austria Locality 128'],
    189 => ['name' => 'Austria Locality 129'],
    190 => ['name' => 'Austria Locality 130'],
    191 => ['name' => 'Austria Locality 131'],
    192 => ['name' => 'Austria Locality 132'],
    193 => ['name' => 'Austria Locality 133'],
    194 => ['name' => 'Austria Locality 134'],
    195 => ['name' => 'Austria Locality 135'],
    196 => ['name' => 'Austria Locality 136'],
    197 => ['name' => 'Austria Locality 137'],
    198 => ['name' => 'Austria Locality 138'],
    199 => ['name' => 'Austria Locality 139'],
    200 => ['name' => 'Austria Locality 140'],
    201 => ['name' => 'Austria Locality 1 (2)'],
    202 => ['name' => 'Austria Locality 2 (2)'],
    203 => ['name' => 'Austria Locality 3 (2)'],
    204 => ['name' => 'Austria Locality 4 (2)'],
    205 => ['name' => 'Austria Locality 5 (2)'],
    206 => ['name' => 'Austria Locality 6 (2)'],
    207 => ['name' => 'Austria Locality 7 (2)'],
    208 => ['name' => 'Austria Locality 8 (2)'],
    209 => ['name' => 'Austria Locality 9 (2)'],
    210 => ['name' => 'Austria Locality 10 (2)'],
    211 => ['name' => 'Austria Locality 11 (2)'],
    212 => ['name' => 'Austria Locality 12 (2)'],
    213 => ['name' => 'Austria Locality 13 (2)'],
    214 => ['name' => 'Austria Locality 14 (2)'],
    215 => ['name' => 'Austria Locality 15 (2)'],
    216 => ['name' => 'Austria Locality 16 (2)'],
    217 => ['name' => 'Austria Locality 17 (2)'],
    218 => ['name' => 'Austria Locality 18 (2)'],
    219 => ['name' => 'Austria Locality 19 (2)'],
    220 => ['name' => 'Austria Locality 20 (2)'],
    221 => ['name' => 'Austria Locality 21 (2)'],
    222 => ['name' => 'Austria Locality 22 (2)'],
    223 => ['name' => 'Austria Locality 23 (2)'],
    224 => ['name' => 'Austria Locality 24 (2)'],
    225 => ['name' => 'Austria Locality 25 (2)'],
    226 => ['name' => 'Austria Locality 26 (2)'],
    227 => ['name' => 'Austria Locality 27 (2)'],
    228 => ['name' => 'Austria Locality 28 (2)'],
    229 => ['name' => 'Austria Locality 29 (2)'],
    230 => ['name' => 'Austria Locality 30 (2)'],
    231 => ['name' => 'Austria Locality 31 (2)'],
    232 => ['name' => 'Austria Locality 32 (2)'],
    233 => ['name' => 'Austria Locality 33 (2)'],
    234 => ['name' => 'Austria Locality 34 (2)'],
    235 => ['name' => 'Austria Locality 35 (2)'],
    236 => ['name' => 'Austria Locality 36 (2)'],
    237 => ['name' => 'Austria Locality 37 (2)'],
    238 => ['name' => 'Austria Locality 38 (2)'],
    239 => ['name' => 'Austria Locality 39 (2)'],
    240 => ['name' => 'Austria Locality 40 (2)'],
    241 => ['name' => 'Austria Locality 41 (2)'],
    242 => ['name' => 'Austria Locality 42 (2)'],
    243 => ['name' => 'Austria Locality 43 (2)'],
    244 => ['name' => 'Austria Locality 44 (2)'],
    245 => ['name' => 'Austria Locality 45 (2)'],
    246 => ['name' => 'Austria Locality 46 (2)'],
    247 => ['name' => 'Austria Locality 47 (2)'],
    248 => ['name' => 'Austria Locality 48 (2)'],
    249 => ['name' => 'Austria Locality 49 (2)'],
    250 => ['name' => 'Austria Locality 50 (2)'],
    251 => ['name' => 'Austria Locality 51 (2)'],
    252 => ['name' => 'Austria Locality 52 (2)'],
    253 => ['name' => 'Austria Locality 53 (2)'],
    254 => ['name' => 'Austria Locality 54 (2)'],
    255 => ['name' => 'Austria Locality 55 (2)'],
    256 => ['name' => 'Austria Locality 56 (2)'],
    257 => ['name' => 'Austria Locality 57 (2)'],
    258 => ['name' => 'Austria Locality 58 (2)'],
    259 => ['name' => 'Austria Locality 59 (2)'],
    260 => ['name' => 'Austria Locality 60 (2)']
];