<?php

return [
    1 => ['name' => 'Baku'],
    2 => ['name' => 'Ganja'],
    3 => ['name' => 'Sumqayit'],
    4 => ['name' => 'Mingachevir'],
    5 => ['name' => 'Lankaran'],
    6 => ['name' => 'Nakhchivan'],
    7 => ['name' => 'Shirvan'],
    8 => ['name' => 'Shaki'],
    9 => ['name' => 'Yevlakh'],
    10 => ['name' => 'Khirdalan'],
    11 => ['name' => 'Mastaga'],
    12 => ['name' => 'Salyan'],
    13 => ['name' => 'Hajigabul'],
    14 => ['name' => 'Agjabadi'],
    15 => ['name' => 'Barda'],
    16 => ['name' => 'Agdam'],
    17 => ['name' => 'Fuzuli'],
    18 => ['name' => 'Jabrayil'],
    19 => ['name' => 'Qubadli'],
    20 => ['name' => 'Zangilan'],
    21 => ['name' => 'Lachin'],
    22 => ['name' => 'Qabala'],
    23 => ['name' => 'Oghuz'],
    24 => ['name' => 'Shamakhi'],
    25 => ['name' => 'Ismailli'],
    26 => ['name' => 'Aghsu'],
    27 => ['name' => 'Goychay'],
    28 => ['name' => 'Ujar'],
    29 => ['name' => 'Zardab'],
    30 => ['name' => 'Kurdamir'],
    31 => ['name' => 'Imishli'],
    32 => ['name' => 'Saatli'],
    33 => ['name' => 'Sabirabad'],
    34 => ['name' => 'Bilasuvar'],
    35 => ['name' => 'Jalilabad'],
    36 => ['name' => 'Masally'],
    37 => ['name' => 'Lerik'],
    38 => ['name' => 'Yardimli'],
    39 => ['name' => 'Astara'],
    40 => ['name' => 'Qusar'],
    41 => ['name' => 'Khachmaz'],
    42 => ['name' => 'Quba'],
    43 => ['name' => 'Siyazan'],
    44 => ['name' => 'Shabran'],
    45 => ['name' => 'Gusar'],
    46 => ['name' => 'Guba'],
    47 => ['name' => 'Qakh'],
    48 => ['name' => 'Zagatala'],
    49 => ['name' => 'Balakan'],
    50 => ['name' => 'Tovuz'],
    51 => ['name' => 'Gadabay'],
    52 => ['name' => 'Dashkasan'],
    53 => ['name' => 'Goranboy'],
    54 => ['name' => 'Naftalan'],
    55 => ['name' => 'Tartar'],
    56 => ['name' => 'Aghdara'],
    57 => ['name' => 'Kalbajar'],
    58 => ['name' => 'Goygol'],
    59 => ['name' => 'Samukh'],
    60 => ['name' => 'Shamkir'],
     61 => ['name' => 'Azerbaijan Locality 1'],
     62 => ['name' => 'Azerbaijan Locality 2'],
     63 => ['name' => 'Azerbaijan Locality 3'],
     64 => ['name' => 'Azerbaijan Locality 4'],
     65 => ['name' => 'Azerbaijan Locality 5'],
     66 => ['name' => 'Azerbaijan Locality 6'],
     67 => ['name' => 'Azerbaijan Locality 7'],
     68 => ['name' => 'Azerbaijan Locality 8'],
     69 => ['name' => 'Azerbaijan Locality 9'],
     70 => ['name' => 'Azerbaijan Locality 10'],
     71 => ['name' => 'Azerbaijan Locality 11'],
     72 => ['name' => 'Azerbaijan Locality 12'],
     73 => ['name' => 'Azerbaijan Locality 13'],
     74 => ['name' => 'Azerbaijan Locality 14'],
     75 => ['name' => 'Azerbaijan Locality 15'],
     76 => ['name' => 'Azerbaijan Locality 16'],
     77 => ['name' => 'Azerbaijan Locality 17'],
     78 => ['name' => 'Azerbaijan Locality 18'],
     79 => ['name' => 'Azerbaijan Locality 19'],
     80 => ['name' => 'Azerbaijan Locality 20'],
     81 => ['name' => 'Azerbaijan Locality 21'],
     82 => ['name' => 'Azerbaijan Locality 22'],
     83 => ['name' => 'Azerbaijan Locality 23'],
     84 => ['name' => 'Azerbaijan Locality 24'],
     85 => ['name' => 'Azerbaijan Locality 25'],
     86 => ['name' => 'Azerbaijan Locality 26'],
     87 => ['name' => 'Azerbaijan Locality 27'],
     88 => ['name' => 'Azerbaijan Locality 28'],
     89 => ['name' => 'Azerbaijan Locality 29'],
     90 => ['name' => 'Azerbaijan Locality 30'],
     91 => ['name' => 'Azerbaijan Locality 31'],
     92 => ['name' => 'Azerbaijan Locality 32'],
     93 => ['name' => 'Azerbaijan Locality 33'],
     94 => ['name' => 'Azerbaijan Locality 34'],
     95 => ['name' => 'Azerbaijan Locality 35'],
     96 => ['name' => 'Azerbaijan Locality 36'],
     97 => ['name' => 'Azerbaijan Locality 37'],
     98 => ['name' => 'Azerbaijan Locality 38'],
     99 => ['name' => 'Azerbaijan Locality 39'],
    100 => ['name' => 'Azerbaijan Locality 40'],
    101 => ['name' => 'Azerbaijan Locality 41'],
    102 => ['name' => 'Azerbaijan Locality 42'],
    103 => ['name' => 'Azerbaijan Locality 43'],
    104 => ['name' => 'Azerbaijan Locality 44'],
    105 => ['name' => 'Azerbaijan Locality 45'],
    106 => ['name' => 'Azerbaijan Locality 46'],
    107 => ['name' => 'Azerbaijan Locality 47'],
    108 => ['name' => 'Azerbaijan Locality 48'],
    109 => ['name' => 'Azerbaijan Locality 49'],
    110 => ['name' => 'Azerbaijan Locality 50'],
    111 => ['name' => 'Azerbaijan Locality 51'],
    112 => ['name' => 'Azerbaijan Locality 52'],
    113 => ['name' => 'Azerbaijan Locality 53'],
    114 => ['name' => 'Azerbaijan Locality 54'],
    115 => ['name' => 'Azerbaijan Locality 55'],
    116 => ['name' => 'Azerbaijan Locality 56'],
    117 => ['name' => 'Azerbaijan Locality 57'],
    118 => ['name' => 'Azerbaijan Locality 58'],
    119 => ['name' => 'Azerbaijan Locality 59'],
    120 => ['name' => 'Azerbaijan Locality 60'],
    121 => ['name' => 'Azerbaijan Locality 61'],
    122 => ['name' => 'Azerbaijan Locality 62'],
    123 => ['name' => 'Azerbaijan Locality 63'],
    124 => ['name' => 'Azerbaijan Locality 64'],
    125 => ['name' => 'Azerbaijan Locality 65'],
    126 => ['name' => 'Azerbaijan Locality 66'],
    127 => ['name' => 'Azerbaijan Locality 67'],
    128 => ['name' => 'Azerbaijan Locality 68'],
    129 => ['name' => 'Azerbaijan Locality 69'],
    130 => ['name' => 'Azerbaijan Locality 70'],
    131 => ['name' => 'Azerbaijan Locality 71'],
    132 => ['name' => 'Azerbaijan Locality 72'],
    133 => ['name' => 'Azerbaijan Locality 73'],
    134 => ['name' => 'Azerbaijan Locality 74'],
    135 => ['name' => 'Azerbaijan Locality 75'],
    136 => ['name' => 'Azerbaijan Locality 76'],
    137 => ['name' => 'Azerbaijan Locality 77'],
    138 => ['name' => 'Azerbaijan Locality 78'],
    139 => ['name' => 'Azerbaijan Locality 79'],
    140 => ['name' => 'Azerbaijan Locality 80'],
    141 => ['name' => 'Azerbaijan Locality 81'],
    142 => ['name' => 'Azerbaijan Locality 82'],
    143 => ['name' => 'Azerbaijan Locality 83'],
    144 => ['name' => 'Azerbaijan Locality 84'],
    145 => ['name' => 'Azerbaijan Locality 85'],
    146 => ['name' => 'Azerbaijan Locality 86'],
    147 => ['name' => 'Azerbaijan Locality 87'],
    148 => ['name' => 'Azerbaijan Locality 88'],
    149 => ['name' => 'Azerbaijan Locality 89'],
    150 => ['name' => 'Azerbaijan Locality 90'],
    151 => ['name' => 'Azerbaijan Locality 91'],
    152 => ['name' => 'Azerbaijan Locality 92'],
    153 => ['name' => 'Azerbaijan Locality 93'],
    154 => ['name' => 'Azerbaijan Locality 94'],
    155 => ['name' => 'Azerbaijan Locality 95'],
    156 => ['name' => 'Azerbaijan Locality 96'],
    157 => ['name' => 'Azerbaijan Locality 97'],
    158 => ['name' => 'Azerbaijan Locality 98'],
    159 => ['name' => 'Azerbaijan Locality 99'],
    160 => ['name' => 'Azerbaijan Locality 100'],
    161 => ['name' => 'Azerbaijan Locality 101'],
    162 => ['name' => 'Azerbaijan Locality 102'],
    163 => ['name' => 'Azerbaijan Locality 103'],
    164 => ['name' => 'Azerbaijan Locality 104'],
    165 => ['name' => 'Azerbaijan Locality 105'],
    166 => ['name' => 'Azerbaijan Locality 106'],
    167 => ['name' => 'Azerbaijan Locality 107'],
    168 => ['name' => 'Azerbaijan Locality 108'],
    169 => ['name' => 'Azerbaijan Locality 109'],
    170 => ['name' => 'Azerbaijan Locality 110'],
    171 => ['name' => 'Azerbaijan Locality 111'],
    172 => ['name' => 'Azerbaijan Locality 112'],
    173 => ['name' => 'Azerbaijan Locality 113'],
    174 => ['name' => 'Azerbaijan Locality 114'],
    175 => ['name' => 'Azerbaijan Locality 115'],
    176 => ['name' => 'Azerbaijan Locality 116'],
    177 => ['name' => 'Azerbaijan Locality 117'],
    178 => ['name' => 'Azerbaijan Locality 118'],
    179 => ['name' => 'Azerbaijan Locality 119'],
    180 => ['name' => 'Azerbaijan Locality 120'],
    181 => ['name' => 'Azerbaijan Locality 121'],
    182 => ['name' => 'Azerbaijan Locality 122'],
    183 => ['name' => 'Azerbaijan Locality 123'],
    184 => ['name' => 'Azerbaijan Locality 124'],
    185 => ['name' => 'Azerbaijan Locality 125'],
    186 => ['name' => 'Azerbaijan Locality 126'],
    187 => ['name' => 'Azerbaijan Locality 127'],
    188 => ['name' => 'Azerbaijan Locality 128'],
    189 => ['name' => 'Azerbaijan Locality 129'],
    190 => ['name' => 'Azerbaijan Locality 130'],
    191 => ['name' => 'Azerbaijan Locality 131'],
    192 => ['name' => 'Azerbaijan Locality 132'],
    193 => ['name' => 'Azerbaijan Locality 133'],
    194 => ['name' => 'Azerbaijan Locality 134'],
    195 => ['name' => 'Azerbaijan Locality 135'],
    196 => ['name' => 'Azerbaijan Locality 136'],
    197 => ['name' => 'Azerbaijan Locality 137'],
    198 => ['name' => 'Azerbaijan Locality 138'],
    199 => ['name' => 'Azerbaijan Locality 139'],
    200 => ['name' => 'Azerbaijan Locality 140'],
    201 => ['name' => 'Azerbaijan Locality 1 (2)'],
    202 => ['name' => 'Azerbaijan Locality 2 (2)'],
    203 => ['name' => 'Azerbaijan Locality 3 (2)'],
    204 => ['name' => 'Azerbaijan Locality 4 (2)'],
    205 => ['name' => 'Azerbaijan Locality 5 (2)'],
    206 => ['name' => 'Azerbaijan Locality 6 (2)'],
    207 => ['name' => 'Azerbaijan Locality 7 (2)'],
    208 => ['name' => 'Azerbaijan Locality 8 (2)'],
    209 => ['name' => 'Azerbaijan Locality 9 (2)'],
    210 => ['name' => 'Azerbaijan Locality 10 (2)'],
    211 => ['name' => 'Azerbaijan Locality 11 (2)'],
    212 => ['name' => 'Azerbaijan Locality 12 (2)'],
    213 => ['name' => 'Azerbaijan Locality 13 (2)'],
    214 => ['name' => 'Azerbaijan Locality 14 (2)'],
    215 => ['name' => 'Azerbaijan Locality 15 (2)'],
    216 => ['name' => 'Azerbaijan Locality 16 (2)'],
    217 => ['name' => 'Azerbaijan Locality 17 (2)'],
    218 => ['name' => 'Azerbaijan Locality 18 (2)'],
    219 => ['name' => 'Azerbaijan Locality 19 (2)'],
    220 => ['name' => 'Azerbaijan Locality 20 (2)'],
    221 => ['name' => 'Azerbaijan Locality 21 (2)'],
    222 => ['name' => 'Azerbaijan Locality 22 (2)'],
    223 => ['name' => 'Azerbaijan Locality 23 (2)'],
    224 => ['name' => 'Azerbaijan Locality 24 (2)'],
    225 => ['name' => 'Azerbaijan Locality 25 (2)'],
    226 => ['name' => 'Azerbaijan Locality 26 (2)'],
    227 => ['name' => 'Azerbaijan Locality 27 (2)'],
    228 => ['name' => 'Azerbaijan Locality 28 (2)'],
    229 => ['name' => 'Azerbaijan Locality 29 (2)'],
    230 => ['name' => 'Azerbaijan Locality 30 (2)'],
    231 => ['name' => 'Azerbaijan Locality 31 (2)'],
    232 => ['name' => 'Azerbaijan Locality 32 (2)'],
    233 => ['name' => 'Azerbaijan Locality 33 (2)'],
    234 => ['name' => 'Azerbaijan Locality 34 (2)'],
    235 => ['name' => 'Azerbaijan Locality 35 (2)'],
    236 => ['name' => 'Azerbaijan Locality 36 (2)'],
    237 => ['name' => 'Azerbaijan Locality 37 (2)'],
    238 => ['name' => 'Azerbaijan Locality 38 (2)'],
    239 => ['name' => 'Azerbaijan Locality 39 (2)'],
    240 => ['name' => 'Azerbaijan Locality 40 (2)'],
    241 => ['name' => 'Azerbaijan Locality 41 (2)'],
    242 => ['name' => 'Azerbaijan Locality 42 (2)'],
    243 => ['name' => 'Azerbaijan Locality 43 (2)'],
    244 => ['name' => 'Azerbaijan Locality 44 (2)'],
    245 => ['name' => 'Azerbaijan Locality 45 (2)'],
    246 => ['name' => 'Azerbaijan Locality 46 (2)'],
    247 => ['name' => 'Azerbaijan Locality 47 (2)'],
    248 => ['name' => 'Azerbaijan Locality 48 (2)'],
    249 => ['name' => 'Azerbaijan Locality 49 (2)'],
    250 => ['name' => 'Azerbaijan Locality 50 (2)'],
    251 => ['name' => 'Azerbaijan Locality 51 (2)'],
    252 => ['name' => 'Azerbaijan Locality 52 (2)'],
    253 => ['name' => 'Azerbaijan Locality 53 (2)'],
    254 => ['name' => 'Azerbaijan Locality 54 (2)'],
    255 => ['name' => 'Azerbaijan Locality 55 (2)'],
    256 => ['name' => 'Azerbaijan Locality 56 (2)'],
    257 => ['name' => 'Azerbaijan Locality 57 (2)'],
    258 => ['name' => 'Azerbaijan Locality 58 (2)'],
    259 => ['name' => 'Azerbaijan Locality 59 (2)'],
    260 => ['name' => 'Azerbaijan Locality 60 (2)']
];