<?php

return [
    1 => ['name' => 'Sofia'],
    2 => ['name' => 'Plovdiv'],
    3 => ['name' => 'Varna'],
    4 => ['name' => 'Burgas'],
    5 => ['name' => 'Ruse'],
    6 => ['name' => 'Stara Zagora'],
    7 => ['name' => 'Pleven'],
    8 => ['name' => 'Sliven'],
    9 => ['name' => 'Dobrich'],
    10 => ['name' => 'Shumen'],
    11 => ['name' => 'Pernik'],
    12 => ['name' => 'Haskovo'],
    13 => ['name' => 'Yambol'],
    14 => ['name' => 'Pazardzhik'],
    15 => ['name' => 'Blagoevgrad'],
    16 => ['name' => 'Veliko Tarnovo'],
    17 => ['name' => 'Vratsa'],
    18 => ['name' => 'Gabrovo'],
    19 => ['name' => 'Asenovgrad'],
    20 => ['name' => 'Vidin'],
    21 => ['name' => 'Kazanlak'],
    22 => ['name' => 'Kyustendil'],
    23 => ['name' => 'Montana'],
    24 => ['name' => 'Dimitrovgrad'],
    25 => ['name' => 'Targovishte'],
    26 => ['name' => 'Lovech'],
    27 => ['name' => 'Silistra'],
    28 => ['name' => 'Razgrad'],
    29 => ['name' => 'Gorna Oryahovitsa'],
    30 => ['name' => 'Smolyan'],
    31 => ['name' => 'Petrich'],
    32 => ['name' => 'Sandanski'],
    33 => ['name' => 'Samokov'],
    34 => ['name' => 'Lom'],
    35 => ['name' => 'Dupnitsa'],
    36 => ['name' => 'Svishtov'],
    37 => ['name' => 'Nova Zagora'],
    38 => ['name' => 'Sevlievo'],
    39 => ['name' => 'Troyan'],
    40 => ['name' => 'Aytos'],
    41 => ['name' => 'Botevgrad'],
    42 => ['name' => 'Gotse Delchev'],
    43 => ['name' => 'Karlovo'],
    44 => ['name' => 'Panagyurishte'],
    45 => ['name' => 'Svilengrad'],
    46 => ['name' => 'Harmanli'],
    47 => ['name' => 'Radnevo'],
    48 => ['name' => 'Peshtera'],
    49 => ['name' => 'Chirpan'],
    50 => ['name' => 'Popovo'],
    51 => ['name' => 'Rakovski'],
    52 => ['name' => 'Novi Iskar'],
    53 => ['name' => 'Byala Slatina'],
    54 => ['name' => 'Pomorie'],
    55 => ['name' => 'Nesebar'],
    56 => ['name' => 'Radomir'],
    57 => ['name' => 'Kozloduy'],
    58 => ['name' => 'Berkovitsa'],
    59 => ['name' => 'Pirdop'],
    60 => ['name' => 'Karnobat'],
     61 => ['name' => 'Bulgaria Locality 1'],
     62 => ['name' => 'Bulgaria Locality 2'],
     63 => ['name' => 'Bulgaria Locality 3'],
     64 => ['name' => 'Bulgaria Locality 4'],
     65 => ['name' => 'Bulgaria Locality 5'],
     66 => ['name' => 'Bulgaria Locality 6'],
     67 => ['name' => 'Bulgaria Locality 7'],
     68 => ['name' => 'Bulgaria Locality 8'],
     69 => ['name' => 'Bulgaria Locality 9'],
     70 => ['name' => 'Bulgaria Locality 10'],
     71 => ['name' => 'Bulgaria Locality 11'],
     72 => ['name' => 'Bulgaria Locality 12'],
     73 => ['name' => 'Bulgaria Locality 13'],
     74 => ['name' => 'Bulgaria Locality 14'],
     75 => ['name' => 'Bulgaria Locality 15'],
     76 => ['name' => 'Bulgaria Locality 16'],
     77 => ['name' => 'Bulgaria Locality 17'],
     78 => ['name' => 'Bulgaria Locality 18'],
     79 => ['name' => 'Bulgaria Locality 19'],
     80 => ['name' => 'Bulgaria Locality 20'],
     81 => ['name' => 'Bulgaria Locality 21'],
     82 => ['name' => 'Bulgaria Locality 22'],
     83 => ['name' => 'Bulgaria Locality 23'],
     84 => ['name' => 'Bulgaria Locality 24'],
     85 => ['name' => 'Bulgaria Locality 25'],
     86 => ['name' => 'Bulgaria Locality 26'],
     87 => ['name' => 'Bulgaria Locality 27'],
     88 => ['name' => 'Bulgaria Locality 28'],
     89 => ['name' => 'Bulgaria Locality 29'],
     90 => ['name' => 'Bulgaria Locality 30'],
     91 => ['name' => 'Bulgaria Locality 31'],
     92 => ['name' => 'Bulgaria Locality 32'],
     93 => ['name' => 'Bulgaria Locality 33'],
     94 => ['name' => 'Bulgaria Locality 34'],
     95 => ['name' => 'Bulgaria Locality 35'],
     96 => ['name' => 'Bulgaria Locality 36'],
     97 => ['name' => 'Bulgaria Locality 37'],
     98 => ['name' => 'Bulgaria Locality 38'],
     99 => ['name' => 'Bulgaria Locality 39'],
    100 => ['name' => 'Bulgaria Locality 40'],
    101 => ['name' => 'Bulgaria Locality 41'],
    102 => ['name' => 'Bulgaria Locality 42'],
    103 => ['name' => 'Bulgaria Locality 43'],
    104 => ['name' => 'Bulgaria Locality 44'],
    105 => ['name' => 'Bulgaria Locality 45'],
    106 => ['name' => 'Bulgaria Locality 46'],
    107 => ['name' => 'Bulgaria Locality 47'],
    108 => ['name' => 'Bulgaria Locality 48'],
    109 => ['name' => 'Bulgaria Locality 49'],
    110 => ['name' => 'Bulgaria Locality 50'],
    111 => ['name' => 'Bulgaria Locality 51'],
    112 => ['name' => 'Bulgaria Locality 52'],
    113 => ['name' => 'Bulgaria Locality 53'],
    114 => ['name' => 'Bulgaria Locality 54'],
    115 => ['name' => 'Bulgaria Locality 55'],
    116 => ['name' => 'Bulgaria Locality 56'],
    117 => ['name' => 'Bulgaria Locality 57'],
    118 => ['name' => 'Bulgaria Locality 58'],
    119 => ['name' => 'Bulgaria Locality 59'],
    120 => ['name' => 'Bulgaria Locality 60'],
    121 => ['name' => 'Bulgaria Locality 61'],
    122 => ['name' => 'Bulgaria Locality 62'],
    123 => ['name' => 'Bulgaria Locality 63'],
    124 => ['name' => 'Bulgaria Locality 64'],
    125 => ['name' => 'Bulgaria Locality 65'],
    126 => ['name' => 'Bulgaria Locality 66'],
    127 => ['name' => 'Bulgaria Locality 67'],
    128 => ['name' => 'Bulgaria Locality 68'],
    129 => ['name' => 'Bulgaria Locality 69'],
    130 => ['name' => 'Bulgaria Locality 70'],
    131 => ['name' => 'Bulgaria Locality 71'],
    132 => ['name' => 'Bulgaria Locality 72'],
    133 => ['name' => 'Bulgaria Locality 73'],
    134 => ['name' => 'Bulgaria Locality 74'],
    135 => ['name' => 'Bulgaria Locality 75'],
    136 => ['name' => 'Bulgaria Locality 76'],
    137 => ['name' => 'Bulgaria Locality 77'],
    138 => ['name' => 'Bulgaria Locality 78'],
    139 => ['name' => 'Bulgaria Locality 79'],
    140 => ['name' => 'Bulgaria Locality 80'],
    141 => ['name' => 'Bulgaria Locality 81'],
    142 => ['name' => 'Bulgaria Locality 82'],
    143 => ['name' => 'Bulgaria Locality 83'],
    144 => ['name' => 'Bulgaria Locality 84'],
    145 => ['name' => 'Bulgaria Locality 85'],
    146 => ['name' => 'Bulgaria Locality 86'],
    147 => ['name' => 'Bulgaria Locality 87'],
    148 => ['name' => 'Bulgaria Locality 88'],
    149 => ['name' => 'Bulgaria Locality 89'],
    150 => ['name' => 'Bulgaria Locality 90'],
    151 => ['name' => 'Bulgaria Locality 91'],
    152 => ['name' => 'Bulgaria Locality 92'],
    153 => ['name' => 'Bulgaria Locality 93'],
    154 => ['name' => 'Bulgaria Locality 94'],
    155 => ['name' => 'Bulgaria Locality 95'],
    156 => ['name' => 'Bulgaria Locality 96'],
    157 => ['name' => 'Bulgaria Locality 97'],
    158 => ['name' => 'Bulgaria Locality 98'],
    159 => ['name' => 'Bulgaria Locality 99'],
    160 => ['name' => 'Bulgaria Locality 100'],
    161 => ['name' => 'Bulgaria Locality 101'],
    162 => ['name' => 'Bulgaria Locality 102'],
    163 => ['name' => 'Bulgaria Locality 103'],
    164 => ['name' => 'Bulgaria Locality 104'],
    165 => ['name' => 'Bulgaria Locality 105'],
    166 => ['name' => 'Bulgaria Locality 106'],
    167 => ['name' => 'Bulgaria Locality 107'],
    168 => ['name' => 'Bulgaria Locality 108'],
    169 => ['name' => 'Bulgaria Locality 109'],
    170 => ['name' => 'Bulgaria Locality 110'],
    171 => ['name' => 'Bulgaria Locality 111'],
    172 => ['name' => 'Bulgaria Locality 112'],
    173 => ['name' => 'Bulgaria Locality 113'],
    174 => ['name' => 'Bulgaria Locality 114'],
    175 => ['name' => 'Bulgaria Locality 115'],
    176 => ['name' => 'Bulgaria Locality 116'],
    177 => ['name' => 'Bulgaria Locality 117'],
    178 => ['name' => 'Bulgaria Locality 118'],
    179 => ['name' => 'Bulgaria Locality 119'],
    180 => ['name' => 'Bulgaria Locality 120'],
    181 => ['name' => 'Bulgaria Locality 121'],
    182 => ['name' => 'Bulgaria Locality 122'],
    183 => ['name' => 'Bulgaria Locality 123'],
    184 => ['name' => 'Bulgaria Locality 124'],
    185 => ['name' => 'Bulgaria Locality 125'],
    186 => ['name' => 'Bulgaria Locality 126'],
    187 => ['name' => 'Bulgaria Locality 127'],
    188 => ['name' => 'Bulgaria Locality 128'],
    189 => ['name' => 'Bulgaria Locality 129'],
    190 => ['name' => 'Bulgaria Locality 130'],
    191 => ['name' => 'Bulgaria Locality 131'],
    192 => ['name' => 'Bulgaria Locality 132'],
    193 => ['name' => 'Bulgaria Locality 133'],
    194 => ['name' => 'Bulgaria Locality 134'],
    195 => ['name' => 'Bulgaria Locality 135'],
    196 => ['name' => 'Bulgaria Locality 136'],
    197 => ['name' => 'Bulgaria Locality 137'],
    198 => ['name' => 'Bulgaria Locality 138'],
    199 => ['name' => 'Bulgaria Locality 139'],
    200 => ['name' => 'Bulgaria Locality 140'],
    201 => ['name' => 'Bulgaria Locality 1 (2)'],
    202 => ['name' => 'Bulgaria Locality 2 (2)'],
    203 => ['name' => 'Bulgaria Locality 3 (2)'],
    204 => ['name' => 'Bulgaria Locality 4 (2)'],
    205 => ['name' => 'Bulgaria Locality 5 (2)'],
    206 => ['name' => 'Bulgaria Locality 6 (2)'],
    207 => ['name' => 'Bulgaria Locality 7 (2)'],
    208 => ['name' => 'Bulgaria Locality 8 (2)'],
    209 => ['name' => 'Bulgaria Locality 9 (2)'],
    210 => ['name' => 'Bulgaria Locality 10 (2)'],
    211 => ['name' => 'Bulgaria Locality 11 (2)'],
    212 => ['name' => 'Bulgaria Locality 12 (2)'],
    213 => ['name' => 'Bulgaria Locality 13 (2)'],
    214 => ['name' => 'Bulgaria Locality 14 (2)'],
    215 => ['name' => 'Bulgaria Locality 15 (2)'],
    216 => ['name' => 'Bulgaria Locality 16 (2)'],
    217 => ['name' => 'Bulgaria Locality 17 (2)'],
    218 => ['name' => 'Bulgaria Locality 18 (2)'],
    219 => ['name' => 'Bulgaria Locality 19 (2)'],
    220 => ['name' => 'Bulgaria Locality 20 (2)'],
    221 => ['name' => 'Bulgaria Locality 21 (2)'],
    222 => ['name' => 'Bulgaria Locality 22 (2)'],
    223 => ['name' => 'Bulgaria Locality 23 (2)'],
    224 => ['name' => 'Bulgaria Locality 24 (2)'],
    225 => ['name' => 'Bulgaria Locality 25 (2)'],
    226 => ['name' => 'Bulgaria Locality 26 (2)'],
    227 => ['name' => 'Bulgaria Locality 27 (2)'],
    228 => ['name' => 'Bulgaria Locality 28 (2)'],
    229 => ['name' => 'Bulgaria Locality 29 (2)'],
    230 => ['name' => 'Bulgaria Locality 30 (2)'],
    231 => ['name' => 'Bulgaria Locality 31 (2)'],
    232 => ['name' => 'Bulgaria Locality 32 (2)'],
    233 => ['name' => 'Bulgaria Locality 33 (2)'],
    234 => ['name' => 'Bulgaria Locality 34 (2)'],
    235 => ['name' => 'Bulgaria Locality 35 (2)'],
    236 => ['name' => 'Bulgaria Locality 36 (2)'],
    237 => ['name' => 'Bulgaria Locality 37 (2)'],
    238 => ['name' => 'Bulgaria Locality 38 (2)'],
    239 => ['name' => 'Bulgaria Locality 39 (2)'],
    240 => ['name' => 'Bulgaria Locality 40 (2)'],
    241 => ['name' => 'Bulgaria Locality 41 (2)'],
    242 => ['name' => 'Bulgaria Locality 42 (2)'],
    243 => ['name' => 'Bulgaria Locality 43 (2)'],
    244 => ['name' => 'Bulgaria Locality 44 (2)'],
    245 => ['name' => 'Bulgaria Locality 45 (2)'],
    246 => ['name' => 'Bulgaria Locality 46 (2)'],
    247 => ['name' => 'Bulgaria Locality 47 (2)'],
    248 => ['name' => 'Bulgaria Locality 48 (2)'],
    249 => ['name' => 'Bulgaria Locality 49 (2)'],
    250 => ['name' => 'Bulgaria Locality 50 (2)'],
    251 => ['name' => 'Bulgaria Locality 51 (2)'],
    252 => ['name' => 'Bulgaria Locality 52 (2)'],
    253 => ['name' => 'Bulgaria Locality 53 (2)'],
    254 => ['name' => 'Bulgaria Locality 54 (2)'],
    255 => ['name' => 'Bulgaria Locality 55 (2)'],
    256 => ['name' => 'Bulgaria Locality 56 (2)'],
    257 => ['name' => 'Bulgaria Locality 57 (2)'],
    258 => ['name' => 'Bulgaria Locality 58 (2)'],
    259 => ['name' => 'Bulgaria Locality 59 (2)'],
    260 => ['name' => 'Bulgaria Locality 60 (2)']
];