<?php

return [
    1 => ['name' => 'Minsk', 'region' => 'Minsk'],
    2 => ['name' => 'Sebeža', 'region' => 'Sebeža'],
    3 => ['name' => 'Gomel'],
    4 => ['name' => 'Mogilev'],
      3 => ['name' => 'Vitebsk'],
      4 => ['name' => 'Grodno'],
      7 => ['name' => 'Brest'],
      8 => ['name' => 'Bobruisk'],
      9 => ['name' => 'Baranavichy'],
     10 => ['name' => 'Barysau'],
     11 => ['name' => 'Pinsk'],
     12 => ['name' => 'Orsha'],
     13 => ['name' => 'Mazyr'],
     14 => ['name' => 'Salihorsk'],
     15 => ['name' => 'Novopolotsk'],
     16 => ['name' => 'Lida'],
     17 => ['name' => 'Maladzyechna'],
     18 => ['name' => 'Polatsk'],
     19 => ['name' => 'Zhlobin'],
     20 => ['name' => 'Svetlahorsk'],
     21 => ['name' => 'Rechytsa'],
     22 => ['name' => 'Slutsk'],
     23 => ['name' => 'Zhodzina'],
     24 => ['name' => 'Slonim'],
     25 => ['name' => 'Kobryn'],
     26 => ['name' => 'Vawkavysk'],
     27 => ['name' => 'Kalinkavichy'],
     28 => ['name' => 'Smarhon'],
     29 => ['name' => 'Rahachow'],
     30 => ['name' => 'Asipovichy'],
     31 => ['name' => 'Horki'],
     32 => ['name' => 'Navahrudak'],
     33 => ['name' => 'Vilyeyka'],
     34 => ['name' => 'Byaroza'],
     35 => ['name' => 'Krychaw'],
     36 => ['name' => 'Dzyarzhynsk'],
     37 => ['name' => 'Ivanava'],
     38 => ['name' => 'Dobrush'],
     39 => ['name' => 'Hlybokaye'],
     40 => ['name' => 'Luninyets'],
     41 => ['name' => 'Pastavy'],
     42 => ['name' => 'Stolin'],
     43 => ['name' => 'Lyepyel'],
     44 => ['name' => 'Marina Horka'],
     45 => ['name' => 'Klimavichy'],
     46 => ['name' => 'Kastsyukovichy'],
     47 => ['name' => 'Buda-Kashalyova'],
     48 => ['name' => 'Bykhaw'],
     49 => ['name' => 'Homyel'],
     50 => ['name' => 'Chavusy'],
     51 => ['name' => 'Talachyn'],
     52 => ['name' => 'Braslaw'],
     53 => ['name' => 'Shklow'],
     54 => ['name' => 'Krupki'],
     55 => ['name' => 'Uzda'],
     56 => ['name' => 'Drahichyn'],
     57 => ['name' => 'Klichaw'],
     58 => ['name' => 'Masty'],
     59 => ['name' => 'Vetka'],
     60 => ['name' => 'Chachersk'],
     61 => ['name' => 'Turau'],
     62 => ['name' => 'Belarus Locality 1'],
     63 => ['name' => 'Belarus Locality 2'],
     64 => ['name' => 'Belarus Locality 3'],
     65 => ['name' => 'Belarus Locality 4'],
     66 => ['name' => 'Belarus Locality 5'],
     67 => ['name' => 'Belarus Locality 6'],
     68 => ['name' => 'Belarus Locality 7'],
     69 => ['name' => 'Belarus Locality 8'],
     70 => ['name' => 'Belarus Locality 9'],
     71 => ['name' => 'Belarus Locality 10'],
     72 => ['name' => 'Belarus Locality 11'],
     73 => ['name' => 'Belarus Locality 12'],
     74 => ['name' => 'Belarus Locality 13'],
     75 => ['name' => 'Belarus Locality 14'],
     76 => ['name' => 'Belarus Locality 15'],
     77 => ['name' => 'Belarus Locality 16'],
     78 => ['name' => 'Belarus Locality 17'],
     79 => ['name' => 'Belarus Locality 18'],
     80 => ['name' => 'Belarus Locality 19'],
     81 => ['name' => 'Belarus Locality 20'],
     82 => ['name' => 'Belarus Locality 21'],
     83 => ['name' => 'Belarus Locality 22'],
     84 => ['name' => 'Belarus Locality 23'],
     85 => ['name' => 'Belarus Locality 24'],
     86 => ['name' => 'Belarus Locality 25'],
     87 => ['name' => 'Belarus Locality 26'],
     88 => ['name' => 'Belarus Locality 27'],
     89 => ['name' => 'Belarus Locality 28'],
     90 => ['name' => 'Belarus Locality 29'],
     91 => ['name' => 'Belarus Locality 30'],
     92 => ['name' => 'Belarus Locality 31'],
     93 => ['name' => 'Belarus Locality 32'],
     94 => ['name' => 'Belarus Locality 33'],
     95 => ['name' => 'Belarus Locality 34'],
     96 => ['name' => 'Belarus Locality 35'],
     97 => ['name' => 'Belarus Locality 36'],
     98 => ['name' => 'Belarus Locality 37'],
     99 => ['name' => 'Belarus Locality 38'],
     100 => ['name' => 'Belarus Locality 39'],
     101 => ['name' => 'Belarus Locality 40'],
    102 => ['name' => 'Belarus Locality 41'],
    103 => ['name' => 'Belarus Locality 42'],
    104 => ['name' => 'Belarus Locality 43'],
    105 => ['name' => 'Belarus Locality 44'],
    106 => ['name' => 'Belarus Locality 45'],
    107 => ['name' => 'Belarus Locality 46'],
    108 => ['name' => 'Belarus Locality 47'],
    109 => ['name' => 'Belarus Locality 48'],
    110 => ['name' => 'Belarus Locality 49'],
    111 => ['name' => 'Belarus Locality 50'],
    112 => ['name' => 'Belarus Locality 51'],
    113 => ['name' => 'Belarus Locality 52'],
    114 => ['name' => 'Belarus Locality 53'],
    115 => ['name' => 'Belarus Locality 54'],
    116 => ['name' => 'Belarus Locality 55'],
    117 => ['name' => 'Belarus Locality 56'],
    118 => ['name' => 'Belarus Locality 57'],
    119 => ['name' => 'Belarus Locality 58'],
    120 => ['name' => 'Belarus Locality 59'],
    121 => ['name' => 'Belarus Locality 60'],
    122 => ['name' => 'Belarus Locality 61'],
    123 => ['name' => 'Belarus Locality 62'],
    124 => ['name' => 'Belarus Locality 63'],
    125 => ['name' => 'Belarus Locality 64'],
    126 => ['name' => 'Belarus Locality 65'],
    127 => ['name' => 'Belarus Locality 66'],
    128 => ['name' => 'Belarus Locality 67'],
    129 => ['name' => 'Belarus Locality 68'],
    130 => ['name' => 'Belarus Locality 69'],
    131 => ['name' => 'Belarus Locality 70'],
    132 => ['name' => 'Belarus Locality 71'],
    133 => ['name' => 'Belarus Locality 72'],
    134 => ['name' => 'Belarus Locality 73'],
    135 => ['name' => 'Belarus Locality 74'],
    136 => ['name' => 'Belarus Locality 75'],
    137 => ['name' => 'Belarus Locality 76'],
    138 => ['name' => 'Belarus Locality 77'],
    139 => ['name' => 'Belarus Locality 78'],
    140 => ['name' => 'Belarus Locality 79'],
    141 => ['name' => 'Belarus Locality 80'],
    142 => ['name' => 'Belarus Locality 81'],
    143 => ['name' => 'Belarus Locality 82'],
    144 => ['name' => 'Belarus Locality 83'],
    145 => ['name' => 'Belarus Locality 84'],
    146 => ['name' => 'Belarus Locality 85'],
    147 => ['name' => 'Belarus Locality 86'],
    148 => ['name' => 'Belarus Locality 87'],
    149 => ['name' => 'Belarus Locality 88'],
    150 => ['name' => 'Belarus Locality 89'],
    151 => ['name' => 'Belarus Locality 90'],
    152 => ['name' => 'Belarus Locality 91'],
    153 => ['name' => 'Belarus Locality 92'],
    154 => ['name' => 'Belarus Locality 93'],
    155 => ['name' => 'Belarus Locality 94'],
    156 => ['name' => 'Belarus Locality 95'],
    157 => ['name' => 'Belarus Locality 96'],
    158 => ['name' => 'Belarus Locality 97'],
    159 => ['name' => 'Belarus Locality 98'],
    160 => ['name' => 'Belarus Locality 99'],
    161 => ['name' => 'Belarus Locality 100'],
    162 => ['name' => 'Belarus Locality 101'],
    163 => ['name' => 'Belarus Locality 102'],
    164 => ['name' => 'Belarus Locality 103'],
    165 => ['name' => 'Belarus Locality 104'],
    166 => ['name' => 'Belarus Locality 105'],
    167 => ['name' => 'Belarus Locality 106'],
    168 => ['name' => 'Belarus Locality 107'],
    169 => ['name' => 'Belarus Locality 108'],
    170 => ['name' => 'Belarus Locality 109'],
    171 => ['name' => 'Belarus Locality 110'],
    172 => ['name' => 'Belarus Locality 111'],
    173 => ['name' => 'Belarus Locality 112'],
    174 => ['name' => 'Belarus Locality 113'],
    175 => ['name' => 'Belarus Locality 114'],
    176 => ['name' => 'Belarus Locality 115'],
    177 => ['name' => 'Belarus Locality 116'],
    178 => ['name' => 'Belarus Locality 117'],
    179 => ['name' => 'Belarus Locality 118'],
    180 => ['name' => 'Belarus Locality 119'],
    181 => ['name' => 'Belarus Locality 120'],
    182 => ['name' => 'Belarus Locality 121'],
    183 => ['name' => 'Belarus Locality 122'],
    184 => ['name' => 'Belarus Locality 123'],
    185 => ['name' => 'Belarus Locality 124'],
    186 => ['name' => 'Belarus Locality 125'],
    187 => ['name' => 'Belarus Locality 126'],
    188 => ['name' => 'Belarus Locality 127'],
    189 => ['name' => 'Belarus Locality 128'],
    190 => ['name' => 'Belarus Locality 129'],
    191 => ['name' => 'Belarus Locality 130'],
    192 => ['name' => 'Belarus Locality 131'],
    193 => ['name' => 'Belarus Locality 132'],
    194 => ['name' => 'Belarus Locality 133'],
    195 => ['name' => 'Belarus Locality 134'],
    196 => ['name' => 'Belarus Locality 135'],
    197 => ['name' => 'Belarus Locality 136'],
    198 => ['name' => 'Belarus Locality 137'],
    199 => ['name' => 'Belarus Locality 138'],
    200 => ['name' => 'Belarus Locality 139'],
    201 => ['name' => 'Belarus Locality 140'],
    202 => ['name' => 'Gomel (2)']
];