<?php

return [
    1 => ['name' => 'Prague'],
    2 => ['name' => 'Brno'],
    3 => ['name' => 'Ostrava'],
    4 => ['name' => 'Pilsen'],
    5 => ['name' => 'Liberec'],
    6 => ['name' => 'Olomouc'],
    7 => ['name' => 'České Budějovice'],
    8 => ['name' => 'Hradec Králové'],
    9 => ['name' => 'Ústí nad Labem'],
    10 => ['name' => 'Pardubice'],
    11 => ['name' => 'Zlín'],
    12 => ['name' => 'Havířov'],
    13 => ['name' => 'Kladno'],
    14 => ['name' => 'Most'],
    15 => ['name' => 'Opava'],
    16 => ['name' => 'Frýdek-Místek'],
    17 => ['name' => 'Karviná'],
    18 => ['name' => 'Jihlava'],
    19 => ['name' => 'Teplice'],
    20 => ['name' => 'Chomutov'],
    21 => ['name' => 'Jablonec nad Nisou'],
    22 => ['name' => 'Prostějov'],
    23 => ['name' => 'Mladá Boleslav'],
    24 => ['name' => 'Česká Lípa'],
    25 => ['name' => 'Třebíč'],
    26 => ['name' => 'Trutnov'],
    27 => ['name' => 'Znojmo'],
    28 => ['name' => 'Přerov'],
    29 => ['name' => 'Cheb'],
    30 => ['name' => 'Kolín'],
    31 => ['name' => 'Kroměříž'],
    32 => ['name' => 'Šumperk'],
    33 => ['name' => 'Vsetín'],
    34 => ['name' => 'Litoměřice'],
    35 => ['name' => 'Nový Jičín'],
    36 => ['name' => 'Uherské Hradiště'],
    37 => ['name' => 'Hodonín'],
    38 => ['name' => 'Břeclav'],
    39 => ['name' => 'Žďár nad Sázavou'],
    40 => ['name' => 'Blansko'],
    41 => ['name' => 'Sokolov'],
    42 => ['name' => 'Kladno'],
    43 => ['name' => 'Litvinov'],
    44 => ['name' => 'Valašské Meziříčí'],
    45 => ['name' => 'Chrudim'],
    46 => ['name' => 'Havlíčkův Brod'],
    47 => ['name' => 'Kopřivnice'],
    48 => ['name' => 'Kutná Hora'],
    49 => ['name' => 'Kyjov'],
    50 => ['name' => 'Náchod'],
    51 => ['name' => 'Jindřichův Hradec'],
    52 => ['name' => 'Děčín'],
    53 => ['name' => 'Varnsdorf'],
    54 => ['name' => 'Orlová'],
    55 => ['name' => 'Beroun'],
    56 => ['name' => 'Tábor'],
    57 => ['name' => 'Pelhřimov'],
    58 => ['name' => 'Tachov'],
    59 => ['name' => 'Svitavy'],
    60 => ['name' => 'Žamberk'],
     61 => ['name' => 'Czech Republic Locality 1'],
     62 => ['name' => 'Czech Republic Locality 2'],
     63 => ['name' => 'Czech Republic Locality 3'],
     64 => ['name' => 'Czech Republic Locality 4'],
     65 => ['name' => 'Czech Republic Locality 5'],
     66 => ['name' => 'Czech Republic Locality 6'],
     67 => ['name' => 'Czech Republic Locality 7'],
     68 => ['name' => 'Czech Republic Locality 8'],
     69 => ['name' => 'Czech Republic Locality 9'],
     70 => ['name' => 'Czech Republic Locality 10'],
     71 => ['name' => 'Czech Republic Locality 11'],
     72 => ['name' => 'Czech Republic Locality 12'],
     73 => ['name' => 'Czech Republic Locality 13'],
     74 => ['name' => 'Czech Republic Locality 14'],
     75 => ['name' => 'Czech Republic Locality 15'],
     76 => ['name' => 'Czech Republic Locality 16'],
     77 => ['name' => 'Czech Republic Locality 17'],
     78 => ['name' => 'Czech Republic Locality 18'],
     79 => ['name' => 'Czech Republic Locality 19'],
     80 => ['name' => 'Czech Republic Locality 20'],
     81 => ['name' => 'Czech Republic Locality 21'],
     82 => ['name' => 'Czech Republic Locality 22'],
     83 => ['name' => 'Czech Republic Locality 23'],
     84 => ['name' => 'Czech Republic Locality 24'],
     85 => ['name' => 'Czech Republic Locality 25'],
     86 => ['name' => 'Czech Republic Locality 26'],
     87 => ['name' => 'Czech Republic Locality 27'],
     88 => ['name' => 'Czech Republic Locality 28'],
     89 => ['name' => 'Czech Republic Locality 29'],
     90 => ['name' => 'Czech Republic Locality 30'],
     91 => ['name' => 'Czech Republic Locality 31'],
     92 => ['name' => 'Czech Republic Locality 32'],
     93 => ['name' => 'Czech Republic Locality 33'],
     94 => ['name' => 'Czech Republic Locality 34'],
     95 => ['name' => 'Czech Republic Locality 35'],
     96 => ['name' => 'Czech Republic Locality 36'],
     97 => ['name' => 'Czech Republic Locality 37'],
     98 => ['name' => 'Czech Republic Locality 38'],
     99 => ['name' => 'Czech Republic Locality 39'],
    100 => ['name' => 'Czech Republic Locality 40'],
    101 => ['name' => 'Czech Republic Locality 41'],
    102 => ['name' => 'Czech Republic Locality 42'],
    103 => ['name' => 'Czech Republic Locality 43'],
    104 => ['name' => 'Czech Republic Locality 44'],
    105 => ['name' => 'Czech Republic Locality 45'],
    106 => ['name' => 'Czech Republic Locality 46'],
    107 => ['name' => 'Czech Republic Locality 47'],
    108 => ['name' => 'Czech Republic Locality 48'],
    109 => ['name' => 'Czech Republic Locality 49'],
    110 => ['name' => 'Czech Republic Locality 50'],
    111 => ['name' => 'Czech Republic Locality 51'],
    112 => ['name' => 'Czech Republic Locality 52'],
    113 => ['name' => 'Czech Republic Locality 53'],
    114 => ['name' => 'Czech Republic Locality 54'],
    115 => ['name' => 'Czech Republic Locality 55'],
    116 => ['name' => 'Czech Republic Locality 56'],
    117 => ['name' => 'Czech Republic Locality 57'],
    118 => ['name' => 'Czech Republic Locality 58'],
    119 => ['name' => 'Czech Republic Locality 59'],
    120 => ['name' => 'Czech Republic Locality 60'],
    121 => ['name' => 'Czech Republic Locality 61'],
    122 => ['name' => 'Czech Republic Locality 62'],
    123 => ['name' => 'Czech Republic Locality 63'],
    124 => ['name' => 'Czech Republic Locality 64'],
    125 => ['name' => 'Czech Republic Locality 65'],
    126 => ['name' => 'Czech Republic Locality 66'],
    127 => ['name' => 'Czech Republic Locality 67'],
    128 => ['name' => 'Czech Republic Locality 68'],
    129 => ['name' => 'Czech Republic Locality 69'],
    130 => ['name' => 'Czech Republic Locality 70'],
    131 => ['name' => 'Czech Republic Locality 71'],
    132 => ['name' => 'Czech Republic Locality 72'],
    133 => ['name' => 'Czech Republic Locality 73'],
    134 => ['name' => 'Czech Republic Locality 74'],
    135 => ['name' => 'Czech Republic Locality 75'],
    136 => ['name' => 'Czech Republic Locality 76'],
    137 => ['name' => 'Czech Republic Locality 77'],
    138 => ['name' => 'Czech Republic Locality 78'],
    139 => ['name' => 'Czech Republic Locality 79'],
    140 => ['name' => 'Czech Republic Locality 80'],
    141 => ['name' => 'Czech Republic Locality 81'],
    142 => ['name' => 'Czech Republic Locality 82'],
    143 => ['name' => 'Czech Republic Locality 83'],
    144 => ['name' => 'Czech Republic Locality 84'],
    145 => ['name' => 'Czech Republic Locality 85'],
    146 => ['name' => 'Czech Republic Locality 86'],
    147 => ['name' => 'Czech Republic Locality 87'],
    148 => ['name' => 'Czech Republic Locality 88'],
    149 => ['name' => 'Czech Republic Locality 89'],
    150 => ['name' => 'Czech Republic Locality 90'],
    151 => ['name' => 'Czech Republic Locality 91'],
    152 => ['name' => 'Czech Republic Locality 92'],
    153 => ['name' => 'Czech Republic Locality 93'],
    154 => ['name' => 'Czech Republic Locality 94'],
    155 => ['name' => 'Czech Republic Locality 95'],
    156 => ['name' => 'Czech Republic Locality 96'],
    157 => ['name' => 'Czech Republic Locality 97'],
    158 => ['name' => 'Czech Republic Locality 98'],
    159 => ['name' => 'Czech Republic Locality 99'],
    160 => ['name' => 'Czech Republic Locality 100'],
    161 => ['name' => 'Czech Republic Locality 101'],
    162 => ['name' => 'Czech Republic Locality 102'],
    163 => ['name' => 'Czech Republic Locality 103'],
    164 => ['name' => 'Czech Republic Locality 104'],
    165 => ['name' => 'Czech Republic Locality 105'],
    166 => ['name' => 'Czech Republic Locality 106'],
    167 => ['name' => 'Czech Republic Locality 107'],
    168 => ['name' => 'Czech Republic Locality 108'],
    169 => ['name' => 'Czech Republic Locality 109'],
    170 => ['name' => 'Czech Republic Locality 110'],
    171 => ['name' => 'Czech Republic Locality 111'],
    172 => ['name' => 'Czech Republic Locality 112'],
    173 => ['name' => 'Czech Republic Locality 113'],
    174 => ['name' => 'Czech Republic Locality 114'],
    175 => ['name' => 'Czech Republic Locality 115'],
    176 => ['name' => 'Czech Republic Locality 116'],
    177 => ['name' => 'Czech Republic Locality 117'],
    178 => ['name' => 'Czech Republic Locality 118'],
    179 => ['name' => 'Czech Republic Locality 119'],
    180 => ['name' => 'Czech Republic Locality 120'],
    181 => ['name' => 'Czech Republic Locality 121'],
    182 => ['name' => 'Czech Republic Locality 122'],
    183 => ['name' => 'Czech Republic Locality 123'],
    184 => ['name' => 'Czech Republic Locality 124'],
    185 => ['name' => 'Czech Republic Locality 125'],
    186 => ['name' => 'Czech Republic Locality 126'],
    187 => ['name' => 'Czech Republic Locality 127'],
    188 => ['name' => 'Czech Republic Locality 128'],
    189 => ['name' => 'Czech Republic Locality 129'],
    190 => ['name' => 'Czech Republic Locality 130'],
    191 => ['name' => 'Czech Republic Locality 131'],
    192 => ['name' => 'Czech Republic Locality 132'],
    193 => ['name' => 'Czech Republic Locality 133'],
    194 => ['name' => 'Czech Republic Locality 134'],
    195 => ['name' => 'Czech Republic Locality 135'],
    196 => ['name' => 'Czech Republic Locality 136'],
    197 => ['name' => 'Czech Republic Locality 137'],
    198 => ['name' => 'Czech Republic Locality 138'],
    199 => ['name' => 'Czech Republic Locality 139'],
    200 => ['name' => 'Czech Republic Locality 140'],
    201 => ['name' => 'Czech Republic Locality 1 (2)'],
    202 => ['name' => 'Czech Republic Locality 2 (2)'],
    203 => ['name' => 'Czech Republic Locality 3 (2)'],
    204 => ['name' => 'Czech Republic Locality 4 (2)'],
    205 => ['name' => 'Czech Republic Locality 5 (2)'],
    206 => ['name' => 'Czech Republic Locality 6 (2)'],
    207 => ['name' => 'Czech Republic Locality 7 (2)'],
    208 => ['name' => 'Czech Republic Locality 8 (2)'],
    209 => ['name' => 'Czech Republic Locality 9 (2)'],
    210 => ['name' => 'Czech Republic Locality 10 (2)'],
    211 => ['name' => 'Czech Republic Locality 11 (2)'],
    212 => ['name' => 'Czech Republic Locality 12 (2)'],
    213 => ['name' => 'Czech Republic Locality 13 (2)'],
    214 => ['name' => 'Czech Republic Locality 14 (2)'],
    215 => ['name' => 'Czech Republic Locality 15 (2)'],
    216 => ['name' => 'Czech Republic Locality 16 (2)'],
    217 => ['name' => 'Czech Republic Locality 17 (2)'],
    218 => ['name' => 'Czech Republic Locality 18 (2)'],
    219 => ['name' => 'Czech Republic Locality 19 (2)'],
    220 => ['name' => 'Czech Republic Locality 20 (2)'],
    221 => ['name' => 'Czech Republic Locality 21 (2)'],
    222 => ['name' => 'Czech Republic Locality 22 (2)'],
    223 => ['name' => 'Czech Republic Locality 23 (2)'],
    224 => ['name' => 'Czech Republic Locality 24 (2)'],
    225 => ['name' => 'Czech Republic Locality 25 (2)'],
    226 => ['name' => 'Czech Republic Locality 26 (2)'],
    227 => ['name' => 'Czech Republic Locality 27 (2)'],
    228 => ['name' => 'Czech Republic Locality 28 (2)'],
    229 => ['name' => 'Czech Republic Locality 29 (2)'],
    230 => ['name' => 'Czech Republic Locality 30 (2)'],
    231 => ['name' => 'Czech Republic Locality 31 (2)'],
    232 => ['name' => 'Czech Republic Locality 32 (2)'],
    233 => ['name' => 'Czech Republic Locality 33 (2)'],
    234 => ['name' => 'Czech Republic Locality 34 (2)'],
    235 => ['name' => 'Czech Republic Locality 35 (2)'],
    236 => ['name' => 'Czech Republic Locality 36 (2)'],
    237 => ['name' => 'Czech Republic Locality 37 (2)'],
    238 => ['name' => 'Czech Republic Locality 38 (2)'],
    239 => ['name' => 'Czech Republic Locality 39 (2)'],
    240 => ['name' => 'Czech Republic Locality 40 (2)'],
    241 => ['name' => 'Czech Republic Locality 41 (2)'],
    242 => ['name' => 'Czech Republic Locality 42 (2)'],
    243 => ['name' => 'Czech Republic Locality 43 (2)'],
    244 => ['name' => 'Czech Republic Locality 44 (2)'],
    245 => ['name' => 'Czech Republic Locality 45 (2)'],
    246 => ['name' => 'Czech Republic Locality 46 (2)'],
    247 => ['name' => 'Czech Republic Locality 47 (2)'],
    248 => ['name' => 'Czech Republic Locality 48 (2)'],
    249 => ['name' => 'Czech Republic Locality 49 (2)'],
    250 => ['name' => 'Czech Republic Locality 50 (2)'],
    251 => ['name' => 'Czech Republic Locality 51 (2)'],
    252 => ['name' => 'Czech Republic Locality 52 (2)'],
    253 => ['name' => 'Czech Republic Locality 53 (2)'],
    254 => ['name' => 'Czech Republic Locality 54 (2)'],
    255 => ['name' => 'Czech Republic Locality 55 (2)'],
    256 => ['name' => 'Czech Republic Locality 56 (2)'],
    257 => ['name' => 'Czech Republic Locality 57 (2)'],
    258 => ['name' => 'Czech Republic Locality 58 (2)'],
    259 => ['name' => 'Czech Republic Locality 59 (2)'],
    260 => ['name' => 'Czech Republic Locality 60 (2)']
];