<?php

return [
    1  => ['name' => 'Berlin'],
    2  => ['name' => 'Hamburg'],
    3  => ['name' => 'München'],
    4  => ['name' => 'Köln'],
    5  => ['name' => 'Frankfurt am Main'],
    6  => ['name' => 'Stuttgart'],
      7 => ['name' => 'Aachen'],
      8 => ['name' => 'Augsburg'],
      9 => ['name' => 'Bielefeld'],
     10 => ['name' => 'Bochum'],
     11 => ['name' => 'Bonn'],
     12 => ['name' => 'Bottrop'],
     13 => ['name' => 'Braunschweig'],
     14 => ['name' => 'Bremen'],
     15 => ['name' => 'Bremerhaven'],
     16 => ['name' => 'Chemnitz'],
     17 => ['name' => 'Cottbus'],
     18 => ['name' => 'Darmstadt'],
     19 => ['name' => 'Dortmund'],
     20 => ['name' => 'Dresden'],
     21 => ['name' => 'Duisburg'],
     22 => ['name' => 'Erfurt'],
     23 => ['name' => 'Erlangen'],
     24 => ['name' => 'Essen'],
     25 => ['name' => 'Freiburg'],
     26 => ['name' => 'Gelsenkirchen'],
     27 => ['name' => 'Göttingen'],
     28 => ['name' => 'Hagen'],
     29 => ['name' => 'Halle'],
     30 => ['name' => 'Hamm'],
     31 => ['name' => 'Hannover'],
     32 => ['name' => 'Heidelberg'],
     33 => ['name' => 'Heilbronn'],
     34 => ['name' => 'Herne'],
     35 => ['name' => 'Hildesheim'],
     36 => ['name' => 'Ingolstadt'],
     37 => ['name' => 'Jena'],
     38 => ['name' => 'Kassel'],
     39 => ['name' => 'Kiel'],
     40 => ['name' => 'Koblenz'],
     41 => ['name' => 'Krefeld'],
     42 => ['name' => 'Leverkusen'],
     43 => ['name' => 'Lübeck'],
     44 => ['name' => 'Magdeburg'],
     45 => ['name' => 'Mainz'],
     46 => ['name' => 'Mannheim'],
     47 => ['name' => 'Mönchengladbach'],
     48 => ['name' => 'Mülheim'],
     49 => ['name' => 'Münster'],
     50 => ['name' => 'Neuss'],
     51 => ['name' => 'Nuremberg'],
     52 => ['name' => 'Oberhausen'],
     53 => ['name' => 'Offenbach'],
     54 => ['name' => 'Oldenburg'],
     55 => ['name' => 'Osnabrück'],
     56 => ['name' => 'Paderborn'],
     57 => ['name' => 'Pforzheim'],
     58 => ['name' => 'Potsdam'],
     59 => ['name' => 'Recklinghausen'],
     60 => ['name' => 'Regensburg'],
     61 => ['name' => 'Remscheid'],
     62 => ['name' => 'Reutlingen'],
     63 => ['name' => 'Rostock'],
     64 => ['name' => 'Saarbrücken'],
     65 => ['name' => 'Salzgitter'],
     66 => ['name' => 'Siegen'],
     67 => ['name' => 'Solingen'],
     68 => ['name' => 'Trier'],
     69 => ['name' => 'Ulm'],
     70 => ['name' => 'Wolfsburg'],
     71 => ['name' => 'Wuppertal'],
     72 => ['name' => 'Würzburg'],
     73 => ['name' => 'Bamberg'],
     74 => ['name' => 'Bayreuth'],
     75 => ['name' => 'Landshut'],
     76 => ['name' => 'Passau'],
     77 => ['name' => 'Straubing'],
     78 => ['name' => 'Baden-Baden'],
     79 => ['name' => 'Fulda'],
     80 => ['name' => 'Gießen'],
     81 => ['name' => 'Marburg'],
     82 => ['name' => 'Wetzlar'],
     83 => ['name' => 'Lüneburg'],
     84 => ['name' => 'Celle'],
     85 => ['name' => 'Goslar'],
     86 => ['name' => 'Wolfenbüttel'],
     87 => ['name' => 'Heide'],
     88 => ['name' => 'Flensburg'],
     89 => ['name' => 'Lübeck'],
     90 => ['name' => 'Rendsburg'],
     91 => ['name' => 'Itzehoe'],
     92 => ['name' => 'Detmold'],
     93 => ['name' => 'Lippstadt'],
     94 => ['name' => 'Minden'],
     95 => ['name' => 'Paderborn'],
     96 => ['name' => 'Soest'],
     97 => ['name' => 'Wesel'],
     98 => ['name' => 'Kleve'],
     99 => ['name' => 'Emden'],
    100 => ['name' => 'Wilhelmshaven'],
    101 => ['name' => 'Delmenhorst'],
    102 => ['name' => 'Cuxhaven'],
    103 => ['name' => 'Stade'],
    104 => ['name' => 'Lüneburg'],
    105 => ['name' => 'Stendal'],
    106 => ['name' => 'Wittenberg'],
    107 => ['name' => 'Bautzen'],
    108 => ['name' => 'Görlitz'],
    109 => ['name' => 'Zwickau'],
    110 => ['name' => 'Plauen'],
    111 => ['name' => 'Weimar'],
    112 => ['name' => 'Suhl'],
    113 => ['name' => 'Gera'],
    114 => ['name' => 'Jena'],
    115 => ['name' => 'Eisenach'],
    116 => ['name' => 'Schwerin'],
    117 => ['name' => 'Rostock'],
    118 => ['name' => 'Stralsund'],
    119 => ['name' => 'Greifswald'],
    120 => ['name' => 'Neubrandenburg'],
    121 => ['name' => 'Wismar'],
    122 => ['name' => 'Ludwigshafen'],
    123 => ['name' => 'Kaiserslautern'],
    124 => ['name' => 'Neustadt'],
    125 => ['name' => 'Speyer'],
    126 => ['name' => 'Landau'],
    127 => ['name' => 'Pirmasens'],
    128 => ['name' => 'Trier'],
    129 => ['name' => 'Konstanz'],
    130 => ['name' => 'Friedrichshafen'],
    131 => ['name' => 'Ravensburg'],
    132 => ['name' => 'Reutlingen'],
    133 => ['name' => 'Sindelfingen'],
    134 => ['name' => 'Reutlingen'],
    135 => ['name' => 'Aalen'],
    136 => ['name' => 'Schwäbisch Gmünd'],
    137 => ['name' => 'Ulm'],
    138 => ['name' => 'Heidenheim'],
    139 => ['name' => 'Baden-Baden'],
    140 => ['name' => 'Pforzheim'],
    141 => ['name' => 'Karlsruhe'],
    142 => ['name' => 'Heidelberg'],
    143 => ['name' => 'Mannheim'],
    144 => ['name' => 'Heilbronn'],
    145 => ['name' => 'Schweinfurt'],
    146 => ['name' => 'Bamberg'],
    147 => ['name' => 'Coburg'],
    148 => ['name' => 'Hof'],
    149 => ['name' => 'Bayreuth'],
    150 => ['name' => 'Bamberg'],
    151 => ['name' => 'Ansbach'],
    152 => ['name' => 'Fürth'],
    153 => ['name' => 'Erlangen'],
    154 => ['name' => 'Bamberg'],
    155 => ['name' => 'Aschaffenburg'],
    156 => ['name' => 'Würzburg'],
    157 => ['name' => 'Kitzingen'],
    158 => ['name' => 'Schweinfurt'],
    159 => ['name' => 'Bad Kissingen'],
    160 => ['name' => 'Coburg'],
    161 => ['name' => 'Düsseldorf'],
    162 => ['name' => 'Leipzig'],
    163 => ['name' => 'Nürnberg'],
    164 => ['name' => 'Wiesbaden'],
    165 => ['name' => 'Freiburg im Breisgau'],
    166 => ['name' => 'Germany Locality 1'],
    167 => ['name' => 'Germany Locality 2'],
    168 => ['name' => 'Germany Locality 3'],
    169 => ['name' => 'Germany Locality 4'],
    170 => ['name' => 'Germany Locality 5'],
    171 => ['name' => 'Germany Locality 6'],
    172 => ['name' => 'Germany Locality 7'],
    173 => ['name' => 'Germany Locality 8'],
    174 => ['name' => 'Germany Locality 9'],
    175 => ['name' => 'Germany Locality 10'],
    176 => ['name' => 'Germany Locality 11'],
    177 => ['name' => 'Germany Locality 12'],
    178 => ['name' => 'Germany Locality 13'],
    179 => ['name' => 'Germany Locality 14'],
    180 => ['name' => 'Germany Locality 15'],
    181 => ['name' => 'Germany Locality 16'],
    182 => ['name' => 'Germany Locality 17'],
    183 => ['name' => 'Germany Locality 18'],
    184 => ['name' => 'Germany Locality 19'],
    185 => ['name' => 'Germany Locality 20'],
    186 => ['name' => 'Germany Locality 21'],
    187 => ['name' => 'Germany Locality 22'],
    188 => ['name' => 'Germany Locality 23'],
    189 => ['name' => 'Germany Locality 24'],
    190 => ['name' => 'Germany Locality 25'],
    191 => ['name' => 'Germany Locality 26'],
    192 => ['name' => 'Germany Locality 27'],
    193 => ['name' => 'Germany Locality 28'],
    194 => ['name' => 'Germany Locality 29'],
    195 => ['name' => 'Germany Locality 30'],
    196 => ['name' => 'Germany Locality 31'],
    197 => ['name' => 'Germany Locality 32'],
    198 => ['name' => 'Germany Locality 33'],
    199 => ['name' => 'Germany Locality 34'],
    200 => ['name' => 'Germany Locality 35'],
    201 => ['name' => 'Germany Locality 36'],
    202 => ['name' => 'Germany Locality 37'],
    203 => ['name' => 'Germany Locality 38'],
    204 => ['name' => 'Germany Locality 39'],
    205 => ['name' => 'Germany Locality 40'],
    206 => ['name' => 'Germany Locality 41']
];