<?php

return [
    1  => ['name' => 'Helsinki'],
    2  => ['name' => 'Espoo'],
    3  => ['name' => 'Tampere'],
    4  => ['name' => 'Vantaa'],
    5  => ['name' => 'Oulu'],
    6  => ['name' => 'Turku'],
    7  => ['name' => 'Jyväskylä'],
    8  => ['name' => 'Lahti'],
    9  => ['name' => 'Kuopio'],
    10 => ['name' => 'Pori'],
    11 => ['name' => 'Lappeenranta'],
    12 => ['name' => 'Vaasa'],
    13 => ['name' => 'Joensuu'],
    14 => ['name' => 'Hämeenlinna'],
    15 => ['name' => 'Rovaniemi'],
    16 => ['name' => 'Seinäjoki'],
    17 => ['name' => 'Mikkeli'],
    18 => ['name' => 'Kokkola'],
    19 => ['name' => 'Kajaani'],
    20 => ['name' => 'Kouvola'],
    21 => ['name' => 'Kotka'],
    22 => ['name' => 'Salo'],
    23 => ['name' => 'Porvoo'],
    24 => ['name' => 'Lohja'],
    25 => ['name' => 'Hyvinkää'],
    26 => ['name' => 'Nurmijärvi'],
    27 => ['name' => 'Järvenpää'],
    28 => ['name' => 'Rauma'],
    29 => ['name' => 'Kirkkonummi'],
    30 => ['name' => 'Tuusula'],
    31 => ['name' => 'Kerava'],
    32 => ['name' => 'Imatra'],
    33 => ['name' => 'Riihimäki'],
    34 => ['name' => 'Ylöjärvi'],
    35 => ['name' => 'Kemi'],
    36 => ['name' => 'Iisalmi'],
    37 => ['name' => 'Jakobstad (Pietarsaari)'],
    38 => ['name' => 'Savonlinna'],
    39 => ['name' => 'Karhula'],
    40 => ['name' => 'Raahe'],
    41 => ['name' => 'Valkeakoski'],
    42 => ['name' => 'Hamina'],
    43 => ['name' => 'Vihti'],
    44 => ['name' => 'Kaarina'],
    45 => ['name' => 'Tornio'],
    46 => ['name' => 'Heinola'],
    47 => ['name' => 'Äänekoski'],
    48 => ['name' => 'Kuusamo'],
    49 => ['name' => 'Kangasala'],
    50 => ['name' => 'Naantali'],
    51 => ['name' => 'Raisio'],
    52 => ['name' => 'Hollola'],
    53 => ['name' => 'Varkaus'],
    54 => ['name' => 'Forssa'],
    55 => ['name' => 'Orimattila'],
    56 => ['name' => 'Raasepori (Raseborg)'],
    57 => ['name' => 'Kauhava'],
    58 => ['name' => 'Nokia'],
    59 => ['name' => 'Lempäälä'],
    60 => ['name' => 'Jämsä'],
    61 => ['name' => 'Korsholm (Mustasaari)'],
    62 => ['name' => 'Pietarsaari'],
    63 => ['name' => 'Sastamala'],
    64 => ['name' => 'Sipoo'],
    65 => ['name' => 'Kuhmo'],
    66 => ['name' => 'Närpiö (Närpes)'],
    67 => ['name' => 'Somero'],
    68 => ['name' => 'Pieksämäki'],
    69 => ['name' => 'Alajärvi'],
    70 => ['name' => 'Pudasjärvi'],
    71 => ['name' => 'Lieksa'],
    72 => ['name' => 'Tammisaari (Ekenäs)'],
    73 => ['name' => 'Mäntsälä'],
    74 => ['name' => 'Kankaanpää'],
    75 => ['name' => 'Outokumpu'],
    76 => ['name' => 'Kemijärvi'],
    77 => ['name' => 'Kristiinankaupunki (Kristinestad)'],
    78 => ['name' => 'Loimaa'],
    79 => ['name' => 'Kemiönsaari (Kimitoön)'],
    80 => ['name' => 'Kalajoki'],
    81 => ['name' => 'Jämsänkoski'],
    82 => ['name' => 'Lapua'],
    83 => ['name' => 'Eura'],
    84 => ['name' => 'Tornio-Haparanda'],
    85 => ['name' => 'Mänttä-Vilppula'],
    86 => ['name' => 'Huittinen'],
    87 => ['name' => 'Orivesi'],
    88 => ['name' => 'Saarijärvi'],
    89 => ['name' => 'Nivala'],
    90 => ['name' => 'Ylivieska'],
    91 => ['name' => 'Kuusankoski'],
    92 => ['name' => 'Karkkila'],
    93 => ['name' => 'Tornio'],
    94 => ['name' => 'Paimio'],
    95 => ['name' => 'Virrat'],
    96 => ['name' => 'Savitaipale'],
    97 => ['name' => 'Outokumpu'],
    98 => ['name' => 'Joensuu-Rantakylä'],
    99 => ['name' => 'Rovaniemi (Lapland)'],
    100 => ['name' => 'Enontekiö'],
];
