<?php

return [
    1  => ['name' => 'Athens'],
    2  => ['name' => 'Thessaloniki'],
    3  => ['name' => 'Patras'],
    4  => ['name' => 'Heraklion'],
    5  => ['name' => 'Larissa'],
    6  => ['name' => 'Volos'],
    7  => ['name' => 'Ioannina'],
    8  => ['name' => 'Chania'],
    9  => ['name' => 'Rhodes'],
    10 => ['name' => 'Serres'],
    11 => ['name' => 'Kavala'],
    12 => ['name' => 'Alexandroupoli'],
    13 => ['name' => 'Katerini'],
    14 => ['name' => 'Agrinio'],
    15 => ['name' => 'Kalamata'],
    16 => ['name' => 'Trikala'],
    17 => ['name' => 'Chalcis'],
    18 => ['name' => 'Veria'],
    19 => ['name' => 'Kozani'],
    20 => ['name' => 'Karditsa'],
    21 => ['name' => 'Ptolemaida'],
    22 => ['name' => 'Drama'],
    23 => ['name' => 'Komotini'],
    24 => ['name' => 'Mytilene'],
    25 => ['name' => 'Xanthi'],
    26 => ['name' => 'Katerini'],
    27 => ['name' => 'Lamia'],
    28 => ['name' => 'Rethymno'],
    29 => ['name' => 'Kilkis'],
    30 => ['name' => 'Tripoli'],
    31 => ['name' => 'Corinth'],
    32 => ['name' => 'Chios'],
    33 => ['name' => 'Sparta'],
    34 => ['name' => 'Giannitsa'],
    35 => ['name' => 'Orestiada'],
    36 => ['name' => 'Florina'],
    37 => ['name' => 'Naousa'],
    38 => ['name' => 'Edessa'],
    39 => ['name' => 'Preveza'],
    40 => ['name' => 'Arta'],
    41 => ['name' => 'Lefkada'],
    42 => ['name' => 'Kos'],
    43 => ['name' => 'Samos'],
    44 => ['name' => 'Kalymnos'],
    45 => ['name' => 'Naxos'],
    46 => ['name' => 'Paros'],
    47 => ['name' => 'Syros'],
    48 => ['name' => 'Santorini (Thira)'],
    49 => ['name' => 'Mykonos'],
    50 => ['name' => 'Corfu'],
    51 => ['name' => 'Zakynthos'],
    52 => ['name' => 'Kefalonia'],
    53 => ['name' => 'Igoumenitsa'],
    54 => ['name' => 'Argos'],
    55 => ['name' => 'Pyrgos'],
    56 => ['name' => 'Aigio'],
    57 => ['name' => 'Thebes'],
    58 => ['name' => 'Livadeia'],
    59 => ['name' => 'Mesolongi'],
    60 => ['name' => 'Karpenisi'],
    61 => ['name' => 'Amfissa'],
    62 => ['name' => 'Kyparissia'],
    63 => ['name' => 'Kalambaka'],
    64 => ['name' => 'Grevena'],
    65 => ['name' => 'Megalopoli'],
    66 => ['name' => 'Parga'],
    67 => ['name' => 'Thasos'],
    68 => ['name' => 'Kassandra'],
    69 => ['name' => 'Polygyros'],
    70 => ['name' => 'Nea Moudania'],
    71 => ['name' => 'Amaliada'],
    72 => ['name' => 'Ierapetra'],
    73 => ['name' => 'Agios Nikolaos'],
    74 => ['name' => 'Sitia'],
    75 => ['name' => 'Kastoria'],
    76 => ['name' => 'Didymoteicho'],
    77 => ['name' => 'Ermoupoli'],
    78 => ['name' => 'Pylos'],
    79 => ['name' => 'Kalavryta'],
    80 => ['name' => 'Loutraki'],
    81 => ['name' => 'Nea Ionia'],
    82 => ['name' => 'Marousi'],
    83 => ['name' => 'Piraeus'],
    84 => ['name' => 'Peristeri'],
    85 => ['name' => 'Kallithea'],
    86 => ['name' => 'Nea Smyrni'],
    87 => ['name' => 'Petroupoli'],
    88 => ['name' => 'Ilion'],
    89 => ['name' => 'Glyfada'],
    90 => ['name' => 'Chalandri'],
    91 => ['name' => 'Voula'],
    92 => ['name' => 'Perama'],
    93 => ['name' => 'Acharnae'],
    94 => ['name' => 'Agia Paraskevi'],
    95 => ['name' => 'Pallini'],
    96 => ['name' => 'Koropi'],
    97 => ['name' => 'Elefsina'],
    98 => ['name' => 'Menidi'],
    99 => ['name' => 'Salamina'],
    100 => ['name' => 'Alimos'],
];
