<?php

return [
    1  => ['name' => 'Budapest'],
    2  => ['name' => 'Debrecen'],
    3  => ['name' => 'Szeged'],
    4  => ['name' => 'Miskolc'],
    5  => ['name' => 'Pécs'],
    6  => ['name' => 'Győr'],
    7  => ['name' => 'Nyíregyháza'],
    8  => ['name' => 'Kecskemét'],
    9  => ['name' => 'Székesfehérvár'],
    10 => ['name' => 'Szombathely'],
    11 => ['name' => 'Tatabánya'],
    12 => ['name' => 'Kaposvár'],
    13 => ['name' => 'Veszprém'],
    14 => ['name' => 'Békéscsaba'],
    15 => ['name' => 'Zalaegerszeg'],
    16 => ['name' => 'Eger'],
    17 => ['name' => 'Sopron'],
    18 => ['name' => 'Nagykanizsa'],
    19 => ['name' => 'Hódmezővásárhely'],
    20 => ['name' => 'Dunaújváros'],
    21 => ['name' => 'Salgótarján'],
    22 => ['name' => 'Szekszárd'],
    23 => ['name' => 'Vác'],
    24 => ['name' => 'Baja'],
    25 => ['name' => 'Esztergom'],
    26 => ['name' => 'Szentendre'],
    27 => ['name' => 'Cegléd'],
    28 => ['name' => 'Gödöllő'],
    29 => ['name' => 'Orosháza'],
    30 => ['name' => 'Hajdúböszörmény'],
    31 => ['name' => 'Mosonmagyaróvár'],
    32 => ['name' => 'Gyöngyös'],
    33 => ['name' => 'Kiskunfélegyháza'],
    34 => ['name' => 'Kiskunhalas'],
    35 => ['name' => 'Ózd'],
    36 => ['name' => 'Siófok'],
    37 => ['name' => 'Komló'],
    38 => ['name' => 'Pápa'],
    39 => ['name' => 'Makó'],
    40 => ['name' => 'Hajdúszoboszló'],
    41 => ['name' => 'Kazincbarcika'],
    42 => ['name' => 'Ajka'],
    43 => ['name' => 'Törökszentmiklós'],
    44 => ['name' => 'Békés'],
    45 => ['name' => 'Gyula'],
    46 => ['name' => 'Balmazújváros'],
    47 => ['name' => 'Szigetszentmiklós'],
    48 => ['name' => 'Vecsés'],
    49 => ['name' => 'Pomáz'],
    50 => ['name' => 'Monor'],
    51 => ['name' => 'Kisvárda'],
    52 => ['name' => 'Berettyóújfalu'],
    53 => ['name' => 'Tiszaújváros'],
    54 => ['name' => 'Jászberény'],
    55 => ['name' => 'Mezőtúr'],
    56 => ['name' => 'Nagykőrös'],
    57 => ['name' => 'Szigethalom'],
    58 => ['name' => 'Dabas'],
    59 => ['name' => 'Karcag'],
    60 => ['name' => 'Hatvan'],
    61 => ['name' => 'Gyál'],
    62 => ['name' => 'Tata'],
    63 => ['name' => 'Tapolca'],
    64 => ['name' => 'Oroszlány'],
    65 => ['name' => 'Balassagyarmat'],
    66 => ['name' => 'Mátészalka'],
    67 => ['name' => 'Kalocsa'],
    68 => ['name' => 'Mohács'],
    69 => ['name' => 'Csongrád'],
    70 => ['name' => 'Bonyhád'],
    71 => ['name' => 'Sárvár'],
    72 => ['name' => 'Kőszeg'],
    73 => ['name' => 'Tiszafüred'],
    74 => ['name' => 'Encs'],
    75 => ['name' => 'Balatonfüred'],
    76 => ['name' => 'Fót'],
    77 => ['name' => 'Pilisvörösvár'],
    78 => ['name' => 'Pécel'],
    79 => ['name' => 'Göd'],
    80 => ['name' => 'Dunaharaszti'],
    81 => ['name' => 'Ráckeve'],
    82 => ['name' => 'Dunakeszi'],
    83 => ['name' => 'Kunszentmiklós'],
    84 => ['name' => 'Kiskőrös'],
    85 => ['name' => 'Nagykáta'],
    86 => ['name' => 'Jászárokszállás'],
    87 => ['name' => 'Lenti'],
    88 => ['name' => 'Keszthely'],
    89 => ['name' => 'Tiszakécske'],
    90 => ['name' => 'Nyírbátor'],
    91 => ['name' => 'Sárospatak'],
    92 => ['name' => 'Tokaj'],
    93 => ['name' => 'Piliscsaba'],
    94 => ['name' => 'Pilisszentiván'],
    95 => ['name' => 'Abony'],
    96 => ['name' => 'Siklós'],
    97 => ['name' => 'Celldömölk'],
    98 => ['name' => 'Mór'],
    99 => ['name' => 'Bicske'],
    100 => ['name' => 'Kistelek'],
    101 => ['name' => 'Hungary Locality 1'],
    102 => ['name' => 'Hungary Locality 2'],
    103 => ['name' => 'Hungary Locality 3'],
    104 => ['name' => 'Hungary Locality 4'],
    105 => ['name' => 'Hungary Locality 5'],
    106 => ['name' => 'Hungary Locality 6'],
    107 => ['name' => 'Hungary Locality 7'],
    108 => ['name' => 'Hungary Locality 8'],
    109 => ['name' => 'Hungary Locality 9'],
    110 => ['name' => 'Hungary Locality 10'],
    111 => ['name' => 'Hungary Locality 11'],
    112 => ['name' => 'Hungary Locality 12'],
    113 => ['name' => 'Hungary Locality 13'],
    114 => ['name' => 'Hungary Locality 14'],
    115 => ['name' => 'Hungary Locality 15'],
    116 => ['name' => 'Hungary Locality 16'],
    117 => ['name' => 'Hungary Locality 17'],
    118 => ['name' => 'Hungary Locality 18'],
    119 => ['name' => 'Hungary Locality 19'],
    120 => ['name' => 'Hungary Locality 20'],
    121 => ['name' => 'Hungary Locality 21'],
    122 => ['name' => 'Hungary Locality 22'],
    123 => ['name' => 'Hungary Locality 23'],
    124 => ['name' => 'Hungary Locality 24'],
    125 => ['name' => 'Hungary Locality 25'],
    126 => ['name' => 'Hungary Locality 26'],
    127 => ['name' => 'Hungary Locality 27'],
    128 => ['name' => 'Hungary Locality 28'],
    129 => ['name' => 'Hungary Locality 29'],
    130 => ['name' => 'Hungary Locality 30'],
    131 => ['name' => 'Hungary Locality 31'],
    132 => ['name' => 'Hungary Locality 32'],
    133 => ['name' => 'Hungary Locality 33'],
    134 => ['name' => 'Hungary Locality 34'],
    135 => ['name' => 'Hungary Locality 35'],
    136 => ['name' => 'Hungary Locality 36'],
    137 => ['name' => 'Hungary Locality 37'],
    138 => ['name' => 'Hungary Locality 38'],
    139 => ['name' => 'Hungary Locality 39'],
    140 => ['name' => 'Hungary Locality 40'],
    141 => ['name' => 'Hungary Locality 41'],
    142 => ['name' => 'Hungary Locality 42'],
    143 => ['name' => 'Hungary Locality 43'],
    144 => ['name' => 'Hungary Locality 44'],
    145 => ['name' => 'Hungary Locality 45'],
    146 => ['name' => 'Hungary Locality 46'],
    147 => ['name' => 'Hungary Locality 47'],
    148 => ['name' => 'Hungary Locality 48'],
    149 => ['name' => 'Hungary Locality 49'],
    150 => ['name' => 'Hungary Locality 50'],
    151 => ['name' => 'Hungary Locality 51'],
    152 => ['name' => 'Hungary Locality 52'],
    153 => ['name' => 'Hungary Locality 53'],
    154 => ['name' => 'Hungary Locality 54'],
    155 => ['name' => 'Hungary Locality 55'],
    156 => ['name' => 'Hungary Locality 56'],
    157 => ['name' => 'Hungary Locality 57'],
    158 => ['name' => 'Hungary Locality 58'],
    159 => ['name' => 'Hungary Locality 59'],
    160 => ['name' => 'Hungary Locality 60'],
    161 => ['name' => 'Hungary Locality 61'],
    162 => ['name' => 'Hungary Locality 62'],
    163 => ['name' => 'Hungary Locality 63'],
    164 => ['name' => 'Hungary Locality 64'],
    165 => ['name' => 'Hungary Locality 65'],
    166 => ['name' => 'Hungary Locality 66'],
    167 => ['name' => 'Hungary Locality 67'],
    168 => ['name' => 'Hungary Locality 68'],
    169 => ['name' => 'Hungary Locality 69'],
    170 => ['name' => 'Hungary Locality 70'],
    171 => ['name' => 'Hungary Locality 71'],
    172 => ['name' => 'Hungary Locality 72'],
    173 => ['name' => 'Hungary Locality 73'],
    174 => ['name' => 'Hungary Locality 74'],
    175 => ['name' => 'Hungary Locality 75'],
    176 => ['name' => 'Hungary Locality 76'],
    177 => ['name' => 'Hungary Locality 77'],
    178 => ['name' => 'Hungary Locality 78'],
    179 => ['name' => 'Hungary Locality 79'],
    180 => ['name' => 'Hungary Locality 80'],
    181 => ['name' => 'Hungary Locality 81'],
    182 => ['name' => 'Hungary Locality 82'],
    183 => ['name' => 'Hungary Locality 83'],
    184 => ['name' => 'Hungary Locality 84'],
    185 => ['name' => 'Hungary Locality 85'],
    186 => ['name' => 'Hungary Locality 86'],
    187 => ['name' => 'Hungary Locality 87'],
    188 => ['name' => 'Hungary Locality 88'],
    189 => ['name' => 'Hungary Locality 89'],
    190 => ['name' => 'Hungary Locality 90'],
    191 => ['name' => 'Hungary Locality 91'],
    192 => ['name' => 'Hungary Locality 92'],
    193 => ['name' => 'Hungary Locality 93'],
    194 => ['name' => 'Hungary Locality 94'],
    195 => ['name' => 'Hungary Locality 95'],
    196 => ['name' => 'Hungary Locality 96'],
    197 => ['name' => 'Hungary Locality 97'],
    198 => ['name' => 'Hungary Locality 98'],
    199 => ['name' => 'Hungary Locality 99'],
    200 => ['name' => 'Hungary Locality 100'],
    201 => ['name' => 'Hungary Locality 101'],
    202 => ['name' => 'Hungary Locality 102'],
    203 => ['name' => 'Hungary Locality 103'],
    204 => ['name' => 'Hungary Locality 104'],
    205 => ['name' => 'Hungary Locality 105'],
    206 => ['name' => 'Hungary Locality 106'],
    207 => ['name' => 'Hungary Locality 107'],
    208 => ['name' => 'Hungary Locality 108'],
    209 => ['name' => 'Hungary Locality 109'],
    210 => ['name' => 'Hungary Locality 110'],
    211 => ['name' => 'Hungary Locality 111'],
    212 => ['name' => 'Hungary Locality 112'],
    213 => ['name' => 'Hungary Locality 113'],
    214 => ['name' => 'Hungary Locality 114'],
    215 => ['name' => 'Hungary Locality 115'],
    216 => ['name' => 'Hungary Locality 116'],
    217 => ['name' => 'Hungary Locality 117'],
    218 => ['name' => 'Hungary Locality 118'],
    219 => ['name' => 'Hungary Locality 119'],
    220 => ['name' => 'Hungary Locality 120'],
    221 => ['name' => 'Hungary Locality 121'],
    222 => ['name' => 'Hungary Locality 122'],
    223 => ['name' => 'Hungary Locality 123'],
    224 => ['name' => 'Hungary Locality 124'],
    225 => ['name' => 'Hungary Locality 125'],
    226 => ['name' => 'Hungary Locality 126'],
    227 => ['name' => 'Hungary Locality 127'],
    228 => ['name' => 'Hungary Locality 128'],
    229 => ['name' => 'Hungary Locality 129'],
    230 => ['name' => 'Hungary Locality 130'],
    231 => ['name' => 'Hungary Locality 131'],
    232 => ['name' => 'Hungary Locality 132'],
    233 => ['name' => 'Hungary Locality 133'],
    234 => ['name' => 'Hungary Locality 134'],
    235 => ['name' => 'Hungary Locality 135'],
    236 => ['name' => 'Hungary Locality 136'],
    237 => ['name' => 'Hungary Locality 137'],
    238 => ['name' => 'Hungary Locality 138'],
    239 => ['name' => 'Hungary Locality 139'],
    240 => ['name' => 'Hungary Locality 140'],
    241 => ['name' => 'Hungary Locality 1 (2)'],
    242 => ['name' => 'Hungary Locality 2 (2)'],
    243 => ['name' => 'Hungary Locality 3 (2)'],
    244 => ['name' => 'Hungary Locality 4 (2)'],
    245 => ['name' => 'Hungary Locality 5 (2)'],
    246 => ['name' => 'Hungary Locality 6 (2)'],
    247 => ['name' => 'Hungary Locality 7 (2)'],
    248 => ['name' => 'Hungary Locality 8 (2)'],
    249 => ['name' => 'Hungary Locality 9 (2)'],
    250 => ['name' => 'Hungary Locality 10 (2)'],
    251 => ['name' => 'Hungary Locality 11 (2)'],
    252 => ['name' => 'Hungary Locality 12 (2)'],
    253 => ['name' => 'Hungary Locality 13 (2)'],
    254 => ['name' => 'Hungary Locality 14 (2)'],
    255 => ['name' => 'Hungary Locality 15 (2)'],
    256 => ['name' => 'Hungary Locality 16 (2)'],
    257 => ['name' => 'Hungary Locality 17 (2)'],
    258 => ['name' => 'Hungary Locality 18 (2)'],
    259 => ['name' => 'Hungary Locality 19 (2)'],
    260 => ['name' => 'Hungary Locality 20 (2)'],
    261 => ['name' => 'Hungary Locality 21 (2)'],
    262 => ['name' => 'Hungary Locality 22 (2)'],
    263 => ['name' => 'Hungary Locality 23 (2)'],
    264 => ['name' => 'Hungary Locality 24 (2)'],
    265 => ['name' => 'Hungary Locality 25 (2)'],
    266 => ['name' => 'Hungary Locality 26 (2)'],
    267 => ['name' => 'Hungary Locality 27 (2)'],
    268 => ['name' => 'Hungary Locality 28 (2)'],
    269 => ['name' => 'Hungary Locality 29 (2)'],
    270 => ['name' => 'Hungary Locality 30 (2)'],
    271 => ['name' => 'Hungary Locality 31 (2)'],
    272 => ['name' => 'Hungary Locality 32 (2)'],
    273 => ['name' => 'Hungary Locality 33 (2)'],
    274 => ['name' => 'Hungary Locality 34 (2)'],
    275 => ['name' => 'Hungary Locality 35 (2)'],
    276 => ['name' => 'Hungary Locality 36 (2)'],
    277 => ['name' => 'Hungary Locality 37 (2)'],
    278 => ['name' => 'Hungary Locality 38 (2)'],
    279 => ['name' => 'Hungary Locality 39 (2)'],
    280 => ['name' => 'Hungary Locality 40 (2)'],
    281 => ['name' => 'Hungary Locality 41 (2)'],
    282 => ['name' => 'Hungary Locality 42 (2)'],
    283 => ['name' => 'Hungary Locality 43 (2)'],
    284 => ['name' => 'Hungary Locality 44 (2)'],
    285 => ['name' => 'Hungary Locality 45 (2)'],
    286 => ['name' => 'Hungary Locality 46 (2)'],
    287 => ['name' => 'Hungary Locality 47 (2)'],
    288 => ['name' => 'Hungary Locality 48 (2)'],
    289 => ['name' => 'Hungary Locality 49 (2)'],
    290 => ['name' => 'Hungary Locality 50 (2)'],
    291 => ['name' => 'Hungary Locality 51 (2)'],
    292 => ['name' => 'Hungary Locality 52 (2)'],
    293 => ['name' => 'Hungary Locality 53 (2)'],
    294 => ['name' => 'Hungary Locality 54 (2)'],
    295 => ['name' => 'Hungary Locality 55 (2)'],
    296 => ['name' => 'Hungary Locality 56 (2)'],
    297 => ['name' => 'Hungary Locality 57 (2)'],
    298 => ['name' => 'Hungary Locality 58 (2)'],
    299 => ['name' => 'Hungary Locality 59 (2)'],
    300 => ['name' => 'Hungary Locality 60 (2)']
];