<?php

return [
    1 => ['name' => 'Reykjavík'],
    2 => ['name' => 'Kópavogur'],
    3 => ['name' => 'Hafnarfjörður'],
    4 => ['name' => 'Akureyri'],
    5 => ['name' => 'Reykjanesbær'],
    6 => ['name' => 'Garðabær'],
    7 => ['name' => 'Mosfellsbær'],
    8 => ['name' => 'Árborg'],
    9 => ['name' => 'Akranes'],
    10 => ['name' => 'Fjarðabyggð'],
    11 => ['name' => 'Seltjarnarnes'],
    12 => ['name' => 'Vestmannaeyjar'],
    13 => ['name' => 'Ísafjörður'],
    14 => ['name' => 'Sauðárkrókur'],
    15 => ['name' => 'Selfoss'],
    16 => ['name' => 'Hveragerði'],
    17 => ['name' => 'Egilsstaðir'],
    18 => ['name' => 'Húsavík'],
    19 => ['name' => 'Borgarnes'],
    20 => ['name' => 'Neskaupstaður'],
    21 => ['name' => 'Dalvík'],
    22 => ['name' => 'Siglufjörður'],
    23 => ['name' => 'Höfn'],
    24 => ['name' => 'Ísafjörður'],
    25 => ['name' => 'Ólafsfjörður'],
    26 => ['name' => 'Reyðarfjörður'],
    27 => ['name' => 'Fáskrúðsfjörður'],
    28 => ['name' => 'Seyðisfjörður'],
    29 => ['name' => 'Neskaupstaður'],
    30 => ['name' => 'Vopnafjörður'],
    31 => ['name' => 'Þórshöfn'],
    32 => ['name' => 'Hólmavík'],
    33 => ['name' => 'Patreksfjörður'],
    34 => ['name' => 'Bíldudalur'],
    35 => ['name' => 'Tálknafjörður'],
    36 => ['name' => 'Flateyri'],
    37 => ['name' => 'Suðureyri'],
    38 => ['name' => 'Bolungarvík'],
    39 => ['name' => 'Hnífsdalur'],
    40 => ['name' => 'Stykkishólmur'],
    41 => ['name' => 'Grundarfjörður'],
    42 => ['name' => 'Ólafsvík'],
    43 => ['name' => 'Snæfellsbær'],
    44 => ['name' => 'Reykholt'],
    45 => ['name' => 'Blönduós'],
    46 => ['name' => 'Skagaströnd'],
    47 => ['name' => 'Hvammstangi'],
    48 => ['name' => 'Laugar'],
    49 => ['name' => 'Hella'],
    50 => ['name' => 'Vík'],
    51 => ['name' => 'Kirkjubæjarklaustur'],
    52 => ['name' => 'Höfn'],
    53 => ['name' => 'Djúpivogur'],
    54 => ['name' => 'Eskifjörður'],
    55 => ['name' => 'Reyðarfjörður'],
    56 => ['name' => 'Fjarðabyggð'],
    57 => ['name' => 'Neskaupstaður'],
    58 => ['name' => 'Seyðisfjörður'],
    59 => ['name' => 'Egilsstaðir'],
    60 => ['name' => 'Vopnafjörður'],
     61 => ['name' => 'Iceland Locality 1'],
     62 => ['name' => 'Iceland Locality 2'],
     63 => ['name' => 'Iceland Locality 3'],
     64 => ['name' => 'Iceland Locality 4'],
     65 => ['name' => 'Iceland Locality 5'],
     66 => ['name' => 'Iceland Locality 6'],
     67 => ['name' => 'Iceland Locality 7'],
     68 => ['name' => 'Iceland Locality 8'],
     69 => ['name' => 'Iceland Locality 9'],
     70 => ['name' => 'Iceland Locality 10'],
     71 => ['name' => 'Iceland Locality 11'],
     72 => ['name' => 'Iceland Locality 12'],
     73 => ['name' => 'Iceland Locality 13'],
     74 => ['name' => 'Iceland Locality 14'],
     75 => ['name' => 'Iceland Locality 15'],
     76 => ['name' => 'Iceland Locality 16'],
     77 => ['name' => 'Iceland Locality 17'],
     78 => ['name' => 'Iceland Locality 18'],
     79 => ['name' => 'Iceland Locality 19'],
     80 => ['name' => 'Iceland Locality 20'],
     81 => ['name' => 'Iceland Locality 21'],
     82 => ['name' => 'Iceland Locality 22'],
     83 => ['name' => 'Iceland Locality 23'],
     84 => ['name' => 'Iceland Locality 24'],
     85 => ['name' => 'Iceland Locality 25'],
     86 => ['name' => 'Iceland Locality 26'],
     87 => ['name' => 'Iceland Locality 27'],
     88 => ['name' => 'Iceland Locality 28'],
     89 => ['name' => 'Iceland Locality 29'],
     90 => ['name' => 'Iceland Locality 30'],
     91 => ['name' => 'Iceland Locality 31'],
     92 => ['name' => 'Iceland Locality 32'],
     93 => ['name' => 'Iceland Locality 33'],
     94 => ['name' => 'Iceland Locality 34'],
     95 => ['name' => 'Iceland Locality 35'],
     96 => ['name' => 'Iceland Locality 36'],
     97 => ['name' => 'Iceland Locality 37'],
     98 => ['name' => 'Iceland Locality 38'],
     99 => ['name' => 'Iceland Locality 39'],
    100 => ['name' => 'Iceland Locality 40'],
    101 => ['name' => 'Iceland Locality 41'],
    102 => ['name' => 'Iceland Locality 42'],
    103 => ['name' => 'Iceland Locality 43'],
    104 => ['name' => 'Iceland Locality 44'],
    105 => ['name' => 'Iceland Locality 45'],
    106 => ['name' => 'Iceland Locality 46'],
    107 => ['name' => 'Iceland Locality 47'],
    108 => ['name' => 'Iceland Locality 48'],
    109 => ['name' => 'Iceland Locality 49'],
    110 => ['name' => 'Iceland Locality 50'],
    111 => ['name' => 'Iceland Locality 51'],
    112 => ['name' => 'Iceland Locality 52'],
    113 => ['name' => 'Iceland Locality 53'],
    114 => ['name' => 'Iceland Locality 54'],
    115 => ['name' => 'Iceland Locality 55'],
    116 => ['name' => 'Iceland Locality 56'],
    117 => ['name' => 'Iceland Locality 57'],
    118 => ['name' => 'Iceland Locality 58'],
    119 => ['name' => 'Iceland Locality 59'],
    120 => ['name' => 'Iceland Locality 60'],
    121 => ['name' => 'Iceland Locality 61'],
    122 => ['name' => 'Iceland Locality 62'],
    123 => ['name' => 'Iceland Locality 63'],
    124 => ['name' => 'Iceland Locality 64'],
    125 => ['name' => 'Iceland Locality 65'],
    126 => ['name' => 'Iceland Locality 66'],
    127 => ['name' => 'Iceland Locality 67'],
    128 => ['name' => 'Iceland Locality 68'],
    129 => ['name' => 'Iceland Locality 69'],
    130 => ['name' => 'Iceland Locality 70'],
    131 => ['name' => 'Iceland Locality 71'],
    132 => ['name' => 'Iceland Locality 72'],
    133 => ['name' => 'Iceland Locality 73'],
    134 => ['name' => 'Iceland Locality 74'],
    135 => ['name' => 'Iceland Locality 75'],
    136 => ['name' => 'Iceland Locality 76'],
    137 => ['name' => 'Iceland Locality 77'],
    138 => ['name' => 'Iceland Locality 78'],
    139 => ['name' => 'Iceland Locality 79'],
    140 => ['name' => 'Iceland Locality 80'],
    141 => ['name' => 'Iceland Locality 81'],
    142 => ['name' => 'Iceland Locality 82'],
    143 => ['name' => 'Iceland Locality 83'],
    144 => ['name' => 'Iceland Locality 84'],
    145 => ['name' => 'Iceland Locality 85'],
    146 => ['name' => 'Iceland Locality 86'],
    147 => ['name' => 'Iceland Locality 87'],
    148 => ['name' => 'Iceland Locality 88'],
    149 => ['name' => 'Iceland Locality 89'],
    150 => ['name' => 'Iceland Locality 90'],
    151 => ['name' => 'Iceland Locality 91'],
    152 => ['name' => 'Iceland Locality 92'],
    153 => ['name' => 'Iceland Locality 93'],
    154 => ['name' => 'Iceland Locality 94'],
    155 => ['name' => 'Iceland Locality 95'],
    156 => ['name' => 'Iceland Locality 96'],
    157 => ['name' => 'Iceland Locality 97'],
    158 => ['name' => 'Iceland Locality 98'],
    159 => ['name' => 'Iceland Locality 99'],
    160 => ['name' => 'Iceland Locality 100'],
    161 => ['name' => 'Iceland Locality 101'],
    162 => ['name' => 'Iceland Locality 102'],
    163 => ['name' => 'Iceland Locality 103'],
    164 => ['name' => 'Iceland Locality 104'],
    165 => ['name' => 'Iceland Locality 105'],
    166 => ['name' => 'Iceland Locality 106'],
    167 => ['name' => 'Iceland Locality 107'],
    168 => ['name' => 'Iceland Locality 108'],
    169 => ['name' => 'Iceland Locality 109'],
    170 => ['name' => 'Iceland Locality 110'],
    171 => ['name' => 'Iceland Locality 111'],
    172 => ['name' => 'Iceland Locality 112'],
    173 => ['name' => 'Iceland Locality 113'],
    174 => ['name' => 'Iceland Locality 114'],
    175 => ['name' => 'Iceland Locality 115'],
    176 => ['name' => 'Iceland Locality 116'],
    177 => ['name' => 'Iceland Locality 117'],
    178 => ['name' => 'Iceland Locality 118'],
    179 => ['name' => 'Iceland Locality 119'],
    180 => ['name' => 'Iceland Locality 120'],
    181 => ['name' => 'Iceland Locality 121'],
    182 => ['name' => 'Iceland Locality 122'],
    183 => ['name' => 'Iceland Locality 123'],
    184 => ['name' => 'Iceland Locality 124'],
    185 => ['name' => 'Iceland Locality 125'],
    186 => ['name' => 'Iceland Locality 126'],
    187 => ['name' => 'Iceland Locality 127'],
    188 => ['name' => 'Iceland Locality 128'],
    189 => ['name' => 'Iceland Locality 129'],
    190 => ['name' => 'Iceland Locality 130'],
    191 => ['name' => 'Iceland Locality 131'],
    192 => ['name' => 'Iceland Locality 132'],
    193 => ['name' => 'Iceland Locality 133'],
    194 => ['name' => 'Iceland Locality 134'],
    195 => ['name' => 'Iceland Locality 135'],
    196 => ['name' => 'Iceland Locality 136'],
    197 => ['name' => 'Iceland Locality 137'],
    198 => ['name' => 'Iceland Locality 138'],
    199 => ['name' => 'Iceland Locality 139'],
    200 => ['name' => 'Iceland Locality 140'],
    201 => ['name' => 'Iceland Locality 1 (2)'],
    202 => ['name' => 'Iceland Locality 2 (2)'],
    203 => ['name' => 'Iceland Locality 3 (2)'],
    204 => ['name' => 'Iceland Locality 4 (2)'],
    205 => ['name' => 'Iceland Locality 5 (2)'],
    206 => ['name' => 'Iceland Locality 6 (2)'],
    207 => ['name' => 'Iceland Locality 7 (2)'],
    208 => ['name' => 'Iceland Locality 8 (2)'],
    209 => ['name' => 'Iceland Locality 9 (2)'],
    210 => ['name' => 'Iceland Locality 10 (2)'],
    211 => ['name' => 'Iceland Locality 11 (2)'],
    212 => ['name' => 'Iceland Locality 12 (2)'],
    213 => ['name' => 'Iceland Locality 13 (2)'],
    214 => ['name' => 'Iceland Locality 14 (2)'],
    215 => ['name' => 'Iceland Locality 15 (2)'],
    216 => ['name' => 'Iceland Locality 16 (2)'],
    217 => ['name' => 'Iceland Locality 17 (2)'],
    218 => ['name' => 'Iceland Locality 18 (2)'],
    219 => ['name' => 'Iceland Locality 19 (2)'],
    220 => ['name' => 'Iceland Locality 20 (2)'],
    221 => ['name' => 'Iceland Locality 21 (2)'],
    222 => ['name' => 'Iceland Locality 22 (2)'],
    223 => ['name' => 'Iceland Locality 23 (2)'],
    224 => ['name' => 'Iceland Locality 24 (2)'],
    225 => ['name' => 'Iceland Locality 25 (2)'],
    226 => ['name' => 'Iceland Locality 26 (2)'],
    227 => ['name' => 'Iceland Locality 27 (2)'],
    228 => ['name' => 'Iceland Locality 28 (2)'],
    229 => ['name' => 'Iceland Locality 29 (2)'],
    230 => ['name' => 'Iceland Locality 30 (2)'],
    231 => ['name' => 'Iceland Locality 31 (2)'],
    232 => ['name' => 'Iceland Locality 32 (2)'],
    233 => ['name' => 'Iceland Locality 33 (2)'],
    234 => ['name' => 'Iceland Locality 34 (2)'],
    235 => ['name' => 'Iceland Locality 35 (2)'],
    236 => ['name' => 'Iceland Locality 36 (2)'],
    237 => ['name' => 'Iceland Locality 37 (2)'],
    238 => ['name' => 'Iceland Locality 38 (2)'],
    239 => ['name' => 'Iceland Locality 39 (2)'],
    240 => ['name' => 'Iceland Locality 40 (2)'],
    241 => ['name' => 'Iceland Locality 41 (2)'],
    242 => ['name' => 'Iceland Locality 42 (2)'],
    243 => ['name' => 'Iceland Locality 43 (2)'],
    244 => ['name' => 'Iceland Locality 44 (2)'],
    245 => ['name' => 'Iceland Locality 45 (2)'],
    246 => ['name' => 'Iceland Locality 46 (2)'],
    247 => ['name' => 'Iceland Locality 47 (2)'],
    248 => ['name' => 'Iceland Locality 48 (2)'],
    249 => ['name' => 'Iceland Locality 49 (2)'],
    250 => ['name' => 'Iceland Locality 50 (2)'],
    251 => ['name' => 'Iceland Locality 51 (2)'],
    252 => ['name' => 'Iceland Locality 52 (2)'],
    253 => ['name' => 'Iceland Locality 53 (2)'],
    254 => ['name' => 'Iceland Locality 54 (2)'],
    255 => ['name' => 'Iceland Locality 55 (2)'],
    256 => ['name' => 'Iceland Locality 56 (2)'],
    257 => ['name' => 'Iceland Locality 57 (2)'],
    258 => ['name' => 'Iceland Locality 58 (2)'],
    259 => ['name' => 'Iceland Locality 59 (2)'],
    260 => ['name' => 'Iceland Locality 60 (2)']
];