<?php

return [
    1 => ['name' => 'Bishkek'],
    2 => ['name' => 'Osh'],
    3 => ['name' => 'Jalal-Abad'],
    4 => ['name' => 'Karakol'],
    5 => ['name' => 'Tokmok'],
    6 => ['name' => 'Kara-Balta'],
    7 => ['name' => 'Naryn'],
    8 => ['name' => 'Batken'],
    9 => ['name' => 'Talas'],
    10 => ['name' => 'Kyzyl-Kiya'],
    11 => ['name' => 'Uzgen'],
    12 => ['name' => 'Balykchy'],
    13 => ['name' => 'Kant'],
    14 => ['name' => 'Kara-Suu'],
    15 => ['name' => 'Isfana'],
    16 => ['name' => 'Suluktu'],
    17 => ['name' => 'Tash-Kumyr'],
    18 => ['name' => 'Kök-Janggak'],
    19 => ['name' => 'Mailuu-Suu'],
    20 => ['name' => 'Kara-Köl'],
    21 => ['name' => 'Cholpon-Ata'],
    22 => ['name' => 'Karakol'],
    23 => ['name' => 'Naryn'],
    24 => ['name' => 'Bazar-Korgon'],
    25 => ['name' => 'Kochkor-Ata'],
    26 => ['name' => 'Talas'],
    27 => ['name' => 'Kara-Balta'],
    28 => ['name' => 'Sokuluk'],
    29 => ['name' => 'Kemin'],
    30 => ['name' => 'Orlovka'],
    31 => ['name' => 'Kyzyl-Suu'],
    32 => ['name' => 'At-Bashy'],
    33 => ['name' => 'Kochkor'],
    34 => ['name' => 'Kara-Kulja'],
    35 => ['name' => 'Ala-Buka'],
    36 => ['name' => 'Kadamjay'],
    37 => ['name' => 'Kazarman'],
    38 => ['name' => 'Nookat'],
    39 => ['name' => 'Aravan'],
    40 => ['name' => 'Guliston'],
    41 => ['name' => 'Sulyukta'],
    42 => ['name' => 'Kyzyl-Kiya'],
    43 => ['name' => 'Massy'],
    44 => ['name' => 'Kök-Janggak'],
    45 => ['name' => 'Tash-Kumyr'],
    46 => ['name' => 'Kara-Suu'],
    47 => ['name' => 'Uzgen'],
    48 => ['name' => 'Jalal-Abad'],
    49 => ['name' => 'Kara-Köl'],
    50 => ['name' => 'Balykchy'],
    51 => ['name' => 'Cholpon-Ata'],
    52 => ['name' => 'Karakol'],
    53 => ['name' => 'Naryn'],
    54 => ['name' => 'Bishkek'],
    55 => ['name' => 'Osh'],
    56 => ['name' => 'Talas'],
    57 => ['name' => 'Batken'],
    58 => ['name' => 'Kara-Balta'],
    59 => ['name' => 'Tokmok'],
    60 => ['name' => 'Kant'],
     61 => ['name' => 'Kyrgyzstan Locality 1'],
     62 => ['name' => 'Kyrgyzstan Locality 2'],
     63 => ['name' => 'Kyrgyzstan Locality 3'],
     64 => ['name' => 'Kyrgyzstan Locality 4'],
     65 => ['name' => 'Kyrgyzstan Locality 5'],
     66 => ['name' => 'Kyrgyzstan Locality 6'],
     67 => ['name' => 'Kyrgyzstan Locality 7'],
     68 => ['name' => 'Kyrgyzstan Locality 8'],
     69 => ['name' => 'Kyrgyzstan Locality 9'],
     70 => ['name' => 'Kyrgyzstan Locality 10'],
     71 => ['name' => 'Kyrgyzstan Locality 11'],
     72 => ['name' => 'Kyrgyzstan Locality 12'],
     73 => ['name' => 'Kyrgyzstan Locality 13'],
     74 => ['name' => 'Kyrgyzstan Locality 14'],
     75 => ['name' => 'Kyrgyzstan Locality 15'],
     76 => ['name' => 'Kyrgyzstan Locality 16'],
     77 => ['name' => 'Kyrgyzstan Locality 17'],
     78 => ['name' => 'Kyrgyzstan Locality 18'],
     79 => ['name' => 'Kyrgyzstan Locality 19'],
     80 => ['name' => 'Kyrgyzstan Locality 20'],
     81 => ['name' => 'Kyrgyzstan Locality 21'],
     82 => ['name' => 'Kyrgyzstan Locality 22'],
     83 => ['name' => 'Kyrgyzstan Locality 23'],
     84 => ['name' => 'Kyrgyzstan Locality 24'],
     85 => ['name' => 'Kyrgyzstan Locality 25'],
     86 => ['name' => 'Kyrgyzstan Locality 26'],
     87 => ['name' => 'Kyrgyzstan Locality 27'],
     88 => ['name' => 'Kyrgyzstan Locality 28'],
     89 => ['name' => 'Kyrgyzstan Locality 29'],
     90 => ['name' => 'Kyrgyzstan Locality 30'],
     91 => ['name' => 'Kyrgyzstan Locality 31'],
     92 => ['name' => 'Kyrgyzstan Locality 32'],
     93 => ['name' => 'Kyrgyzstan Locality 33'],
     94 => ['name' => 'Kyrgyzstan Locality 34'],
     95 => ['name' => 'Kyrgyzstan Locality 35'],
     96 => ['name' => 'Kyrgyzstan Locality 36'],
     97 => ['name' => 'Kyrgyzstan Locality 37'],
     98 => ['name' => 'Kyrgyzstan Locality 38'],
     99 => ['name' => 'Kyrgyzstan Locality 39'],
    100 => ['name' => 'Kyrgyzstan Locality 40'],
    101 => ['name' => 'Kyrgyzstan Locality 41'],
    102 => ['name' => 'Kyrgyzstan Locality 42'],
    103 => ['name' => 'Kyrgyzstan Locality 43'],
    104 => ['name' => 'Kyrgyzstan Locality 44'],
    105 => ['name' => 'Kyrgyzstan Locality 45'],
    106 => ['name' => 'Kyrgyzstan Locality 46'],
    107 => ['name' => 'Kyrgyzstan Locality 47'],
    108 => ['name' => 'Kyrgyzstan Locality 48'],
    109 => ['name' => 'Kyrgyzstan Locality 49'],
    110 => ['name' => 'Kyrgyzstan Locality 50'],
    111 => ['name' => 'Kyrgyzstan Locality 51'],
    112 => ['name' => 'Kyrgyzstan Locality 52'],
    113 => ['name' => 'Kyrgyzstan Locality 53'],
    114 => ['name' => 'Kyrgyzstan Locality 54'],
    115 => ['name' => 'Kyrgyzstan Locality 55'],
    116 => ['name' => 'Kyrgyzstan Locality 56'],
    117 => ['name' => 'Kyrgyzstan Locality 57'],
    118 => ['name' => 'Kyrgyzstan Locality 58'],
    119 => ['name' => 'Kyrgyzstan Locality 59'],
    120 => ['name' => 'Kyrgyzstan Locality 60'],
    121 => ['name' => 'Kyrgyzstan Locality 61'],
    122 => ['name' => 'Kyrgyzstan Locality 62'],
    123 => ['name' => 'Kyrgyzstan Locality 63'],
    124 => ['name' => 'Kyrgyzstan Locality 64'],
    125 => ['name' => 'Kyrgyzstan Locality 65'],
    126 => ['name' => 'Kyrgyzstan Locality 66'],
    127 => ['name' => 'Kyrgyzstan Locality 67'],
    128 => ['name' => 'Kyrgyzstan Locality 68'],
    129 => ['name' => 'Kyrgyzstan Locality 69'],
    130 => ['name' => 'Kyrgyzstan Locality 70'],
    131 => ['name' => 'Kyrgyzstan Locality 71'],
    132 => ['name' => 'Kyrgyzstan Locality 72'],
    133 => ['name' => 'Kyrgyzstan Locality 73'],
    134 => ['name' => 'Kyrgyzstan Locality 74'],
    135 => ['name' => 'Kyrgyzstan Locality 75'],
    136 => ['name' => 'Kyrgyzstan Locality 76'],
    137 => ['name' => 'Kyrgyzstan Locality 77'],
    138 => ['name' => 'Kyrgyzstan Locality 78'],
    139 => ['name' => 'Kyrgyzstan Locality 79'],
    140 => ['name' => 'Kyrgyzstan Locality 80'],
    141 => ['name' => 'Kyrgyzstan Locality 81'],
    142 => ['name' => 'Kyrgyzstan Locality 82'],
    143 => ['name' => 'Kyrgyzstan Locality 83'],
    144 => ['name' => 'Kyrgyzstan Locality 84'],
    145 => ['name' => 'Kyrgyzstan Locality 85'],
    146 => ['name' => 'Kyrgyzstan Locality 86'],
    147 => ['name' => 'Kyrgyzstan Locality 87'],
    148 => ['name' => 'Kyrgyzstan Locality 88'],
    149 => ['name' => 'Kyrgyzstan Locality 89'],
    150 => ['name' => 'Kyrgyzstan Locality 90'],
    151 => ['name' => 'Kyrgyzstan Locality 91'],
    152 => ['name' => 'Kyrgyzstan Locality 92'],
    153 => ['name' => 'Kyrgyzstan Locality 93'],
    154 => ['name' => 'Kyrgyzstan Locality 94'],
    155 => ['name' => 'Kyrgyzstan Locality 95'],
    156 => ['name' => 'Kyrgyzstan Locality 96'],
    157 => ['name' => 'Kyrgyzstan Locality 97'],
    158 => ['name' => 'Kyrgyzstan Locality 98'],
    159 => ['name' => 'Kyrgyzstan Locality 99'],
    160 => ['name' => 'Kyrgyzstan Locality 100'],
    161 => ['name' => 'Kyrgyzstan Locality 101'],
    162 => ['name' => 'Kyrgyzstan Locality 102'],
    163 => ['name' => 'Kyrgyzstan Locality 103'],
    164 => ['name' => 'Kyrgyzstan Locality 104'],
    165 => ['name' => 'Kyrgyzstan Locality 105'],
    166 => ['name' => 'Kyrgyzstan Locality 106'],
    167 => ['name' => 'Kyrgyzstan Locality 107'],
    168 => ['name' => 'Kyrgyzstan Locality 108'],
    169 => ['name' => 'Kyrgyzstan Locality 109'],
    170 => ['name' => 'Kyrgyzstan Locality 110'],
    171 => ['name' => 'Kyrgyzstan Locality 111'],
    172 => ['name' => 'Kyrgyzstan Locality 112'],
    173 => ['name' => 'Kyrgyzstan Locality 113'],
    174 => ['name' => 'Kyrgyzstan Locality 114'],
    175 => ['name' => 'Kyrgyzstan Locality 115'],
    176 => ['name' => 'Kyrgyzstan Locality 116'],
    177 => ['name' => 'Kyrgyzstan Locality 117'],
    178 => ['name' => 'Kyrgyzstan Locality 118'],
    179 => ['name' => 'Kyrgyzstan Locality 119'],
    180 => ['name' => 'Kyrgyzstan Locality 120'],
    181 => ['name' => 'Kyrgyzstan Locality 121'],
    182 => ['name' => 'Kyrgyzstan Locality 122'],
    183 => ['name' => 'Kyrgyzstan Locality 123'],
    184 => ['name' => 'Kyrgyzstan Locality 124'],
    185 => ['name' => 'Kyrgyzstan Locality 125'],
    186 => ['name' => 'Kyrgyzstan Locality 126'],
    187 => ['name' => 'Kyrgyzstan Locality 127'],
    188 => ['name' => 'Kyrgyzstan Locality 128'],
    189 => ['name' => 'Kyrgyzstan Locality 129'],
    190 => ['name' => 'Kyrgyzstan Locality 130'],
    191 => ['name' => 'Kyrgyzstan Locality 131'],
    192 => ['name' => 'Kyrgyzstan Locality 132'],
    193 => ['name' => 'Kyrgyzstan Locality 133'],
    194 => ['name' => 'Kyrgyzstan Locality 134'],
    195 => ['name' => 'Kyrgyzstan Locality 135'],
    196 => ['name' => 'Kyrgyzstan Locality 136'],
    197 => ['name' => 'Kyrgyzstan Locality 137'],
    198 => ['name' => 'Kyrgyzstan Locality 138'],
    199 => ['name' => 'Kyrgyzstan Locality 139'],
    200 => ['name' => 'Kyrgyzstan Locality 140'],
    201 => ['name' => 'Kyrgyzstan Locality 1 (2)'],
    202 => ['name' => 'Kyrgyzstan Locality 2 (2)'],
    203 => ['name' => 'Kyrgyzstan Locality 3 (2)'],
    204 => ['name' => 'Kyrgyzstan Locality 4 (2)'],
    205 => ['name' => 'Kyrgyzstan Locality 5 (2)'],
    206 => ['name' => 'Kyrgyzstan Locality 6 (2)'],
    207 => ['name' => 'Kyrgyzstan Locality 7 (2)'],
    208 => ['name' => 'Kyrgyzstan Locality 8 (2)'],
    209 => ['name' => 'Kyrgyzstan Locality 9 (2)'],
    210 => ['name' => 'Kyrgyzstan Locality 10 (2)'],
    211 => ['name' => 'Kyrgyzstan Locality 11 (2)'],
    212 => ['name' => 'Kyrgyzstan Locality 12 (2)'],
    213 => ['name' => 'Kyrgyzstan Locality 13 (2)'],
    214 => ['name' => 'Kyrgyzstan Locality 14 (2)'],
    215 => ['name' => 'Kyrgyzstan Locality 15 (2)'],
    216 => ['name' => 'Kyrgyzstan Locality 16 (2)'],
    217 => ['name' => 'Kyrgyzstan Locality 17 (2)'],
    218 => ['name' => 'Kyrgyzstan Locality 18 (2)'],
    219 => ['name' => 'Kyrgyzstan Locality 19 (2)'],
    220 => ['name' => 'Kyrgyzstan Locality 20 (2)'],
    221 => ['name' => 'Kyrgyzstan Locality 21 (2)'],
    222 => ['name' => 'Kyrgyzstan Locality 22 (2)'],
    223 => ['name' => 'Kyrgyzstan Locality 23 (2)'],
    224 => ['name' => 'Kyrgyzstan Locality 24 (2)'],
    225 => ['name' => 'Kyrgyzstan Locality 25 (2)'],
    226 => ['name' => 'Kyrgyzstan Locality 26 (2)'],
    227 => ['name' => 'Kyrgyzstan Locality 27 (2)'],
    228 => ['name' => 'Kyrgyzstan Locality 28 (2)'],
    229 => ['name' => 'Kyrgyzstan Locality 29 (2)'],
    230 => ['name' => 'Kyrgyzstan Locality 30 (2)'],
    231 => ['name' => 'Kyrgyzstan Locality 31 (2)'],
    232 => ['name' => 'Kyrgyzstan Locality 32 (2)'],
    233 => ['name' => 'Kyrgyzstan Locality 33 (2)'],
    234 => ['name' => 'Kyrgyzstan Locality 34 (2)'],
    235 => ['name' => 'Kyrgyzstan Locality 35 (2)'],
    236 => ['name' => 'Kyrgyzstan Locality 36 (2)'],
    237 => ['name' => 'Kyrgyzstan Locality 37 (2)'],
    238 => ['name' => 'Kyrgyzstan Locality 38 (2)'],
    239 => ['name' => 'Kyrgyzstan Locality 39 (2)'],
    240 => ['name' => 'Kyrgyzstan Locality 40 (2)'],
    241 => ['name' => 'Kyrgyzstan Locality 41 (2)'],
    242 => ['name' => 'Kyrgyzstan Locality 42 (2)'],
    243 => ['name' => 'Kyrgyzstan Locality 43 (2)'],
    244 => ['name' => 'Kyrgyzstan Locality 44 (2)'],
    245 => ['name' => 'Kyrgyzstan Locality 45 (2)'],
    246 => ['name' => 'Kyrgyzstan Locality 46 (2)'],
    247 => ['name' => 'Kyrgyzstan Locality 47 (2)'],
    248 => ['name' => 'Kyrgyzstan Locality 48 (2)'],
    249 => ['name' => 'Kyrgyzstan Locality 49 (2)'],
    250 => ['name' => 'Kyrgyzstan Locality 50 (2)'],
    251 => ['name' => 'Kyrgyzstan Locality 51 (2)'],
    252 => ['name' => 'Kyrgyzstan Locality 52 (2)'],
    253 => ['name' => 'Kyrgyzstan Locality 53 (2)'],
    254 => ['name' => 'Kyrgyzstan Locality 54 (2)'],
    255 => ['name' => 'Kyrgyzstan Locality 55 (2)'],
    256 => ['name' => 'Kyrgyzstan Locality 56 (2)'],
    257 => ['name' => 'Kyrgyzstan Locality 57 (2)'],
    258 => ['name' => 'Kyrgyzstan Locality 58 (2)'],
    259 => ['name' => 'Kyrgyzstan Locality 59 (2)'],
    260 => ['name' => 'Kyrgyzstan Locality 60 (2)']
];