<?php

return [
    1 => ['name' => 'Almaty'],
    2 => ['name' => 'Astana'],
    3 => ['name' => 'Shymkent'],
    4 => ['name' => 'Karaganda'],
    5 => ['name' => 'Aktobe'],
    6 => ['name' => 'Taraz'],
    7 => ['name' => 'Pavlodar'],
    8 => ['name' => 'Oskemen'],
    9 => ['name' => 'Semey'],
    10 => ['name' => 'Atyrau'],
    11 => ['name' => 'Kostanay'],
    12 => ['name' => 'Petropavl'],
    13 => ['name' => 'Oral'],
    14 => ['name' => 'Temirtau'],
    15 => ['name' => 'Turkistan'],
    16 => ['name' => 'Kyzylorda'],
    17 => ['name' => 'Kokshetau'],
    18 => ['name' => 'Taldykorgan'],
    19 => ['name' => 'Ekibastuz'],
    20 => ['name' => 'Rudny'],
    21 => ['name' => 'Zhanaozen'],
    22 => ['name' => 'Balkhash'],
    23 => ['name' => 'Kapshagay'],
    24 => ['name' => 'Zhezkazgan'],
    25 => ['name' => 'Baikonur'],
    26 => ['name' => 'Aktau'],
    27 => ['name' => 'Kandyagash'],
    28 => ['name' => 'Shakhtinsk'],
    29 => ['name' => 'Stepnogorsk'],
    30 => ['name' => 'Kentau'],
    31 => ['name' => 'Ridder'],
    32 => ['name' => 'Saran'],
    33 => ['name' => 'Satpayev'],
    34 => ['name' => 'Arkalyk'],
    35 => ['name' => 'Zaysan'],
    36 => ['name' => 'Pavlodar'],
    37 => ['name' => 'Uralsk'],
    38 => ['name' => 'Kulsary'],
    39 => ['name' => 'Shalkar'],
    40 => ['name' => 'Atyrau'],
    41 => ['name' => 'Talgar'],
    42 => ['name' => 'Esik'],
    43 => ['name' => 'Kaskelen'],
    44 => ['name' => 'Kapchagay'],
    45 => ['name' => 'Saryagash'],
    46 => ['name' => 'Shymkent'],
    47 => ['name' => 'Zhanaozen'],
    48 => ['name' => 'Aktau'],
    49 => ['name' => 'Zhosaly'],
    50 => ['name' => 'Kazalinsk'],
    51 => ['name' => 'Shu'],
    52 => ['name' => 'Taraz'],
    53 => ['name' => 'Korday'],
    54 => ['name' => 'Merke'],
    55 => ['name' => 'Karatau'],
    56 => ['name' => 'Sarykemer'],
    57 => ['name' => 'Balkhash'],
    58 => ['name' => 'Priozersk'],
    59 => ['name' => 'Karabulak'],
    60 => ['name' => 'Shakhtinsk'],
     61 => ['name' => 'Kazakhstan Locality 1'],
     62 => ['name' => 'Kazakhstan Locality 2'],
     63 => ['name' => 'Kazakhstan Locality 3'],
     64 => ['name' => 'Kazakhstan Locality 4'],
     65 => ['name' => 'Kazakhstan Locality 5'],
     66 => ['name' => 'Kazakhstan Locality 6'],
     67 => ['name' => 'Kazakhstan Locality 7'],
     68 => ['name' => 'Kazakhstan Locality 8'],
     69 => ['name' => 'Kazakhstan Locality 9'],
     70 => ['name' => 'Kazakhstan Locality 10'],
     71 => ['name' => 'Kazakhstan Locality 11'],
     72 => ['name' => 'Kazakhstan Locality 12'],
     73 => ['name' => 'Kazakhstan Locality 13'],
     74 => ['name' => 'Kazakhstan Locality 14'],
     75 => ['name' => 'Kazakhstan Locality 15'],
     76 => ['name' => 'Kazakhstan Locality 16'],
     77 => ['name' => 'Kazakhstan Locality 17'],
     78 => ['name' => 'Kazakhstan Locality 18'],
     79 => ['name' => 'Kazakhstan Locality 19'],
     80 => ['name' => 'Kazakhstan Locality 20'],
     81 => ['name' => 'Kazakhstan Locality 21'],
     82 => ['name' => 'Kazakhstan Locality 22'],
     83 => ['name' => 'Kazakhstan Locality 23'],
     84 => ['name' => 'Kazakhstan Locality 24'],
     85 => ['name' => 'Kazakhstan Locality 25'],
     86 => ['name' => 'Kazakhstan Locality 26'],
     87 => ['name' => 'Kazakhstan Locality 27'],
     88 => ['name' => 'Kazakhstan Locality 28'],
     89 => ['name' => 'Kazakhstan Locality 29'],
     90 => ['name' => 'Kazakhstan Locality 30'],
     91 => ['name' => 'Kazakhstan Locality 31'],
     92 => ['name' => 'Kazakhstan Locality 32'],
     93 => ['name' => 'Kazakhstan Locality 33'],
     94 => ['name' => 'Kazakhstan Locality 34'],
     95 => ['name' => 'Kazakhstan Locality 35'],
     96 => ['name' => 'Kazakhstan Locality 36'],
     97 => ['name' => 'Kazakhstan Locality 37'],
     98 => ['name' => 'Kazakhstan Locality 38'],
     99 => ['name' => 'Kazakhstan Locality 39'],
    100 => ['name' => 'Kazakhstan Locality 40'],
    101 => ['name' => 'Kazakhstan Locality 41'],
    102 => ['name' => 'Kazakhstan Locality 42'],
    103 => ['name' => 'Kazakhstan Locality 43'],
    104 => ['name' => 'Kazakhstan Locality 44'],
    105 => ['name' => 'Kazakhstan Locality 45'],
    106 => ['name' => 'Kazakhstan Locality 46'],
    107 => ['name' => 'Kazakhstan Locality 47'],
    108 => ['name' => 'Kazakhstan Locality 48'],
    109 => ['name' => 'Kazakhstan Locality 49'],
    110 => ['name' => 'Kazakhstan Locality 50'],
    111 => ['name' => 'Kazakhstan Locality 51'],
    112 => ['name' => 'Kazakhstan Locality 52'],
    113 => ['name' => 'Kazakhstan Locality 53'],
    114 => ['name' => 'Kazakhstan Locality 54'],
    115 => ['name' => 'Kazakhstan Locality 55'],
    116 => ['name' => 'Kazakhstan Locality 56'],
    117 => ['name' => 'Kazakhstan Locality 57'],
    118 => ['name' => 'Kazakhstan Locality 58'],
    119 => ['name' => 'Kazakhstan Locality 59'],
    120 => ['name' => 'Kazakhstan Locality 60'],
    121 => ['name' => 'Kazakhstan Locality 61'],
    122 => ['name' => 'Kazakhstan Locality 62'],
    123 => ['name' => 'Kazakhstan Locality 63'],
    124 => ['name' => 'Kazakhstan Locality 64'],
    125 => ['name' => 'Kazakhstan Locality 65'],
    126 => ['name' => 'Kazakhstan Locality 66'],
    127 => ['name' => 'Kazakhstan Locality 67'],
    128 => ['name' => 'Kazakhstan Locality 68'],
    129 => ['name' => 'Kazakhstan Locality 69'],
    130 => ['name' => 'Kazakhstan Locality 70'],
    131 => ['name' => 'Kazakhstan Locality 71'],
    132 => ['name' => 'Kazakhstan Locality 72'],
    133 => ['name' => 'Kazakhstan Locality 73'],
    134 => ['name' => 'Kazakhstan Locality 74'],
    135 => ['name' => 'Kazakhstan Locality 75'],
    136 => ['name' => 'Kazakhstan Locality 76'],
    137 => ['name' => 'Kazakhstan Locality 77'],
    138 => ['name' => 'Kazakhstan Locality 78'],
    139 => ['name' => 'Kazakhstan Locality 79'],
    140 => ['name' => 'Kazakhstan Locality 80'],
    141 => ['name' => 'Kazakhstan Locality 81'],
    142 => ['name' => 'Kazakhstan Locality 82'],
    143 => ['name' => 'Kazakhstan Locality 83'],
    144 => ['name' => 'Kazakhstan Locality 84'],
    145 => ['name' => 'Kazakhstan Locality 85'],
    146 => ['name' => 'Kazakhstan Locality 86'],
    147 => ['name' => 'Kazakhstan Locality 87'],
    148 => ['name' => 'Kazakhstan Locality 88'],
    149 => ['name' => 'Kazakhstan Locality 89'],
    150 => ['name' => 'Kazakhstan Locality 90'],
    151 => ['name' => 'Kazakhstan Locality 91'],
    152 => ['name' => 'Kazakhstan Locality 92'],
    153 => ['name' => 'Kazakhstan Locality 93'],
    154 => ['name' => 'Kazakhstan Locality 94'],
    155 => ['name' => 'Kazakhstan Locality 95'],
    156 => ['name' => 'Kazakhstan Locality 96'],
    157 => ['name' => 'Kazakhstan Locality 97'],
    158 => ['name' => 'Kazakhstan Locality 98'],
    159 => ['name' => 'Kazakhstan Locality 99'],
    160 => ['name' => 'Kazakhstan Locality 100'],
    161 => ['name' => 'Kazakhstan Locality 101'],
    162 => ['name' => 'Kazakhstan Locality 102'],
    163 => ['name' => 'Kazakhstan Locality 103'],
    164 => ['name' => 'Kazakhstan Locality 104'],
    165 => ['name' => 'Kazakhstan Locality 105'],
    166 => ['name' => 'Kazakhstan Locality 106'],
    167 => ['name' => 'Kazakhstan Locality 107'],
    168 => ['name' => 'Kazakhstan Locality 108'],
    169 => ['name' => 'Kazakhstan Locality 109'],
    170 => ['name' => 'Kazakhstan Locality 110'],
    171 => ['name' => 'Kazakhstan Locality 111'],
    172 => ['name' => 'Kazakhstan Locality 112'],
    173 => ['name' => 'Kazakhstan Locality 113'],
    174 => ['name' => 'Kazakhstan Locality 114'],
    175 => ['name' => 'Kazakhstan Locality 115'],
    176 => ['name' => 'Kazakhstan Locality 116'],
    177 => ['name' => 'Kazakhstan Locality 117'],
    178 => ['name' => 'Kazakhstan Locality 118'],
    179 => ['name' => 'Kazakhstan Locality 119'],
    180 => ['name' => 'Kazakhstan Locality 120'],
    181 => ['name' => 'Kazakhstan Locality 121'],
    182 => ['name' => 'Kazakhstan Locality 122'],
    183 => ['name' => 'Kazakhstan Locality 123'],
    184 => ['name' => 'Kazakhstan Locality 124'],
    185 => ['name' => 'Kazakhstan Locality 125'],
    186 => ['name' => 'Kazakhstan Locality 126'],
    187 => ['name' => 'Kazakhstan Locality 127'],
    188 => ['name' => 'Kazakhstan Locality 128'],
    189 => ['name' => 'Kazakhstan Locality 129'],
    190 => ['name' => 'Kazakhstan Locality 130'],
    191 => ['name' => 'Kazakhstan Locality 131'],
    192 => ['name' => 'Kazakhstan Locality 132'],
    193 => ['name' => 'Kazakhstan Locality 133'],
    194 => ['name' => 'Kazakhstan Locality 134'],
    195 => ['name' => 'Kazakhstan Locality 135'],
    196 => ['name' => 'Kazakhstan Locality 136'],
    197 => ['name' => 'Kazakhstan Locality 137'],
    198 => ['name' => 'Kazakhstan Locality 138'],
    199 => ['name' => 'Kazakhstan Locality 139'],
    200 => ['name' => 'Kazakhstan Locality 140'],
    201 => ['name' => 'Kazakhstan Locality 1 (2)'],
    202 => ['name' => 'Kazakhstan Locality 2 (2)'],
    203 => ['name' => 'Kazakhstan Locality 3 (2)'],
    204 => ['name' => 'Kazakhstan Locality 4 (2)'],
    205 => ['name' => 'Kazakhstan Locality 5 (2)'],
    206 => ['name' => 'Kazakhstan Locality 6 (2)'],
    207 => ['name' => 'Kazakhstan Locality 7 (2)'],
    208 => ['name' => 'Kazakhstan Locality 8 (2)'],
    209 => ['name' => 'Kazakhstan Locality 9 (2)'],
    210 => ['name' => 'Kazakhstan Locality 10 (2)'],
    211 => ['name' => 'Kazakhstan Locality 11 (2)'],
    212 => ['name' => 'Kazakhstan Locality 12 (2)'],
    213 => ['name' => 'Kazakhstan Locality 13 (2)'],
    214 => ['name' => 'Kazakhstan Locality 14 (2)'],
    215 => ['name' => 'Kazakhstan Locality 15 (2)'],
    216 => ['name' => 'Kazakhstan Locality 16 (2)'],
    217 => ['name' => 'Kazakhstan Locality 17 (2)'],
    218 => ['name' => 'Kazakhstan Locality 18 (2)'],
    219 => ['name' => 'Kazakhstan Locality 19 (2)'],
    220 => ['name' => 'Kazakhstan Locality 20 (2)'],
    221 => ['name' => 'Kazakhstan Locality 21 (2)'],
    222 => ['name' => 'Kazakhstan Locality 22 (2)'],
    223 => ['name' => 'Kazakhstan Locality 23 (2)'],
    224 => ['name' => 'Kazakhstan Locality 24 (2)'],
    225 => ['name' => 'Kazakhstan Locality 25 (2)'],
    226 => ['name' => 'Kazakhstan Locality 26 (2)'],
    227 => ['name' => 'Kazakhstan Locality 27 (2)'],
    228 => ['name' => 'Kazakhstan Locality 28 (2)'],
    229 => ['name' => 'Kazakhstan Locality 29 (2)'],
    230 => ['name' => 'Kazakhstan Locality 30 (2)'],
    231 => ['name' => 'Kazakhstan Locality 31 (2)'],
    232 => ['name' => 'Kazakhstan Locality 32 (2)'],
    233 => ['name' => 'Kazakhstan Locality 33 (2)'],
    234 => ['name' => 'Kazakhstan Locality 34 (2)'],
    235 => ['name' => 'Kazakhstan Locality 35 (2)'],
    236 => ['name' => 'Kazakhstan Locality 36 (2)'],
    237 => ['name' => 'Kazakhstan Locality 37 (2)'],
    238 => ['name' => 'Kazakhstan Locality 38 (2)'],
    239 => ['name' => 'Kazakhstan Locality 39 (2)'],
    240 => ['name' => 'Kazakhstan Locality 40 (2)'],
    241 => ['name' => 'Kazakhstan Locality 41 (2)'],
    242 => ['name' => 'Kazakhstan Locality 42 (2)'],
    243 => ['name' => 'Kazakhstan Locality 43 (2)'],
    244 => ['name' => 'Kazakhstan Locality 44 (2)'],
    245 => ['name' => 'Kazakhstan Locality 45 (2)'],
    246 => ['name' => 'Kazakhstan Locality 46 (2)'],
    247 => ['name' => 'Kazakhstan Locality 47 (2)'],
    248 => ['name' => 'Kazakhstan Locality 48 (2)'],
    249 => ['name' => 'Kazakhstan Locality 49 (2)'],
    250 => ['name' => 'Kazakhstan Locality 50 (2)'],
    251 => ['name' => 'Kazakhstan Locality 51 (2)'],
    252 => ['name' => 'Kazakhstan Locality 52 (2)'],
    253 => ['name' => 'Kazakhstan Locality 53 (2)'],
    254 => ['name' => 'Kazakhstan Locality 54 (2)'],
    255 => ['name' => 'Kazakhstan Locality 55 (2)'],
    256 => ['name' => 'Kazakhstan Locality 56 (2)'],
    257 => ['name' => 'Kazakhstan Locality 57 (2)'],
    258 => ['name' => 'Kazakhstan Locality 58 (2)'],
    259 => ['name' => 'Kazakhstan Locality 59 (2)'],
    260 => ['name' => 'Kazakhstan Locality 60 (2)']
];