<?php

return [
    1  => ['name' => 'Vilnius'],
    2  => ['name' => 'Kaunas'],
    3  => ['name' => 'Klaipėda'],
    4  => ['name' => 'Šiauliai'],
    5  => ['name' => 'Panevėžys'],
    6  => ['name' => 'Alytus'],
    7  => ['name' => 'Marijampolė'],
    8  => ['name' => 'Mažeikiai'],
    9  => ['name' => 'Jonava'],
    10 => ['name' => 'Utena'],
    11 => ['name' => 'Kėdainiai'],
    12 => ['name' => 'Telšiai'],
    13 => ['name' => 'Tauragė'],
    14 => ['name' => 'Visaginas'],
    15 => ['name' => 'Ukmergė'],
    16 => ['name' => 'Plungė'],
    17 => ['name' => 'Kretinga'],
    18 => ['name' => 'Šilutė'],
    19 => ['name' => 'Radviliškis'],
    20 => ['name' => 'Palanga'],
    21 => ['name' => 'Druskininkai'],
    22 => ['name' => 'Rokiškis'],
    23 => ['name' => 'Biržai'],
    24 => ['name' => 'Gargždai'],
    25 => ['name' => 'Jurbarkas'],
    26 => ['name' => 'Vilkaviškis'],
    27 => ['name' => 'Kazlų Rūda'],
    28 => ['name' => 'Molėtai'],
    29 => ['name' => 'Ignalina'],
    30 => ['name' => 'Anykščiai'],
    31 => ['name' => 'Kaišiadorys'],
    32 => ['name' => 'Širvintos'],
    33 => ['name' => 'Elektrėnai'],
    34 => ['name' => 'Pasvalys'],
    35 => ['name' => 'Trakai'],
    36 => ['name' => 'Zarasai'],
    37 => ['name' => 'Kupiškis'],
    38 => ['name' => 'Joniškis'],
    39 => ['name' => 'Šakiai'],
    40 => ['name' => 'Prienai'],
    41 => ['name' => 'Lazdijai'],
    42 => ['name' => 'Skuodas'],
    43 => ['name' => 'Kalvarija'],
    44 => ['name' => 'Neringa'],
    45 => ['name' => 'Pagėgiai'],
    46 => ['name' => 'Birštonas'],
    47 => ['name' => 'Akmenė'],
    48 => ['name' => 'Salantai'],
    49 => ['name' => 'Veisiejai'],
    50 => ['name' => 'Žiežmariai'],
    51 => ['name' => 'Baltoji Vokė'],
    52 => ['name' => 'Grigiškės'],
    53 => ['name' => 'Vievis'],
    54 => ['name' => 'Ežerėlis'],
    55 => ['name' => 'Rietavas'],
    56 => ['name' => 'Seda'],
    57 => ['name' => 'Tytuvėnai'],
    58 => ['name' => 'Varniai'],
    59 => ['name' => 'Gelgaudiškis'],
    60 => ['name' => 'Kudirkos Naumiestis'],
    61 => ['name' => 'Simnas'],
    62 => ['name' => 'Dusetos'],
    63 => ['name' => 'Viekšniai'],
    64 => ['name' => 'Ariogala'],
    65 => ['name' => 'Linkuva'],
    66 => ['name' => 'Pandėlys'],
    67 => ['name' => 'Ramygala'],
    68 => ['name' => 'Subačius'],
    69 => ['name' => 'Troškūnai'],
    70 => ['name' => 'Obeliai'],
    71 => ['name' => 'Naujoji Akmenė'],
    72 => ['name' => 'Šeduva'],
    73 => ['name' => 'Gelvonai'],
    74 => ['name' => 'Pabradė'],
    75 => ['name' => 'Švenčionys'],
    76 => ['name' => 'Švenčionėliai'],
    77 => ['name' => 'Kybartai'],
    78 => ['name' => 'Virbalis'],
    79 => ['name' => 'Lentvaris'],
    80 => ['name' => 'Vievis'],
    81 => ['name' => 'Pagiriai'],
    82 => ['name' => 'Rudamina'],
    83 => ['name' => 'Grigiškės'],
    84 => ['name' => 'Balbieriškis'],
    85 => ['name' => 'Žasliai'],
    86 => ['name' => 'Skaudvilė'],
    87 => ['name' => 'Užventis'],
    88 => ['name' => 'Vilkija'],
    89 => ['name' => 'Viešvilė'],
    90 => ['name' => 'Pajūris'],
    91 => ['name' => 'Aukštadvaris'],
    92 => ['name' => 'Eišiškės'],
    93 => ['name' => 'Lentvaris'],
    94 => ['name' => 'Rūdiškės'],
    95 => ['name' => 'Varėna'],
    96 => ['name' => 'Šilalė'],
    97 => ['name' => 'Jieznas'],
    98 => ['name' => 'Kelmė'],
    99 => ['name' => 'Nida'],
    100 => ['name' => 'Drūkšiai'],
    101 => ['name' => 'Šeduva'],
    102 => ['name' => 'Žagarė'],
    103 => ['name' => 'Alytus II (priemiesčio zona)'],
    104 => ['name' => 'Lithuania Locality 1'],
    105 => ['name' => 'Lithuania Locality 2'],
    106 => ['name' => 'Lithuania Locality 3'],
    107 => ['name' => 'Lithuania Locality 4'],
    108 => ['name' => 'Lithuania Locality 5'],
    109 => ['name' => 'Lithuania Locality 6'],
    110 => ['name' => 'Lithuania Locality 7'],
    111 => ['name' => 'Lithuania Locality 8'],
    112 => ['name' => 'Lithuania Locality 9'],
    113 => ['name' => 'Lithuania Locality 10'],
    114 => ['name' => 'Lithuania Locality 11'],
    115 => ['name' => 'Lithuania Locality 12'],
    116 => ['name' => 'Lithuania Locality 13'],
    117 => ['name' => 'Lithuania Locality 14'],
    118 => ['name' => 'Lithuania Locality 15'],
    119 => ['name' => 'Lithuania Locality 16'],
    120 => ['name' => 'Lithuania Locality 17'],
    121 => ['name' => 'Lithuania Locality 18'],
    122 => ['name' => 'Lithuania Locality 19'],
    123 => ['name' => 'Lithuania Locality 20'],
    124 => ['name' => 'Lithuania Locality 21'],
    125 => ['name' => 'Lithuania Locality 22'],
    126 => ['name' => 'Lithuania Locality 23'],
    127 => ['name' => 'Lithuania Locality 24'],
    128 => ['name' => 'Lithuania Locality 25'],
    129 => ['name' => 'Lithuania Locality 26'],
    130 => ['name' => 'Lithuania Locality 27'],
    131 => ['name' => 'Lithuania Locality 28'],
    132 => ['name' => 'Lithuania Locality 29'],
    133 => ['name' => 'Lithuania Locality 30'],
    134 => ['name' => 'Lithuania Locality 31'],
    135 => ['name' => 'Lithuania Locality 32'],
    136 => ['name' => 'Lithuania Locality 33'],
    137 => ['name' => 'Lithuania Locality 34'],
    138 => ['name' => 'Lithuania Locality 35'],
    139 => ['name' => 'Lithuania Locality 36'],
    140 => ['name' => 'Lithuania Locality 37'],
    141 => ['name' => 'Lithuania Locality 38'],
    142 => ['name' => 'Lithuania Locality 39'],
    143 => ['name' => 'Lithuania Locality 40'],
    144 => ['name' => 'Lithuania Locality 41'],
    145 => ['name' => 'Lithuania Locality 42'],
    146 => ['name' => 'Lithuania Locality 43'],
    147 => ['name' => 'Lithuania Locality 44'],
    148 => ['name' => 'Lithuania Locality 45'],
    149 => ['name' => 'Lithuania Locality 46'],
    150 => ['name' => 'Lithuania Locality 47'],
    151 => ['name' => 'Lithuania Locality 48'],
    152 => ['name' => 'Lithuania Locality 49'],
    153 => ['name' => 'Lithuania Locality 50'],
    154 => ['name' => 'Lithuania Locality 51'],
    155 => ['name' => 'Lithuania Locality 52'],
    156 => ['name' => 'Lithuania Locality 53'],
    157 => ['name' => 'Lithuania Locality 54'],
    158 => ['name' => 'Lithuania Locality 55'],
    159 => ['name' => 'Lithuania Locality 56'],
    160 => ['name' => 'Lithuania Locality 57'],
    161 => ['name' => 'Lithuania Locality 58'],
    162 => ['name' => 'Lithuania Locality 59'],
    163 => ['name' => 'Lithuania Locality 60'],
    164 => ['name' => 'Lithuania Locality 61'],
    165 => ['name' => 'Lithuania Locality 62'],
    166 => ['name' => 'Lithuania Locality 63'],
    167 => ['name' => 'Lithuania Locality 64'],
    168 => ['name' => 'Lithuania Locality 65'],
    169 => ['name' => 'Lithuania Locality 66'],
    170 => ['name' => 'Lithuania Locality 67'],
    171 => ['name' => 'Lithuania Locality 68'],
    172 => ['name' => 'Lithuania Locality 69'],
    173 => ['name' => 'Lithuania Locality 70'],
    174 => ['name' => 'Lithuania Locality 71'],
    175 => ['name' => 'Lithuania Locality 72'],
    176 => ['name' => 'Lithuania Locality 73'],
    177 => ['name' => 'Lithuania Locality 74'],
    178 => ['name' => 'Lithuania Locality 75'],
    179 => ['name' => 'Lithuania Locality 76'],
    180 => ['name' => 'Lithuania Locality 77'],
    181 => ['name' => 'Lithuania Locality 78'],
    182 => ['name' => 'Lithuania Locality 79'],
    183 => ['name' => 'Lithuania Locality 80'],
    184 => ['name' => 'Lithuania Locality 81'],
    185 => ['name' => 'Lithuania Locality 82'],
    186 => ['name' => 'Lithuania Locality 83'],
    187 => ['name' => 'Lithuania Locality 84'],
    188 => ['name' => 'Lithuania Locality 85'],
    189 => ['name' => 'Lithuania Locality 86'],
    190 => ['name' => 'Lithuania Locality 87'],
    191 => ['name' => 'Lithuania Locality 88'],
    192 => ['name' => 'Lithuania Locality 89'],
    193 => ['name' => 'Lithuania Locality 90'],
    194 => ['name' => 'Lithuania Locality 91'],
    195 => ['name' => 'Lithuania Locality 92'],
    196 => ['name' => 'Lithuania Locality 93'],
    197 => ['name' => 'Lithuania Locality 94'],
    198 => ['name' => 'Lithuania Locality 95'],
    199 => ['name' => 'Lithuania Locality 96'],
    200 => ['name' => 'Lithuania Locality 97'],
    201 => ['name' => 'Lithuania Locality 98'],
    202 => ['name' => 'Lithuania Locality 99'],
    203 => ['name' => 'Lithuania Locality 100'],
    204 => ['name' => 'Lithuania Locality 101'],
    205 => ['name' => 'Lithuania Locality 102'],
    206 => ['name' => 'Lithuania Locality 103'],
    207 => ['name' => 'Lithuania Locality 104'],
    208 => ['name' => 'Lithuania Locality 105'],
    209 => ['name' => 'Lithuania Locality 106'],
    210 => ['name' => 'Lithuania Locality 107'],
    211 => ['name' => 'Lithuania Locality 108'],
    212 => ['name' => 'Lithuania Locality 109'],
    213 => ['name' => 'Lithuania Locality 110'],
    214 => ['name' => 'Lithuania Locality 111'],
    215 => ['name' => 'Lithuania Locality 112'],
    216 => ['name' => 'Lithuania Locality 113'],
    217 => ['name' => 'Lithuania Locality 114'],
    218 => ['name' => 'Lithuania Locality 115'],
    219 => ['name' => 'Lithuania Locality 116'],
    220 => ['name' => 'Lithuania Locality 117'],
    221 => ['name' => 'Lithuania Locality 118'],
    222 => ['name' => 'Lithuania Locality 119'],
    223 => ['name' => 'Lithuania Locality 120'],
    224 => ['name' => 'Lithuania Locality 121'],
    225 => ['name' => 'Lithuania Locality 122'],
    226 => ['name' => 'Lithuania Locality 123'],
    227 => ['name' => 'Lithuania Locality 124'],
    228 => ['name' => 'Lithuania Locality 125'],
    229 => ['name' => 'Lithuania Locality 126'],
    230 => ['name' => 'Lithuania Locality 127'],
    231 => ['name' => 'Lithuania Locality 128'],
    232 => ['name' => 'Lithuania Locality 129'],
    233 => ['name' => 'Lithuania Locality 130'],
    234 => ['name' => 'Lithuania Locality 131'],
    235 => ['name' => 'Lithuania Locality 132'],
    236 => ['name' => 'Lithuania Locality 133'],
    237 => ['name' => 'Lithuania Locality 134'],
    238 => ['name' => 'Lithuania Locality 135'],
    239 => ['name' => 'Lithuania Locality 136'],
    240 => ['name' => 'Lithuania Locality 137'],
    241 => ['name' => 'Lithuania Locality 138'],
    242 => ['name' => 'Lithuania Locality 139'],
    243 => ['name' => 'Lithuania Locality 140'],
    244 => ['name' => 'Lithuania Locality 1 (2)'],
    245 => ['name' => 'Lithuania Locality 2 (2)'],
    246 => ['name' => 'Lithuania Locality 3 (2)'],
    247 => ['name' => 'Lithuania Locality 4 (2)'],
    248 => ['name' => 'Lithuania Locality 5 (2)'],
    249 => ['name' => 'Lithuania Locality 6 (2)'],
    250 => ['name' => 'Lithuania Locality 7 (2)'],
    251 => ['name' => 'Lithuania Locality 8 (2)'],
    252 => ['name' => 'Lithuania Locality 9 (2)'],
    253 => ['name' => 'Lithuania Locality 10 (2)'],
    254 => ['name' => 'Lithuania Locality 11 (2)'],
    255 => ['name' => 'Lithuania Locality 12 (2)'],
    256 => ['name' => 'Lithuania Locality 13 (2)'],
    257 => ['name' => 'Lithuania Locality 14 (2)'],
    258 => ['name' => 'Lithuania Locality 15 (2)'],
    259 => ['name' => 'Lithuania Locality 16 (2)'],
    260 => ['name' => 'Lithuania Locality 17 (2)'],
    261 => ['name' => 'Lithuania Locality 18 (2)'],
    262 => ['name' => 'Lithuania Locality 19 (2)'],
    263 => ['name' => 'Lithuania Locality 20 (2)'],
    264 => ['name' => 'Lithuania Locality 21 (2)'],
    265 => ['name' => 'Lithuania Locality 22 (2)'],
    266 => ['name' => 'Lithuania Locality 23 (2)'],
    267 => ['name' => 'Lithuania Locality 24 (2)'],
    268 => ['name' => 'Lithuania Locality 25 (2)'],
    269 => ['name' => 'Lithuania Locality 26 (2)'],
    270 => ['name' => 'Lithuania Locality 27 (2)'],
    271 => ['name' => 'Lithuania Locality 28 (2)'],
    272 => ['name' => 'Lithuania Locality 29 (2)'],
    273 => ['name' => 'Lithuania Locality 30 (2)'],
    274 => ['name' => 'Lithuania Locality 31 (2)'],
    275 => ['name' => 'Lithuania Locality 32 (2)'],
    276 => ['name' => 'Lithuania Locality 33 (2)'],
    277 => ['name' => 'Lithuania Locality 34 (2)'],
    278 => ['name' => 'Lithuania Locality 35 (2)'],
    279 => ['name' => 'Lithuania Locality 36 (2)'],
    280 => ['name' => 'Lithuania Locality 37 (2)'],
    281 => ['name' => 'Lithuania Locality 38 (2)'],
    282 => ['name' => 'Lithuania Locality 39 (2)'],
    283 => ['name' => 'Lithuania Locality 40 (2)'],
    284 => ['name' => 'Lithuania Locality 41 (2)'],
    285 => ['name' => 'Lithuania Locality 42 (2)'],
    286 => ['name' => 'Lithuania Locality 43 (2)'],
    287 => ['name' => 'Lithuania Locality 44 (2)'],
    288 => ['name' => 'Lithuania Locality 45 (2)'],
    289 => ['name' => 'Lithuania Locality 46 (2)'],
    290 => ['name' => 'Lithuania Locality 47 (2)'],
    291 => ['name' => 'Lithuania Locality 48 (2)'],
    292 => ['name' => 'Lithuania Locality 49 (2)'],
    293 => ['name' => 'Lithuania Locality 50 (2)'],
    294 => ['name' => 'Lithuania Locality 51 (2)'],
    295 => ['name' => 'Lithuania Locality 52 (2)'],
    296 => ['name' => 'Lithuania Locality 53 (2)'],
    297 => ['name' => 'Lithuania Locality 54 (2)'],
    298 => ['name' => 'Lithuania Locality 55 (2)'],
    299 => ['name' => 'Lithuania Locality 56 (2)'],
    300 => ['name' => 'Lithuania Locality 57 (2)'],
    301 => ['name' => 'Lithuania Locality 58 (2)'],
    302 => ['name' => 'Lithuania Locality 59 (2)'],
    303 => ['name' => 'Lithuania Locality 60 (2)']
];