<?php

return [
    1 => ['name' => 'Luxembourg City'],
    2 => ['name' => 'Esch-sur-Alzette'],
    3 => ['name' => 'Differdange'],
    4 => ['name' => 'Dudelange'],
    5 => ['name' => 'Pétange'],
    6 => ['name' => 'Sanem'],
    7 => ['name' => 'Hesperange'],
    8 => ['name' => 'Bettembourg'],
    9 => ['name' => 'Schifflange'],
    10 => ['name' => 'Kayl'],
    11 => ['name' => 'Ettelbruck'],
    12 => ['name' => 'Mersch'],
    13 => ['name' => 'Diekirch'],
    14 => ['name' => 'Wiltz'],
    15 => ['name' => 'Grevenmacher'],
    16 => ['name' => 'Remich'],
    17 => ['name' => 'Vianden'],
    18 => ['name' => 'Echternach'],
    19 => ['name' => 'Rumelange'],
    20 => ['name' => 'Bascharage'],
    21 => ['name' => 'Belvaux'],
    22 => ['name' => 'Clemency'],
    23 => ['name' => 'Colmar-Berg'],
    24 => ['name' => 'Contern'],
    25 => ['name' => 'Dalheim'],
    26 => ['name' => 'Dippach'],
    27 => ['name' => 'Frisange'],
    28 => ['name' => 'Garnich'],
    29 => ['name' => 'Junglinster'],
    30 => ['name' => 'Kopstal'],
    31 => ['name' => 'Larochette'],
    32 => ['name' => 'Leudelange'],
    33 => ['name' => 'Mondercange'],
    34 => ['name' => 'Niederanven'],
    35 => ['name' => 'Roeser'],
    36 => ['name' => 'Sandweiler'],
    37 => ['name' => 'Schengen'],
    38 => ['name' => 'Schuttrange'],
    39 => ['name' => 'Steinfort'],
    40 => ['name' => 'Strassen'],
    41 => ['name' => 'Walferdange'],
    42 => ['name' => 'Weiler-la-Tour'],
    43 => ['name' => 'Bertrange'],
    44 => ['name' => 'Bissen'],
    45 => ['name' => 'Bous'],
    46 => ['name' => 'Capellen'],
    47 => ['name' => 'Clervaux'],
    48 => ['name' => 'Redange'],
    49 => ['name' => 'Reckange-sur-Mess'],
    50 => ['name' => 'Rodange'],
    51 => ['name' => 'Steinsel'],
    52 => ['name' => 'Tandel'],
    53 => ['name' => 'Troisvierges'],
    54 => ['name' => 'Wormeldange'],
    55 => ['name' => 'Bettendorf'],
    56 => ['name' => 'Bridel'],
    57 => ['name' => 'Cessange'],
    58 => ['name' => 'Dommeldange'],
    59 => ['name' => 'Gasperich'],
    60 => ['name' => 'Hollerich'],
     61 => ['name' => 'Luxembourg Locality 1'],
     62 => ['name' => 'Luxembourg Locality 2'],
     63 => ['name' => 'Luxembourg Locality 3'],
     64 => ['name' => 'Luxembourg Locality 4'],
     65 => ['name' => 'Luxembourg Locality 5'],
     66 => ['name' => 'Luxembourg Locality 6'],
     67 => ['name' => 'Luxembourg Locality 7'],
     68 => ['name' => 'Luxembourg Locality 8'],
     69 => ['name' => 'Luxembourg Locality 9'],
     70 => ['name' => 'Luxembourg Locality 10'],
     71 => ['name' => 'Luxembourg Locality 11'],
     72 => ['name' => 'Luxembourg Locality 12'],
     73 => ['name' => 'Luxembourg Locality 13'],
     74 => ['name' => 'Luxembourg Locality 14'],
     75 => ['name' => 'Luxembourg Locality 15'],
     76 => ['name' => 'Luxembourg Locality 16'],
     77 => ['name' => 'Luxembourg Locality 17'],
     78 => ['name' => 'Luxembourg Locality 18'],
     79 => ['name' => 'Luxembourg Locality 19'],
     80 => ['name' => 'Luxembourg Locality 20'],
     81 => ['name' => 'Luxembourg Locality 21'],
     82 => ['name' => 'Luxembourg Locality 22'],
     83 => ['name' => 'Luxembourg Locality 23'],
     84 => ['name' => 'Luxembourg Locality 24'],
     85 => ['name' => 'Luxembourg Locality 25'],
     86 => ['name' => 'Luxembourg Locality 26'],
     87 => ['name' => 'Luxembourg Locality 27'],
     88 => ['name' => 'Luxembourg Locality 28'],
     89 => ['name' => 'Luxembourg Locality 29'],
     90 => ['name' => 'Luxembourg Locality 30'],
     91 => ['name' => 'Luxembourg Locality 31'],
     92 => ['name' => 'Luxembourg Locality 32'],
     93 => ['name' => 'Luxembourg Locality 33'],
     94 => ['name' => 'Luxembourg Locality 34'],
     95 => ['name' => 'Luxembourg Locality 35'],
     96 => ['name' => 'Luxembourg Locality 36'],
     97 => ['name' => 'Luxembourg Locality 37'],
     98 => ['name' => 'Luxembourg Locality 38'],
     99 => ['name' => 'Luxembourg Locality 39'],
    100 => ['name' => 'Luxembourg Locality 40'],
    101 => ['name' => 'Luxembourg Locality 41'],
    102 => ['name' => 'Luxembourg Locality 42'],
    103 => ['name' => 'Luxembourg Locality 43'],
    104 => ['name' => 'Luxembourg Locality 44'],
    105 => ['name' => 'Luxembourg Locality 45'],
    106 => ['name' => 'Luxembourg Locality 46'],
    107 => ['name' => 'Luxembourg Locality 47'],
    108 => ['name' => 'Luxembourg Locality 48'],
    109 => ['name' => 'Luxembourg Locality 49'],
    110 => ['name' => 'Luxembourg Locality 50'],
    111 => ['name' => 'Luxembourg Locality 51'],
    112 => ['name' => 'Luxembourg Locality 52'],
    113 => ['name' => 'Luxembourg Locality 53'],
    114 => ['name' => 'Luxembourg Locality 54'],
    115 => ['name' => 'Luxembourg Locality 55'],
    116 => ['name' => 'Luxembourg Locality 56'],
    117 => ['name' => 'Luxembourg Locality 57'],
    118 => ['name' => 'Luxembourg Locality 58'],
    119 => ['name' => 'Luxembourg Locality 59'],
    120 => ['name' => 'Luxembourg Locality 60'],
    121 => ['name' => 'Luxembourg Locality 61'],
    122 => ['name' => 'Luxembourg Locality 62'],
    123 => ['name' => 'Luxembourg Locality 63'],
    124 => ['name' => 'Luxembourg Locality 64'],
    125 => ['name' => 'Luxembourg Locality 65'],
    126 => ['name' => 'Luxembourg Locality 66'],
    127 => ['name' => 'Luxembourg Locality 67'],
    128 => ['name' => 'Luxembourg Locality 68'],
    129 => ['name' => 'Luxembourg Locality 69'],
    130 => ['name' => 'Luxembourg Locality 70'],
    131 => ['name' => 'Luxembourg Locality 71'],
    132 => ['name' => 'Luxembourg Locality 72'],
    133 => ['name' => 'Luxembourg Locality 73'],
    134 => ['name' => 'Luxembourg Locality 74'],
    135 => ['name' => 'Luxembourg Locality 75'],
    136 => ['name' => 'Luxembourg Locality 76'],
    137 => ['name' => 'Luxembourg Locality 77'],
    138 => ['name' => 'Luxembourg Locality 78'],
    139 => ['name' => 'Luxembourg Locality 79'],
    140 => ['name' => 'Luxembourg Locality 80'],
    141 => ['name' => 'Luxembourg Locality 81'],
    142 => ['name' => 'Luxembourg Locality 82'],
    143 => ['name' => 'Luxembourg Locality 83'],
    144 => ['name' => 'Luxembourg Locality 84'],
    145 => ['name' => 'Luxembourg Locality 85'],
    146 => ['name' => 'Luxembourg Locality 86'],
    147 => ['name' => 'Luxembourg Locality 87'],
    148 => ['name' => 'Luxembourg Locality 88'],
    149 => ['name' => 'Luxembourg Locality 89'],
    150 => ['name' => 'Luxembourg Locality 90'],
    151 => ['name' => 'Luxembourg Locality 91'],
    152 => ['name' => 'Luxembourg Locality 92'],
    153 => ['name' => 'Luxembourg Locality 93'],
    154 => ['name' => 'Luxembourg Locality 94'],
    155 => ['name' => 'Luxembourg Locality 95'],
    156 => ['name' => 'Luxembourg Locality 96'],
    157 => ['name' => 'Luxembourg Locality 97'],
    158 => ['name' => 'Luxembourg Locality 98'],
    159 => ['name' => 'Luxembourg Locality 99'],
    160 => ['name' => 'Luxembourg Locality 100'],
    161 => ['name' => 'Luxembourg Locality 101'],
    162 => ['name' => 'Luxembourg Locality 102'],
    163 => ['name' => 'Luxembourg Locality 103'],
    164 => ['name' => 'Luxembourg Locality 104'],
    165 => ['name' => 'Luxembourg Locality 105'],
    166 => ['name' => 'Luxembourg Locality 106'],
    167 => ['name' => 'Luxembourg Locality 107'],
    168 => ['name' => 'Luxembourg Locality 108'],
    169 => ['name' => 'Luxembourg Locality 109'],
    170 => ['name' => 'Luxembourg Locality 110'],
    171 => ['name' => 'Luxembourg Locality 111'],
    172 => ['name' => 'Luxembourg Locality 112'],
    173 => ['name' => 'Luxembourg Locality 113'],
    174 => ['name' => 'Luxembourg Locality 114'],
    175 => ['name' => 'Luxembourg Locality 115'],
    176 => ['name' => 'Luxembourg Locality 116'],
    177 => ['name' => 'Luxembourg Locality 117'],
    178 => ['name' => 'Luxembourg Locality 118'],
    179 => ['name' => 'Luxembourg Locality 119'],
    180 => ['name' => 'Luxembourg Locality 120'],
    181 => ['name' => 'Luxembourg Locality 121'],
    182 => ['name' => 'Luxembourg Locality 122'],
    183 => ['name' => 'Luxembourg Locality 123'],
    184 => ['name' => 'Luxembourg Locality 124'],
    185 => ['name' => 'Luxembourg Locality 125'],
    186 => ['name' => 'Luxembourg Locality 126'],
    187 => ['name' => 'Luxembourg Locality 127'],
    188 => ['name' => 'Luxembourg Locality 128'],
    189 => ['name' => 'Luxembourg Locality 129'],
    190 => ['name' => 'Luxembourg Locality 130'],
    191 => ['name' => 'Luxembourg Locality 131'],
    192 => ['name' => 'Luxembourg Locality 132'],
    193 => ['name' => 'Luxembourg Locality 133'],
    194 => ['name' => 'Luxembourg Locality 134'],
    195 => ['name' => 'Luxembourg Locality 135'],
    196 => ['name' => 'Luxembourg Locality 136'],
    197 => ['name' => 'Luxembourg Locality 137'],
    198 => ['name' => 'Luxembourg Locality 138'],
    199 => ['name' => 'Luxembourg Locality 139'],
    200 => ['name' => 'Luxembourg Locality 140'],
    201 => ['name' => 'Luxembourg Locality 1 (2)'],
    202 => ['name' => 'Luxembourg Locality 2 (2)'],
    203 => ['name' => 'Luxembourg Locality 3 (2)'],
    204 => ['name' => 'Luxembourg Locality 4 (2)'],
    205 => ['name' => 'Luxembourg Locality 5 (2)'],
    206 => ['name' => 'Luxembourg Locality 6 (2)'],
    207 => ['name' => 'Luxembourg Locality 7 (2)'],
    208 => ['name' => 'Luxembourg Locality 8 (2)'],
    209 => ['name' => 'Luxembourg Locality 9 (2)'],
    210 => ['name' => 'Luxembourg Locality 10 (2)'],
    211 => ['name' => 'Luxembourg Locality 11 (2)'],
    212 => ['name' => 'Luxembourg Locality 12 (2)'],
    213 => ['name' => 'Luxembourg Locality 13 (2)'],
    214 => ['name' => 'Luxembourg Locality 14 (2)'],
    215 => ['name' => 'Luxembourg Locality 15 (2)'],
    216 => ['name' => 'Luxembourg Locality 16 (2)'],
    217 => ['name' => 'Luxembourg Locality 17 (2)'],
    218 => ['name' => 'Luxembourg Locality 18 (2)'],
    219 => ['name' => 'Luxembourg Locality 19 (2)'],
    220 => ['name' => 'Luxembourg Locality 20 (2)'],
    221 => ['name' => 'Luxembourg Locality 21 (2)'],
    222 => ['name' => 'Luxembourg Locality 22 (2)'],
    223 => ['name' => 'Luxembourg Locality 23 (2)'],
    224 => ['name' => 'Luxembourg Locality 24 (2)'],
    225 => ['name' => 'Luxembourg Locality 25 (2)'],
    226 => ['name' => 'Luxembourg Locality 26 (2)'],
    227 => ['name' => 'Luxembourg Locality 27 (2)'],
    228 => ['name' => 'Luxembourg Locality 28 (2)'],
    229 => ['name' => 'Luxembourg Locality 29 (2)'],
    230 => ['name' => 'Luxembourg Locality 30 (2)'],
    231 => ['name' => 'Luxembourg Locality 31 (2)'],
    232 => ['name' => 'Luxembourg Locality 32 (2)'],
    233 => ['name' => 'Luxembourg Locality 33 (2)'],
    234 => ['name' => 'Luxembourg Locality 34 (2)'],
    235 => ['name' => 'Luxembourg Locality 35 (2)'],
    236 => ['name' => 'Luxembourg Locality 36 (2)'],
    237 => ['name' => 'Luxembourg Locality 37 (2)'],
    238 => ['name' => 'Luxembourg Locality 38 (2)'],
    239 => ['name' => 'Luxembourg Locality 39 (2)'],
    240 => ['name' => 'Luxembourg Locality 40 (2)'],
    241 => ['name' => 'Luxembourg Locality 41 (2)'],
    242 => ['name' => 'Luxembourg Locality 42 (2)'],
    243 => ['name' => 'Luxembourg Locality 43 (2)'],
    244 => ['name' => 'Luxembourg Locality 44 (2)'],
    245 => ['name' => 'Luxembourg Locality 45 (2)'],
    246 => ['name' => 'Luxembourg Locality 46 (2)'],
    247 => ['name' => 'Luxembourg Locality 47 (2)'],
    248 => ['name' => 'Luxembourg Locality 48 (2)'],
    249 => ['name' => 'Luxembourg Locality 49 (2)'],
    250 => ['name' => 'Luxembourg Locality 50 (2)'],
    251 => ['name' => 'Luxembourg Locality 51 (2)'],
    252 => ['name' => 'Luxembourg Locality 52 (2)'],
    253 => ['name' => 'Luxembourg Locality 53 (2)'],
    254 => ['name' => 'Luxembourg Locality 54 (2)'],
    255 => ['name' => 'Luxembourg Locality 55 (2)'],
    256 => ['name' => 'Luxembourg Locality 56 (2)'],
    257 => ['name' => 'Luxembourg Locality 57 (2)'],
    258 => ['name' => 'Luxembourg Locality 58 (2)'],
    259 => ['name' => 'Luxembourg Locality 59 (2)'],
    260 => ['name' => 'Luxembourg Locality 60 (2)']
];