<?php

return [
    1 => ['name' => 'Amsterdam'],
    2 => ['name' => 'Rotterdam'],
    3 => ['name' => 'The Hague'],
    4 => ['name' => 'Utrecht'],
    5 => ['name' => 'Eindhoven'],
    6 => ['name' => 'Groningen'],
    7 => ['name' => 'Tilburg'],
    8 => ['name' => 'Almere'],
    9 => ['name' => 'Breda'],
    10 => ['name' => 'Nijmegen'],
    11 => ['name' => 'Enschede'],
    12 => ['name' => 'Haarlem'],
    13 => ['name' => 'Arnhem'],
    14 => ['name' => 'Zaanstad'],
    15 => ['name' => 'Amersfoort'],
    16 => ['name' => 'Apeldoorn'],
    17 => ['name' => 'Den Bosch'],
    18 => ['name' => 'Hoofddorp'],
    19 => ['name' => 'Maastricht'],
    20 => ['name' => 'Leiden'],
    21 => ['name' => 'Dordrecht'],
    22 => ['name' => 'Zoetermeer'],
    23 => ['name' => 'Zwolle'],
    24 => ['name' => 'Deventer'],
    25 => ['name' => 'Ede'],
    26 => ['name' => 'Westland'],
    27 => ['name' => 'Venlo'],
    28 => ['name' => 'Leeuwarden'],
    29 => ['name' => 'Heerlen'],
    30 => ['name' => 'Hengelo'],
    31 => ['name' => 'Delft'],
    32 => ['name' => 'Oss'],
    33 => ['name' => 'Schiedam'],
    34 => ['name' => 'Purmerend'],
    35 => ['name' => 'Hilversum'],
    36 => ['name' => 'Spijkenisse'],
    37 => ['name' => 'Vlaardingen'],
    38 => ['name' => 'Gouda'],
    39 => ['name' => 'Alphen aan den Rijn'],
    40 => ['name' => 'Bergen op Zoom'],
    41 => ['name' => 'Hoorn'],
    42 => ['name' => 'Leidschendam-Voorburg'],
    43 => ['name' => 'Alkmaar'],
    44 => ['name' => 'Heerhugowaard'],
    45 => ['name' => 'Lelystad'],
    46 => ['name' => 'Helmond'],
    47 => ['name' => 'Emmen'],
    48 => ['name' => 'Assen'],
    49 => ['name' => 'Roosendaal'],
    50 => ['name' => 'Oosterhout'],
    51 => ['name' => 'Hoogeveen'],
    52 => ['name' => 'Kampen'],
    53 => ['name' => 'Sittard-Geleen'],
    54 => ['name' => 'Venray'],
    55 => ['name' => 'Weert'],
    56 => ['name' => 'Heerenveen'],
    57 => ['name' => 'Zaanstad'],
    58 => ['name' => 'Amstelveen'],
    59 => ['name' => 'Capelle aan den IJssel'],
    60 => ['name' => 'Haarlemmermeer'],
     61 => ['name' => 'Netherlands Locality 1'],
     62 => ['name' => 'Netherlands Locality 2'],
     63 => ['name' => 'Netherlands Locality 3'],
     64 => ['name' => 'Netherlands Locality 4'],
     65 => ['name' => 'Netherlands Locality 5'],
     66 => ['name' => 'Netherlands Locality 6'],
     67 => ['name' => 'Netherlands Locality 7'],
     68 => ['name' => 'Netherlands Locality 8'],
     69 => ['name' => 'Netherlands Locality 9'],
     70 => ['name' => 'Netherlands Locality 10'],
     71 => ['name' => 'Netherlands Locality 11'],
     72 => ['name' => 'Netherlands Locality 12'],
     73 => ['name' => 'Netherlands Locality 13'],
     74 => ['name' => 'Netherlands Locality 14'],
     75 => ['name' => 'Netherlands Locality 15'],
     76 => ['name' => 'Netherlands Locality 16'],
     77 => ['name' => 'Netherlands Locality 17'],
     78 => ['name' => 'Netherlands Locality 18'],
     79 => ['name' => 'Netherlands Locality 19'],
     80 => ['name' => 'Netherlands Locality 20'],
     81 => ['name' => 'Netherlands Locality 21'],
     82 => ['name' => 'Netherlands Locality 22'],
     83 => ['name' => 'Netherlands Locality 23'],
     84 => ['name' => 'Netherlands Locality 24'],
     85 => ['name' => 'Netherlands Locality 25'],
     86 => ['name' => 'Netherlands Locality 26'],
     87 => ['name' => 'Netherlands Locality 27'],
     88 => ['name' => 'Netherlands Locality 28'],
     89 => ['name' => 'Netherlands Locality 29'],
     90 => ['name' => 'Netherlands Locality 30'],
     91 => ['name' => 'Netherlands Locality 31'],
     92 => ['name' => 'Netherlands Locality 32'],
     93 => ['name' => 'Netherlands Locality 33'],
     94 => ['name' => 'Netherlands Locality 34'],
     95 => ['name' => 'Netherlands Locality 35'],
     96 => ['name' => 'Netherlands Locality 36'],
     97 => ['name' => 'Netherlands Locality 37'],
     98 => ['name' => 'Netherlands Locality 38'],
     99 => ['name' => 'Netherlands Locality 39'],
    100 => ['name' => 'Netherlands Locality 40'],
    101 => ['name' => 'Netherlands Locality 41'],
    102 => ['name' => 'Netherlands Locality 42'],
    103 => ['name' => 'Netherlands Locality 43'],
    104 => ['name' => 'Netherlands Locality 44'],
    105 => ['name' => 'Netherlands Locality 45'],
    106 => ['name' => 'Netherlands Locality 46'],
    107 => ['name' => 'Netherlands Locality 47'],
    108 => ['name' => 'Netherlands Locality 48'],
    109 => ['name' => 'Netherlands Locality 49'],
    110 => ['name' => 'Netherlands Locality 50'],
    111 => ['name' => 'Netherlands Locality 51'],
    112 => ['name' => 'Netherlands Locality 52'],
    113 => ['name' => 'Netherlands Locality 53'],
    114 => ['name' => 'Netherlands Locality 54'],
    115 => ['name' => 'Netherlands Locality 55'],
    116 => ['name' => 'Netherlands Locality 56'],
    117 => ['name' => 'Netherlands Locality 57'],
    118 => ['name' => 'Netherlands Locality 58'],
    119 => ['name' => 'Netherlands Locality 59'],
    120 => ['name' => 'Netherlands Locality 60'],
    121 => ['name' => 'Netherlands Locality 61'],
    122 => ['name' => 'Netherlands Locality 62'],
    123 => ['name' => 'Netherlands Locality 63'],
    124 => ['name' => 'Netherlands Locality 64'],
    125 => ['name' => 'Netherlands Locality 65'],
    126 => ['name' => 'Netherlands Locality 66'],
    127 => ['name' => 'Netherlands Locality 67'],
    128 => ['name' => 'Netherlands Locality 68'],
    129 => ['name' => 'Netherlands Locality 69'],
    130 => ['name' => 'Netherlands Locality 70'],
    131 => ['name' => 'Netherlands Locality 71'],
    132 => ['name' => 'Netherlands Locality 72'],
    133 => ['name' => 'Netherlands Locality 73'],
    134 => ['name' => 'Netherlands Locality 74'],
    135 => ['name' => 'Netherlands Locality 75'],
    136 => ['name' => 'Netherlands Locality 76'],
    137 => ['name' => 'Netherlands Locality 77'],
    138 => ['name' => 'Netherlands Locality 78'],
    139 => ['name' => 'Netherlands Locality 79'],
    140 => ['name' => 'Netherlands Locality 80'],
    141 => ['name' => 'Netherlands Locality 81'],
    142 => ['name' => 'Netherlands Locality 82'],
    143 => ['name' => 'Netherlands Locality 83'],
    144 => ['name' => 'Netherlands Locality 84'],
    145 => ['name' => 'Netherlands Locality 85'],
    146 => ['name' => 'Netherlands Locality 86'],
    147 => ['name' => 'Netherlands Locality 87'],
    148 => ['name' => 'Netherlands Locality 88'],
    149 => ['name' => 'Netherlands Locality 89'],
    150 => ['name' => 'Netherlands Locality 90'],
    151 => ['name' => 'Netherlands Locality 91'],
    152 => ['name' => 'Netherlands Locality 92'],
    153 => ['name' => 'Netherlands Locality 93'],
    154 => ['name' => 'Netherlands Locality 94'],
    155 => ['name' => 'Netherlands Locality 95'],
    156 => ['name' => 'Netherlands Locality 96'],
    157 => ['name' => 'Netherlands Locality 97'],
    158 => ['name' => 'Netherlands Locality 98'],
    159 => ['name' => 'Netherlands Locality 99'],
    160 => ['name' => 'Netherlands Locality 100'],
    161 => ['name' => 'Netherlands Locality 101'],
    162 => ['name' => 'Netherlands Locality 102'],
    163 => ['name' => 'Netherlands Locality 103'],
    164 => ['name' => 'Netherlands Locality 104'],
    165 => ['name' => 'Netherlands Locality 105'],
    166 => ['name' => 'Netherlands Locality 106'],
    167 => ['name' => 'Netherlands Locality 107'],
    168 => ['name' => 'Netherlands Locality 108'],
    169 => ['name' => 'Netherlands Locality 109'],
    170 => ['name' => 'Netherlands Locality 110'],
    171 => ['name' => 'Netherlands Locality 111'],
    172 => ['name' => 'Netherlands Locality 112'],
    173 => ['name' => 'Netherlands Locality 113'],
    174 => ['name' => 'Netherlands Locality 114'],
    175 => ['name' => 'Netherlands Locality 115'],
    176 => ['name' => 'Netherlands Locality 116'],
    177 => ['name' => 'Netherlands Locality 117'],
    178 => ['name' => 'Netherlands Locality 118'],
    179 => ['name' => 'Netherlands Locality 119'],
    180 => ['name' => 'Netherlands Locality 120'],
    181 => ['name' => 'Netherlands Locality 121'],
    182 => ['name' => 'Netherlands Locality 122'],
    183 => ['name' => 'Netherlands Locality 123'],
    184 => ['name' => 'Netherlands Locality 124'],
    185 => ['name' => 'Netherlands Locality 125'],
    186 => ['name' => 'Netherlands Locality 126'],
    187 => ['name' => 'Netherlands Locality 127'],
    188 => ['name' => 'Netherlands Locality 128'],
    189 => ['name' => 'Netherlands Locality 129'],
    190 => ['name' => 'Netherlands Locality 130'],
    191 => ['name' => 'Netherlands Locality 131'],
    192 => ['name' => 'Netherlands Locality 132'],
    193 => ['name' => 'Netherlands Locality 133'],
    194 => ['name' => 'Netherlands Locality 134'],
    195 => ['name' => 'Netherlands Locality 135'],
    196 => ['name' => 'Netherlands Locality 136'],
    197 => ['name' => 'Netherlands Locality 137'],
    198 => ['name' => 'Netherlands Locality 138'],
    199 => ['name' => 'Netherlands Locality 139'],
    200 => ['name' => 'Netherlands Locality 140'],
    201 => ['name' => 'Netherlands Locality 1 (2)'],
    202 => ['name' => 'Netherlands Locality 2 (2)'],
    203 => ['name' => 'Netherlands Locality 3 (2)'],
    204 => ['name' => 'Netherlands Locality 4 (2)'],
    205 => ['name' => 'Netherlands Locality 5 (2)'],
    206 => ['name' => 'Netherlands Locality 6 (2)'],
    207 => ['name' => 'Netherlands Locality 7 (2)'],
    208 => ['name' => 'Netherlands Locality 8 (2)'],
    209 => ['name' => 'Netherlands Locality 9 (2)'],
    210 => ['name' => 'Netherlands Locality 10 (2)'],
    211 => ['name' => 'Netherlands Locality 11 (2)'],
    212 => ['name' => 'Netherlands Locality 12 (2)'],
    213 => ['name' => 'Netherlands Locality 13 (2)'],
    214 => ['name' => 'Netherlands Locality 14 (2)'],
    215 => ['name' => 'Netherlands Locality 15 (2)'],
    216 => ['name' => 'Netherlands Locality 16 (2)'],
    217 => ['name' => 'Netherlands Locality 17 (2)'],
    218 => ['name' => 'Netherlands Locality 18 (2)'],
    219 => ['name' => 'Netherlands Locality 19 (2)'],
    220 => ['name' => 'Netherlands Locality 20 (2)'],
    221 => ['name' => 'Netherlands Locality 21 (2)'],
    222 => ['name' => 'Netherlands Locality 22 (2)'],
    223 => ['name' => 'Netherlands Locality 23 (2)'],
    224 => ['name' => 'Netherlands Locality 24 (2)'],
    225 => ['name' => 'Netherlands Locality 25 (2)'],
    226 => ['name' => 'Netherlands Locality 26 (2)'],
    227 => ['name' => 'Netherlands Locality 27 (2)'],
    228 => ['name' => 'Netherlands Locality 28 (2)'],
    229 => ['name' => 'Netherlands Locality 29 (2)'],
    230 => ['name' => 'Netherlands Locality 30 (2)'],
    231 => ['name' => 'Netherlands Locality 31 (2)'],
    232 => ['name' => 'Netherlands Locality 32 (2)'],
    233 => ['name' => 'Netherlands Locality 33 (2)'],
    234 => ['name' => 'Netherlands Locality 34 (2)'],
    235 => ['name' => 'Netherlands Locality 35 (2)'],
    236 => ['name' => 'Netherlands Locality 36 (2)'],
    237 => ['name' => 'Netherlands Locality 37 (2)'],
    238 => ['name' => 'Netherlands Locality 38 (2)'],
    239 => ['name' => 'Netherlands Locality 39 (2)'],
    240 => ['name' => 'Netherlands Locality 40 (2)'],
    241 => ['name' => 'Netherlands Locality 41 (2)'],
    242 => ['name' => 'Netherlands Locality 42 (2)'],
    243 => ['name' => 'Netherlands Locality 43 (2)'],
    244 => ['name' => 'Netherlands Locality 44 (2)'],
    245 => ['name' => 'Netherlands Locality 45 (2)'],
    246 => ['name' => 'Netherlands Locality 46 (2)'],
    247 => ['name' => 'Netherlands Locality 47 (2)'],
    248 => ['name' => 'Netherlands Locality 48 (2)'],
    249 => ['name' => 'Netherlands Locality 49 (2)'],
    250 => ['name' => 'Netherlands Locality 50 (2)'],
    251 => ['name' => 'Netherlands Locality 51 (2)'],
    252 => ['name' => 'Netherlands Locality 52 (2)'],
    253 => ['name' => 'Netherlands Locality 53 (2)'],
    254 => ['name' => 'Netherlands Locality 54 (2)'],
    255 => ['name' => 'Netherlands Locality 55 (2)'],
    256 => ['name' => 'Netherlands Locality 56 (2)'],
    257 => ['name' => 'Netherlands Locality 57 (2)'],
    258 => ['name' => 'Netherlands Locality 58 (2)'],
    259 => ['name' => 'Netherlands Locality 59 (2)'],
    260 => ['name' => 'Netherlands Locality 60 (2)']
];