<?php

return [
    1  => ['name' => 'Warszawa'],
    2  => ['name' => 'Kraków'],
    3  => ['name' => 'Łódź'],
    4  => ['name' => 'Wrocław'],
    5  => ['name' => 'Poznań'],
    6  => ['name' => 'Gdańsk'],
    7  => ['name' => 'Szczecin'],
    8  => ['name' => 'Bydgoszcz'],
    9  => ['name' => 'Lublin'],
    10 => ['name' => 'Białystok'],
    11 => ['name' => 'Katowice'],
    12 => ['name' => 'Gdynia'],
    13 => ['name' => 'Częstochowa'],
    14 => ['name' => 'Radom'],
    15 => ['name' => 'Toruń'],
    16 => ['name' => 'Kielce'],
    17 => ['name' => 'Rzeszów'],
    18 => ['name' => 'Gliwice'],
    19 => ['name' => 'Zabrze'],
    20 => ['name' => 'Bytom'],
    21 => ['name' => 'Bielsko-Biała'],
    22 => ['name' => 'Olsztyn'],
    23 => ['name' => 'Rybnik'],
    24 => ['name' => 'Tychy'],
    25 => ['name' => 'Opole'],
    26 => ['name' => 'Elbląg'],
    27 => ['name' => 'Płock'],
    28 => ['name' => 'Wałbrzych'],
    29 => ['name' => 'Zielona Góra'],
    30 => ['name' => 'Włocławek'],
    31 => ['name' => 'Tarnów'],
    32 => ['name' => 'Chorzów'],
    33 => ['name' => 'Koszalin'],
    34 => ['name' => 'Legnica'],
    35 => ['name' => 'Grudziądz'],
    36 => ['name' => 'Jaworzno'],
    37 => ['name' => 'Słupsk'],
    38 => ['name' => 'Jastrzębie-Zdrój'],
    39 => ['name' => 'Nowy Sącz'],
    40 => ['name' => 'Jelenia Góra'],
    41 => ['name' => 'Konin'],
    42 => ['name' => 'Piła'],
    43 => ['name' => 'Ostrowiec Świętokrzyski'],
    44 => ['name' => 'Piotrków Trybunalski'],
    45 => ['name' => 'Lubin'],
    46 => ['name' => 'Gorzów Wielkopolski'],
    47 => ['name' => 'Siemianowice Śląskie'],
    48 => ['name' => 'Pabianice'],
    49 => ['name' => 'Chełm'],
    50 => ['name' => 'Przemyśl'],
    51 => ['name' => 'Stalowa Wola'],
    52 => ['name' => 'Tarnowskie Góry'],
    53 => ['name' => 'Tomaszów Mazowiecki'],
    54 => ['name' => 'Zamość'],
    55 => ['name' => 'Leszno'],
    56 => ['name' => 'Łomża'],
    57 => ['name' => 'Bełchatów'],
    58 => ['name' => 'Świdnica'],
    59 => ['name' => 'Nowy Targ'],
    60 => ['name' => 'Mysłowice'],
    61 => ['name' => 'Inowrocław'],
    62 => ['name' => 'Ostrów Wielkopolski'],
    63 => ['name' => 'Gniezno'],
    64 => ['name' => 'Suwałki'],
    65 => ['name' => 'Stargard'],
    66 => ['name' => 'Kutno'],
    67 => ['name' => 'Siedlce'],
    68 => ['name' => 'Skierniewice'],
    69 => ['name' => 'Żory'],
    70 => ['name' => 'Starachowice'],
    71 => ['name' => 'Ełk'],
    72 => ['name' => 'Mielec'],
    73 => ['name' => 'Legionowo'],
    74 => ['name' => 'Ostrołęka'],
    75 => ['name' => 'Świnoujście'],
    76 => ['name' => 'Krosno'],
    77 => ['name' => 'Łowicz'],
    78 => ['name' => 'Skarżysko-Kamienna'],
    79 => ['name' => 'Rumia'],
    80 => ['name' => 'Zgierz'],
    81 => ['name' => 'Knurów'],
    82 => ['name' => 'Kołobrzeg'],
    83 => ['name' => 'Ciechanów'],
    84 => ['name' => 'Nysa'],
    85 => ['name' => 'Bochnia'],
    86 => ['name' => 'Świętochłowice'],
    87 => ['name' => 'Puławy'],
    88 => ['name' => 'Sopot'],
    89 => ['name' => 'Brodnica'],
    90 => ['name' => 'Nowa Sól'],
    91 => ['name' => 'Zakopane'],
    92 => ['name' => 'Żywiec'],
    93 => ['name' => 'Sanok'],
    94 => ['name' => 'Malbork'],
    95 => ['name' => 'Biała Podlaska'],
    96 => ['name' => 'Kędzierzyn-Koźle'],
    97 => ['name' => 'Jarosław'],
    98 => ['name' => 'Świdnik'],
    99 => ['name' => 'Oława'],
    100 => ['name' => 'Police'],
    101 => ['name' => 'Turek'],
    102 => ['name' => 'Kłodzko'],
    103 => ['name' => 'Lębork'],
    104 => ['name' => 'Nowy Dwór Mazowiecki'],
    105 => ['name' => 'Kraśnik'],
    106 => ['name' => 'Brzeg'],
    107 => ['name' => 'Wodzisław Śląski'],
    108 => ['name' => 'Chojnice'],
    109 => ['name' => 'Mikołów'],
    110 => ['name' => 'Oleśnica'],
    111 => ['name' => 'Piekary Śląskie'],
    112 => ['name' => 'Cieszyn'],
    113 => ['name' => 'Świecie'],
    114 => ['name' => 'Krosno Odrzańskie'],
    115 => ['name' => 'Sandomierz'],
    116 => ['name' => 'Mrągowo'],
    117 => ['name' => 'Augustów'],
    118 => ['name' => 'Giżycko'],
    119 => ['name' => 'Wieliczka'],
    120 => ['name' => 'Łańcut'],
    121 => ['name' => 'Poland Locality 1'],
    122 => ['name' => 'Poland Locality 2'],
    123 => ['name' => 'Poland Locality 3'],
    124 => ['name' => 'Poland Locality 4'],
    125 => ['name' => 'Poland Locality 5'],
    126 => ['name' => 'Poland Locality 6'],
    127 => ['name' => 'Poland Locality 7'],
    128 => ['name' => 'Poland Locality 8'],
    129 => ['name' => 'Poland Locality 9'],
    130 => ['name' => 'Poland Locality 10'],
    131 => ['name' => 'Poland Locality 11'],
    132 => ['name' => 'Poland Locality 12'],
    133 => ['name' => 'Poland Locality 13'],
    134 => ['name' => 'Poland Locality 14'],
    135 => ['name' => 'Poland Locality 15'],
    136 => ['name' => 'Poland Locality 16'],
    137 => ['name' => 'Poland Locality 17'],
    138 => ['name' => 'Poland Locality 18'],
    139 => ['name' => 'Poland Locality 19'],
    140 => ['name' => 'Poland Locality 20'],
    141 => ['name' => 'Poland Locality 21'],
    142 => ['name' => 'Poland Locality 22'],
    143 => ['name' => 'Poland Locality 23'],
    144 => ['name' => 'Poland Locality 24'],
    145 => ['name' => 'Poland Locality 25'],
    146 => ['name' => 'Poland Locality 26'],
    147 => ['name' => 'Poland Locality 27'],
    148 => ['name' => 'Poland Locality 28'],
    149 => ['name' => 'Poland Locality 29'],
    150 => ['name' => 'Poland Locality 30'],
    151 => ['name' => 'Poland Locality 31'],
    152 => ['name' => 'Poland Locality 32'],
    153 => ['name' => 'Poland Locality 33'],
    154 => ['name' => 'Poland Locality 34'],
    155 => ['name' => 'Poland Locality 35'],
    156 => ['name' => 'Poland Locality 36'],
    157 => ['name' => 'Poland Locality 37'],
    158 => ['name' => 'Poland Locality 38'],
    159 => ['name' => 'Poland Locality 39'],
    160 => ['name' => 'Poland Locality 40'],
    161 => ['name' => 'Poland Locality 41'],
    162 => ['name' => 'Poland Locality 42'],
    163 => ['name' => 'Poland Locality 43'],
    164 => ['name' => 'Poland Locality 44'],
    165 => ['name' => 'Poland Locality 45'],
    166 => ['name' => 'Poland Locality 46'],
    167 => ['name' => 'Poland Locality 47'],
    168 => ['name' => 'Poland Locality 48'],
    169 => ['name' => 'Poland Locality 49'],
    170 => ['name' => 'Poland Locality 50'],
    171 => ['name' => 'Poland Locality 51'],
    172 => ['name' => 'Poland Locality 52'],
    173 => ['name' => 'Poland Locality 53'],
    174 => ['name' => 'Poland Locality 54'],
    175 => ['name' => 'Poland Locality 55'],
    176 => ['name' => 'Poland Locality 56'],
    177 => ['name' => 'Poland Locality 57'],
    178 => ['name' => 'Poland Locality 58'],
    179 => ['name' => 'Poland Locality 59'],
    180 => ['name' => 'Poland Locality 60'],
    181 => ['name' => 'Poland Locality 61'],
    182 => ['name' => 'Poland Locality 62'],
    183 => ['name' => 'Poland Locality 63'],
    184 => ['name' => 'Poland Locality 64'],
    185 => ['name' => 'Poland Locality 65'],
    186 => ['name' => 'Poland Locality 66'],
    187 => ['name' => 'Poland Locality 67'],
    188 => ['name' => 'Poland Locality 68'],
    189 => ['name' => 'Poland Locality 69'],
    190 => ['name' => 'Poland Locality 70'],
    191 => ['name' => 'Poland Locality 71'],
    192 => ['name' => 'Poland Locality 72'],
    193 => ['name' => 'Poland Locality 73'],
    194 => ['name' => 'Poland Locality 74'],
    195 => ['name' => 'Poland Locality 75'],
    196 => ['name' => 'Poland Locality 76'],
    197 => ['name' => 'Poland Locality 77'],
    198 => ['name' => 'Poland Locality 78'],
    199 => ['name' => 'Poland Locality 79'],
    200 => ['name' => 'Poland Locality 80'],
    201 => ['name' => 'Poland Locality 81'],
    202 => ['name' => 'Poland Locality 82'],
    203 => ['name' => 'Poland Locality 83'],
    204 => ['name' => 'Poland Locality 84'],
    205 => ['name' => 'Poland Locality 85'],
    206 => ['name' => 'Poland Locality 86'],
    207 => ['name' => 'Poland Locality 87'],
    208 => ['name' => 'Poland Locality 88'],
    209 => ['name' => 'Poland Locality 89'],
    210 => ['name' => 'Poland Locality 90'],
    211 => ['name' => 'Poland Locality 91'],
    212 => ['name' => 'Poland Locality 92'],
    213 => ['name' => 'Poland Locality 93'],
    214 => ['name' => 'Poland Locality 94'],
    215 => ['name' => 'Poland Locality 95'],
    216 => ['name' => 'Poland Locality 96'],
    217 => ['name' => 'Poland Locality 97'],
    218 => ['name' => 'Poland Locality 98'],
    219 => ['name' => 'Poland Locality 99'],
    220 => ['name' => 'Poland Locality 100'],
    221 => ['name' => 'Poland Locality 101'],
    222 => ['name' => 'Poland Locality 102'],
    223 => ['name' => 'Poland Locality 103'],
    224 => ['name' => 'Poland Locality 104'],
    225 => ['name' => 'Poland Locality 105'],
    226 => ['name' => 'Poland Locality 106'],
    227 => ['name' => 'Poland Locality 107'],
    228 => ['name' => 'Poland Locality 108'],
    229 => ['name' => 'Poland Locality 109'],
    230 => ['name' => 'Poland Locality 110'],
    231 => ['name' => 'Poland Locality 111'],
    232 => ['name' => 'Poland Locality 112'],
    233 => ['name' => 'Poland Locality 113'],
    234 => ['name' => 'Poland Locality 114'],
    235 => ['name' => 'Poland Locality 115'],
    236 => ['name' => 'Poland Locality 116'],
    237 => ['name' => 'Poland Locality 117'],
    238 => ['name' => 'Poland Locality 118'],
    239 => ['name' => 'Poland Locality 119'],
    240 => ['name' => 'Poland Locality 120'],
    241 => ['name' => 'Poland Locality 121'],
    242 => ['name' => 'Poland Locality 122'],
    243 => ['name' => 'Poland Locality 123'],
    244 => ['name' => 'Poland Locality 124'],
    245 => ['name' => 'Poland Locality 125'],
    246 => ['name' => 'Poland Locality 126'],
    247 => ['name' => 'Poland Locality 127'],
    248 => ['name' => 'Poland Locality 128'],
    249 => ['name' => 'Poland Locality 129'],
    250 => ['name' => 'Poland Locality 130'],
    251 => ['name' => 'Poland Locality 131'],
    252 => ['name' => 'Poland Locality 132'],
    253 => ['name' => 'Poland Locality 133'],
    254 => ['name' => 'Poland Locality 134'],
    255 => ['name' => 'Poland Locality 135'],
    256 => ['name' => 'Poland Locality 136'],
    257 => ['name' => 'Poland Locality 137'],
    258 => ['name' => 'Poland Locality 138'],
    259 => ['name' => 'Poland Locality 139'],
    260 => ['name' => 'Poland Locality 140'],
    261 => ['name' => 'Poland Locality 1 (2)'],
    262 => ['name' => 'Poland Locality 2 (2)'],
    263 => ['name' => 'Poland Locality 3 (2)'],
    264 => ['name' => 'Poland Locality 4 (2)'],
    265 => ['name' => 'Poland Locality 5 (2)'],
    266 => ['name' => 'Poland Locality 6 (2)'],
    267 => ['name' => 'Poland Locality 7 (2)'],
    268 => ['name' => 'Poland Locality 8 (2)'],
    269 => ['name' => 'Poland Locality 9 (2)'],
    270 => ['name' => 'Poland Locality 10 (2)'],
    271 => ['name' => 'Poland Locality 11 (2)'],
    272 => ['name' => 'Poland Locality 12 (2)'],
    273 => ['name' => 'Poland Locality 13 (2)'],
    274 => ['name' => 'Poland Locality 14 (2)'],
    275 => ['name' => 'Poland Locality 15 (2)'],
    276 => ['name' => 'Poland Locality 16 (2)'],
    277 => ['name' => 'Poland Locality 17 (2)'],
    278 => ['name' => 'Poland Locality 18 (2)'],
    279 => ['name' => 'Poland Locality 19 (2)'],
    280 => ['name' => 'Poland Locality 20 (2)'],
    281 => ['name' => 'Poland Locality 21 (2)'],
    282 => ['name' => 'Poland Locality 22 (2)'],
    283 => ['name' => 'Poland Locality 23 (2)'],
    284 => ['name' => 'Poland Locality 24 (2)'],
    285 => ['name' => 'Poland Locality 25 (2)'],
    286 => ['name' => 'Poland Locality 26 (2)'],
    287 => ['name' => 'Poland Locality 27 (2)'],
    288 => ['name' => 'Poland Locality 28 (2)'],
    289 => ['name' => 'Poland Locality 29 (2)'],
    290 => ['name' => 'Poland Locality 30 (2)'],
    291 => ['name' => 'Poland Locality 31 (2)'],
    292 => ['name' => 'Poland Locality 32 (2)'],
    293 => ['name' => 'Poland Locality 33 (2)'],
    294 => ['name' => 'Poland Locality 34 (2)'],
    295 => ['name' => 'Poland Locality 35 (2)'],
    296 => ['name' => 'Poland Locality 36 (2)'],
    297 => ['name' => 'Poland Locality 37 (2)'],
    298 => ['name' => 'Poland Locality 38 (2)'],
    299 => ['name' => 'Poland Locality 39 (2)'],
    300 => ['name' => 'Poland Locality 40 (2)'],
    301 => ['name' => 'Poland Locality 41 (2)'],
    302 => ['name' => 'Poland Locality 42 (2)'],
    303 => ['name' => 'Poland Locality 43 (2)'],
    304 => ['name' => 'Poland Locality 44 (2)'],
    305 => ['name' => 'Poland Locality 45 (2)'],
    306 => ['name' => 'Poland Locality 46 (2)'],
    307 => ['name' => 'Poland Locality 47 (2)'],
    308 => ['name' => 'Poland Locality 48 (2)'],
    309 => ['name' => 'Poland Locality 49 (2)'],
    310 => ['name' => 'Poland Locality 50 (2)'],
    311 => ['name' => 'Poland Locality 51 (2)'],
    312 => ['name' => 'Poland Locality 52 (2)'],
    313 => ['name' => 'Poland Locality 53 (2)'],
    314 => ['name' => 'Poland Locality 54 (2)'],
    315 => ['name' => 'Poland Locality 55 (2)'],
    316 => ['name' => 'Poland Locality 56 (2)'],
    317 => ['name' => 'Poland Locality 57 (2)'],
    318 => ['name' => 'Poland Locality 58 (2)'],
    319 => ['name' => 'Poland Locality 59 (2)'],
    320 => ['name' => 'Poland Locality 60 (2)']
];