<?php

return [
    1  => ['name' => 'Warszawa'],
    2  => ['name' => 'Kraków'],
    3  => ['name' => 'Łódź'],
    4  => ['name' => 'Wrocław'],
    5  => ['name' => 'Poznań'],
    6  => ['name' => 'Gdańsk'],
    7  => ['name' => 'Szczecin'],
    8  => ['name' => 'Bydgoszcz'],
    9  => ['name' => 'Lublin'],
    10 => ['name' => 'Białystok'],
    11 => ['name' => 'Katowice'],
    12 => ['name' => 'Gdynia'],
    13 => ['name' => 'Częstochowa'],
    14 => ['name' => 'Radom'],
    15 => ['name' => 'Toruń'],
    16 => ['name' => 'Kielce'],
    17 => ['name' => 'Rzeszów'],
    18 => ['name' => 'Gliwice'],
    19 => ['name' => 'Zabrze'],
    20 => ['name' => 'Bytom'],
    21 => ['name' => 'Bielsko-Biała'],
    22 => ['name' => 'Olsztyn'],
    23 => ['name' => 'Rybnik'],
    24 => ['name' => 'Tychy'],
    25 => ['name' => 'Opole'],
    26 => ['name' => 'Elbląg'],
    27 => ['name' => 'Płock'],
    28 => ['name' => 'Wałbrzych'],
    29 => ['name' => 'Zielona Góra'],
    30 => ['name' => 'Włocławek'],
    31 => ['name' => 'Tarnów'],
    32 => ['name' => 'Chorzów'],
    33 => ['name' => 'Koszalin'],
    34 => ['name' => 'Legnica'],
    35 => ['name' => 'Grudziądz'],
    36 => ['name' => 'Jaworzno'],
    37 => ['name' => 'Słupsk'],
    38 => ['name' => 'Jastrzębie-Zdrój'],
    39 => ['name' => 'Nowy Sącz'],
    40 => ['name' => 'Jelenia Góra'],
    41 => ['name' => 'Konin'],
    42 => ['name' => 'Piła'],
    43 => ['name' => 'Ostrowiec Świętokrzyski'],
    44 => ['name' => 'Piotrków Trybunalski'],
    45 => ['name' => 'Lubin'],
    46 => ['name' => 'Gorzów Wielkopolski'],
    47 => ['name' => 'Siemianowice Śląskie'],
    48 => ['name' => 'Pabianice'],
    49 => ['name' => 'Chełm'],
    50 => ['name' => 'Przemyśl'],
    51 => ['name' => 'Stalowa Wola'],
    52 => ['name' => 'Tarnowskie Góry'],
    53 => ['name' => 'Tomaszów Mazowiecki'],
    54 => ['name' => 'Zamość'],
    55 => ['name' => 'Leszno'],
    56 => ['name' => 'Łomża'],
    57 => ['name' => 'Bełchatów'],
    58 => ['name' => 'Świdnica'],
    59 => ['name' => 'Nowy Targ'],
    60 => ['name' => 'Mysłowice'],
    61 => ['name' => 'Inowrocław'],
    62 => ['name' => 'Ostrów Wielkopolski'],
    63 => ['name' => 'Gniezno'],
    64 => ['name' => 'Suwałki'],
    65 => ['name' => 'Stargard'],
    66 => ['name' => 'Kutno'],
    67 => ['name' => 'Siedlce'],
    68 => ['name' => 'Skierniewice'],
    69 => ['name' => 'Żory'],
    70 => ['name' => 'Starachowice'],
    71 => ['name' => 'Ełk'],
    72 => ['name' => 'Mielec'],
    73 => ['name' => 'Legionowo'],
    74 => ['name' => 'Ostrołęka'],
    75 => ['name' => 'Świnoujście'],
    76 => ['name' => 'Krosno'],
    77 => ['name' => 'Łowicz'],
    78 => ['name' => 'Skarżysko-Kamienna'],
    79 => ['name' => 'Rumia'],
    80 => ['name' => 'Zgierz'],
    81 => ['name' => 'Knurów'],
    82 => ['name' => 'Kołobrzeg'],
    83 => ['name' => 'Ciechanów'],
    84 => ['name' => 'Nysa'],
    85 => ['name' => 'Bochnia'],
    86 => ['name' => 'Świętochłowice'],
    87 => ['name' => 'Puławy'],
    88 => ['name' => 'Sopot'],
    89 => ['name' => 'Brodnica'],
    90 => ['name' => 'Nowa Sól'],
    91 => ['name' => 'Zakopane'],
    92 => ['name' => 'Żywiec'],
    93 => ['name' => 'Sanok'],
    94 => ['name' => 'Malbork'],
    95 => ['name' => 'Biała Podlaska'],
    96 => ['name' => 'Kędzierzyn-Koźle'],
    97 => ['name' => 'Jarosław'],
    98 => ['name' => 'Świdnik'],
    99 => ['name' => 'Oława'],
    100 => ['name' => 'Police'],
    101 => ['name' => 'Turek'],
    102 => ['name' => 'Kłodzko'],
    103 => ['name' => 'Lębork'],
    104 => ['name' => 'Nowy Dwór Mazowiecki'],
    105 => ['name' => 'Kraśnik'],
    106 => ['name' => 'Brzeg'],
    107 => ['name' => 'Wodzisław Śląski'],
    108 => ['name' => 'Chojnice'],
    109 => ['name' => 'Mikołów'],
    110 => ['name' => 'Oleśnica'],
    111 => ['name' => 'Piekary Śląskie'],
    112 => ['name' => 'Cieszyn'],
    113 => ['name' => 'Świecie'],
    114 => ['name' => 'Krosno Odrzańskie'],
    115 => ['name' => 'Sandomierz'],
    116 => ['name' => 'Mrągowo'],
    117 => ['name' => 'Augustów'],
    118 => ['name' => 'Giżycko'],
    119 => ['name' => 'Wieliczka'],
    120 => ['name' => 'Łańcut'],
];
