<?php

return [
    1 => ['name' => 'Lisbon'],
    2 => ['name' => 'Porto'],
    3 => ['name' => 'Amadora'],
    4 => ['name' => 'Braga'],
    5 => ['name' => 'Coimbra'],
    6 => ['name' => 'Funchal'],
    7 => ['name' => 'Setúbal'],
    8 => ['name' => 'Almada'],
    9 => ['name' => 'Agualva-Cacém'],
    10 => ['name' => 'Queluz'],
    11 => ['name' => 'Faro'],
    12 => ['name' => 'Vila Nova de Gaia'],
    13 => ['name' => 'Gondomar'],
    14 => ['name' => 'Guimarães'],
    15 => ['name' => 'Odivelas'],
    16 => ['name' => 'Matosinhos'],
    17 => ['name' => 'Amora'],
    18 => ['name' => 'Barreiro'],
    19 => ['name' => 'Évora'],
    20 => ['name' => 'Portimão'],
    21 => ['name' => 'Aveiro'],
    22 => ['name' => 'Leiria'],
    23 => ['name' => 'Ponta Delgada'],
    24 => ['name' => 'Fafe'],
    25 => ['name' => 'Viseu'],
    26 => ['name' => 'Covilhã'],
    27 => ['name' => 'Castelo Branco'],
    28 => ['name' => 'Santarém'],
    29 => ['name' => 'Beja'],
    30 => ['name' => 'Portalegre'],
    31 => ['name' => 'Lagos'],
    32 => ['name' => 'Tavira'],
    33 => ['name' => 'Olhão'],
    34 => ['name' => 'Loulé'],
    35 => ['name' => 'Silves'],
    36 => ['name' => 'Albufeira'],
    37 => ['name' => 'Faro'],
    38 => ['name' => 'Lamego'],
    39 => ['name' => 'Chaves'],
    40 => ['name' => 'Vila Real'],
    41 => ['name' => 'Bragança'],
    42 => ['name' => 'Figueira da Foz'],
    43 => ['name' => 'Pombal'],
    44 => ['name' => 'Tomar'],
    45 => ['name' => 'Torres Vedras'],
    46 => ['name' => 'Caldas da Rainha'],
    47 => ['name' => 'Sintra'],
    48 => ['name' => 'Cascais'],
    49 => ['name' => 'Oeiras'],
    50 => ['name' => 'Loures'],
    51 => ['name' => 'Ovar'],
    52 => ['name' => 'Espinho'],
    53 => ['name' => 'Viana do Castelo'],
    54 => ['name' => 'Póvoa de Varzim'],
    55 => ['name' => 'Maia'],
    56 => ['name' => 'Vila do Conde'],
    57 => ['name' => 'Paredes'],
    58 => ['name' => 'Felgueiras'],
    59 => ['name' => 'Vizela'],
    60 => ['name' => 'Barcelos'],
     61 => ['name' => 'Portugal Locality 1'],
     62 => ['name' => 'Portugal Locality 2'],
     63 => ['name' => 'Portugal Locality 3'],
     64 => ['name' => 'Portugal Locality 4'],
     65 => ['name' => 'Portugal Locality 5'],
     66 => ['name' => 'Portugal Locality 6'],
     67 => ['name' => 'Portugal Locality 7'],
     68 => ['name' => 'Portugal Locality 8'],
     69 => ['name' => 'Portugal Locality 9'],
     70 => ['name' => 'Portugal Locality 10'],
     71 => ['name' => 'Portugal Locality 11'],
     72 => ['name' => 'Portugal Locality 12'],
     73 => ['name' => 'Portugal Locality 13'],
     74 => ['name' => 'Portugal Locality 14'],
     75 => ['name' => 'Portugal Locality 15'],
     76 => ['name' => 'Portugal Locality 16'],
     77 => ['name' => 'Portugal Locality 17'],
     78 => ['name' => 'Portugal Locality 18'],
     79 => ['name' => 'Portugal Locality 19'],
     80 => ['name' => 'Portugal Locality 20'],
     81 => ['name' => 'Portugal Locality 21'],
     82 => ['name' => 'Portugal Locality 22'],
     83 => ['name' => 'Portugal Locality 23'],
     84 => ['name' => 'Portugal Locality 24'],
     85 => ['name' => 'Portugal Locality 25'],
     86 => ['name' => 'Portugal Locality 26'],
     87 => ['name' => 'Portugal Locality 27'],
     88 => ['name' => 'Portugal Locality 28'],
     89 => ['name' => 'Portugal Locality 29'],
     90 => ['name' => 'Portugal Locality 30'],
     91 => ['name' => 'Portugal Locality 31'],
     92 => ['name' => 'Portugal Locality 32'],
     93 => ['name' => 'Portugal Locality 33'],
     94 => ['name' => 'Portugal Locality 34'],
     95 => ['name' => 'Portugal Locality 35'],
     96 => ['name' => 'Portugal Locality 36'],
     97 => ['name' => 'Portugal Locality 37'],
     98 => ['name' => 'Portugal Locality 38'],
     99 => ['name' => 'Portugal Locality 39'],
    100 => ['name' => 'Portugal Locality 40'],
    101 => ['name' => 'Portugal Locality 41'],
    102 => ['name' => 'Portugal Locality 42'],
    103 => ['name' => 'Portugal Locality 43'],
    104 => ['name' => 'Portugal Locality 44'],
    105 => ['name' => 'Portugal Locality 45'],
    106 => ['name' => 'Portugal Locality 46'],
    107 => ['name' => 'Portugal Locality 47'],
    108 => ['name' => 'Portugal Locality 48'],
    109 => ['name' => 'Portugal Locality 49'],
    110 => ['name' => 'Portugal Locality 50'],
    111 => ['name' => 'Portugal Locality 51'],
    112 => ['name' => 'Portugal Locality 52'],
    113 => ['name' => 'Portugal Locality 53'],
    114 => ['name' => 'Portugal Locality 54'],
    115 => ['name' => 'Portugal Locality 55'],
    116 => ['name' => 'Portugal Locality 56'],
    117 => ['name' => 'Portugal Locality 57'],
    118 => ['name' => 'Portugal Locality 58'],
    119 => ['name' => 'Portugal Locality 59'],
    120 => ['name' => 'Portugal Locality 60'],
    121 => ['name' => 'Portugal Locality 61'],
    122 => ['name' => 'Portugal Locality 62'],
    123 => ['name' => 'Portugal Locality 63'],
    124 => ['name' => 'Portugal Locality 64'],
    125 => ['name' => 'Portugal Locality 65'],
    126 => ['name' => 'Portugal Locality 66'],
    127 => ['name' => 'Portugal Locality 67'],
    128 => ['name' => 'Portugal Locality 68'],
    129 => ['name' => 'Portugal Locality 69'],
    130 => ['name' => 'Portugal Locality 70'],
    131 => ['name' => 'Portugal Locality 71'],
    132 => ['name' => 'Portugal Locality 72'],
    133 => ['name' => 'Portugal Locality 73'],
    134 => ['name' => 'Portugal Locality 74'],
    135 => ['name' => 'Portugal Locality 75'],
    136 => ['name' => 'Portugal Locality 76'],
    137 => ['name' => 'Portugal Locality 77'],
    138 => ['name' => 'Portugal Locality 78'],
    139 => ['name' => 'Portugal Locality 79'],
    140 => ['name' => 'Portugal Locality 80'],
    141 => ['name' => 'Portugal Locality 81'],
    142 => ['name' => 'Portugal Locality 82'],
    143 => ['name' => 'Portugal Locality 83'],
    144 => ['name' => 'Portugal Locality 84'],
    145 => ['name' => 'Portugal Locality 85'],
    146 => ['name' => 'Portugal Locality 86'],
    147 => ['name' => 'Portugal Locality 87'],
    148 => ['name' => 'Portugal Locality 88'],
    149 => ['name' => 'Portugal Locality 89'],
    150 => ['name' => 'Portugal Locality 90'],
    151 => ['name' => 'Portugal Locality 91'],
    152 => ['name' => 'Portugal Locality 92'],
    153 => ['name' => 'Portugal Locality 93'],
    154 => ['name' => 'Portugal Locality 94'],
    155 => ['name' => 'Portugal Locality 95'],
    156 => ['name' => 'Portugal Locality 96'],
    157 => ['name' => 'Portugal Locality 97'],
    158 => ['name' => 'Portugal Locality 98'],
    159 => ['name' => 'Portugal Locality 99'],
    160 => ['name' => 'Portugal Locality 100'],
    161 => ['name' => 'Portugal Locality 101'],
    162 => ['name' => 'Portugal Locality 102'],
    163 => ['name' => 'Portugal Locality 103'],
    164 => ['name' => 'Portugal Locality 104'],
    165 => ['name' => 'Portugal Locality 105'],
    166 => ['name' => 'Portugal Locality 106'],
    167 => ['name' => 'Portugal Locality 107'],
    168 => ['name' => 'Portugal Locality 108'],
    169 => ['name' => 'Portugal Locality 109'],
    170 => ['name' => 'Portugal Locality 110'],
    171 => ['name' => 'Portugal Locality 111'],
    172 => ['name' => 'Portugal Locality 112'],
    173 => ['name' => 'Portugal Locality 113'],
    174 => ['name' => 'Portugal Locality 114'],
    175 => ['name' => 'Portugal Locality 115'],
    176 => ['name' => 'Portugal Locality 116'],
    177 => ['name' => 'Portugal Locality 117'],
    178 => ['name' => 'Portugal Locality 118'],
    179 => ['name' => 'Portugal Locality 119'],
    180 => ['name' => 'Portugal Locality 120'],
    181 => ['name' => 'Portugal Locality 121'],
    182 => ['name' => 'Portugal Locality 122'],
    183 => ['name' => 'Portugal Locality 123'],
    184 => ['name' => 'Portugal Locality 124'],
    185 => ['name' => 'Portugal Locality 125'],
    186 => ['name' => 'Portugal Locality 126'],
    187 => ['name' => 'Portugal Locality 127'],
    188 => ['name' => 'Portugal Locality 128'],
    189 => ['name' => 'Portugal Locality 129'],
    190 => ['name' => 'Portugal Locality 130'],
    191 => ['name' => 'Portugal Locality 131'],
    192 => ['name' => 'Portugal Locality 132'],
    193 => ['name' => 'Portugal Locality 133'],
    194 => ['name' => 'Portugal Locality 134'],
    195 => ['name' => 'Portugal Locality 135'],
    196 => ['name' => 'Portugal Locality 136'],
    197 => ['name' => 'Portugal Locality 137'],
    198 => ['name' => 'Portugal Locality 138'],
    199 => ['name' => 'Portugal Locality 139'],
    200 => ['name' => 'Portugal Locality 140'],
    201 => ['name' => 'Portugal Locality 1 (2)'],
    202 => ['name' => 'Portugal Locality 2 (2)'],
    203 => ['name' => 'Portugal Locality 3 (2)'],
    204 => ['name' => 'Portugal Locality 4 (2)'],
    205 => ['name' => 'Portugal Locality 5 (2)'],
    206 => ['name' => 'Portugal Locality 6 (2)'],
    207 => ['name' => 'Portugal Locality 7 (2)'],
    208 => ['name' => 'Portugal Locality 8 (2)'],
    209 => ['name' => 'Portugal Locality 9 (2)'],
    210 => ['name' => 'Portugal Locality 10 (2)'],
    211 => ['name' => 'Portugal Locality 11 (2)'],
    212 => ['name' => 'Portugal Locality 12 (2)'],
    213 => ['name' => 'Portugal Locality 13 (2)'],
    214 => ['name' => 'Portugal Locality 14 (2)'],
    215 => ['name' => 'Portugal Locality 15 (2)'],
    216 => ['name' => 'Portugal Locality 16 (2)'],
    217 => ['name' => 'Portugal Locality 17 (2)'],
    218 => ['name' => 'Portugal Locality 18 (2)'],
    219 => ['name' => 'Portugal Locality 19 (2)'],
    220 => ['name' => 'Portugal Locality 20 (2)'],
    221 => ['name' => 'Portugal Locality 21 (2)'],
    222 => ['name' => 'Portugal Locality 22 (2)'],
    223 => ['name' => 'Portugal Locality 23 (2)'],
    224 => ['name' => 'Portugal Locality 24 (2)'],
    225 => ['name' => 'Portugal Locality 25 (2)'],
    226 => ['name' => 'Portugal Locality 26 (2)'],
    227 => ['name' => 'Portugal Locality 27 (2)'],
    228 => ['name' => 'Portugal Locality 28 (2)'],
    229 => ['name' => 'Portugal Locality 29 (2)'],
    230 => ['name' => 'Portugal Locality 30 (2)'],
    231 => ['name' => 'Portugal Locality 31 (2)'],
    232 => ['name' => 'Portugal Locality 32 (2)'],
    233 => ['name' => 'Portugal Locality 33 (2)'],
    234 => ['name' => 'Portugal Locality 34 (2)'],
    235 => ['name' => 'Portugal Locality 35 (2)'],
    236 => ['name' => 'Portugal Locality 36 (2)'],
    237 => ['name' => 'Portugal Locality 37 (2)'],
    238 => ['name' => 'Portugal Locality 38 (2)'],
    239 => ['name' => 'Portugal Locality 39 (2)'],
    240 => ['name' => 'Portugal Locality 40 (2)'],
    241 => ['name' => 'Portugal Locality 41 (2)'],
    242 => ['name' => 'Portugal Locality 42 (2)'],
    243 => ['name' => 'Portugal Locality 43 (2)'],
    244 => ['name' => 'Portugal Locality 44 (2)'],
    245 => ['name' => 'Portugal Locality 45 (2)'],
    246 => ['name' => 'Portugal Locality 46 (2)'],
    247 => ['name' => 'Portugal Locality 47 (2)'],
    248 => ['name' => 'Portugal Locality 48 (2)'],
    249 => ['name' => 'Portugal Locality 49 (2)'],
    250 => ['name' => 'Portugal Locality 50 (2)'],
    251 => ['name' => 'Portugal Locality 51 (2)'],
    252 => ['name' => 'Portugal Locality 52 (2)'],
    253 => ['name' => 'Portugal Locality 53 (2)'],
    254 => ['name' => 'Portugal Locality 54 (2)'],
    255 => ['name' => 'Portugal Locality 55 (2)'],
    256 => ['name' => 'Portugal Locality 56 (2)'],
    257 => ['name' => 'Portugal Locality 57 (2)'],
    258 => ['name' => 'Portugal Locality 58 (2)'],
    259 => ['name' => 'Portugal Locality 59 (2)'],
    260 => ['name' => 'Portugal Locality 60 (2)']
];