<?php

return [
    1 => ['name' => 'Ljubljana'],
    2 => ['name' => 'Maribor'],
    3 => ['name' => 'Celje'],
    4 => ['name' => 'Kranj'],
    5 => ['name' => 'Velenje'],
    6 => ['name' => 'Koper'],
    7 => ['name' => 'Novo Mesto'],
    8 => ['name' => 'Ptuj'],
    9 => ['name' => 'Trbovlje'],
    10 => ['name' => 'Kamnik'],
    11 => ['name' => 'Jesenice'],
    12 => ['name' => 'Nova Gorica'],
    13 => ['name' => 'Domžale'],
    14 => ['name' => 'Škofja Loka'],
    15 => ['name' => 'Murska Sobota'],
    16 => ['name' => 'Izola'],
    17 => ['name' => 'Kočevje'],
    18 => ['name' => 'Postojna'],
    19 => ['name' => 'Logatec'],
    20 => ['name' => 'Slovenj Gradec'],
    21 => ['name' => 'Ravne na Koroškem'],
    22 => ['name' => 'Vrhnika'],
    23 => ['name' => 'Krško'],
    24 => ['name' => 'Zagorje ob Savi'],
    25 => ['name' => 'Ajdovščina'],
    26 => ['name' => 'Brežice'],
    27 => ['name' => 'Črnomelj'],
    28 => ['name' => 'Dravograd'],
    29 => ['name' => 'Gornja Radgona'],
    30 => ['name' => 'Grosuplje'],
    31 => ['name' => 'Hrastnik'],
    32 => ['name' => 'Idrija'],
    33 => ['name' => 'Ilirska Bistrica'],
    34 => ['name' => 'Lendava'],
    35 => ['name' => 'Litija'],
    36 => ['name' => 'Ljubljana'],
    37 => ['name' => 'Ljutomer'],
    38 => ['name' => 'Metlika'],
    39 => ['name' => 'Mežica'],
    40 => ['name' => 'Mozirje'],
    41 => ['name' => 'Piran'],
    42 => ['name' => 'Pivka'],
    43 => ['name' => 'Prevalje'],
    44 => ['name' => 'Radlje ob Dravi'],
    45 => ['name' => 'Ravne'],
    46 => ['name' => 'Ribnica'],
    47 => ['name' => 'Rogatec'],
    48 => ['name' => 'Ruše'],
    49 => ['name' => 'Sevnica'],
    50 => ['name' => 'Sežana'],
    51 => ['name' => 'Slovenska Bistrica'],
    52 => ['name' => 'Slovenske Konjice'],
    53 => ['name' => 'Šentjur'],
    54 => ['name' => 'Šmarje pri Jelšah'],
    55 => ['name' => 'Tolmin'],
    56 => ['name' => 'Tržič'],
    57 => ['name' => 'Turnišče'],
    58 => ['name' => 'Vipava'],
    59 => ['name' => 'Žalec'],
    60 => ['name' => 'Železniki'],
     61 => ['name' => 'Slovenia Locality 1'],
     62 => ['name' => 'Slovenia Locality 2'],
     63 => ['name' => 'Slovenia Locality 3'],
     64 => ['name' => 'Slovenia Locality 4'],
     65 => ['name' => 'Slovenia Locality 5'],
     66 => ['name' => 'Slovenia Locality 6'],
     67 => ['name' => 'Slovenia Locality 7'],
     68 => ['name' => 'Slovenia Locality 8'],
     69 => ['name' => 'Slovenia Locality 9'],
     70 => ['name' => 'Slovenia Locality 10'],
     71 => ['name' => 'Slovenia Locality 11'],
     72 => ['name' => 'Slovenia Locality 12'],
     73 => ['name' => 'Slovenia Locality 13'],
     74 => ['name' => 'Slovenia Locality 14'],
     75 => ['name' => 'Slovenia Locality 15'],
     76 => ['name' => 'Slovenia Locality 16'],
     77 => ['name' => 'Slovenia Locality 17'],
     78 => ['name' => 'Slovenia Locality 18'],
     79 => ['name' => 'Slovenia Locality 19'],
     80 => ['name' => 'Slovenia Locality 20'],
     81 => ['name' => 'Slovenia Locality 21'],
     82 => ['name' => 'Slovenia Locality 22'],
     83 => ['name' => 'Slovenia Locality 23'],
     84 => ['name' => 'Slovenia Locality 24'],
     85 => ['name' => 'Slovenia Locality 25'],
     86 => ['name' => 'Slovenia Locality 26'],
     87 => ['name' => 'Slovenia Locality 27'],
     88 => ['name' => 'Slovenia Locality 28'],
     89 => ['name' => 'Slovenia Locality 29'],
     90 => ['name' => 'Slovenia Locality 30'],
     91 => ['name' => 'Slovenia Locality 31'],
     92 => ['name' => 'Slovenia Locality 32'],
     93 => ['name' => 'Slovenia Locality 33'],
     94 => ['name' => 'Slovenia Locality 34'],
     95 => ['name' => 'Slovenia Locality 35'],
     96 => ['name' => 'Slovenia Locality 36'],
     97 => ['name' => 'Slovenia Locality 37'],
     98 => ['name' => 'Slovenia Locality 38'],
     99 => ['name' => 'Slovenia Locality 39'],
    100 => ['name' => 'Slovenia Locality 40'],
    101 => ['name' => 'Slovenia Locality 41'],
    102 => ['name' => 'Slovenia Locality 42'],
    103 => ['name' => 'Slovenia Locality 43'],
    104 => ['name' => 'Slovenia Locality 44'],
    105 => ['name' => 'Slovenia Locality 45'],
    106 => ['name' => 'Slovenia Locality 46'],
    107 => ['name' => 'Slovenia Locality 47'],
    108 => ['name' => 'Slovenia Locality 48'],
    109 => ['name' => 'Slovenia Locality 49'],
    110 => ['name' => 'Slovenia Locality 50'],
    111 => ['name' => 'Slovenia Locality 51'],
    112 => ['name' => 'Slovenia Locality 52'],
    113 => ['name' => 'Slovenia Locality 53'],
    114 => ['name' => 'Slovenia Locality 54'],
    115 => ['name' => 'Slovenia Locality 55'],
    116 => ['name' => 'Slovenia Locality 56'],
    117 => ['name' => 'Slovenia Locality 57'],
    118 => ['name' => 'Slovenia Locality 58'],
    119 => ['name' => 'Slovenia Locality 59'],
    120 => ['name' => 'Slovenia Locality 60'],
    121 => ['name' => 'Slovenia Locality 61'],
    122 => ['name' => 'Slovenia Locality 62'],
    123 => ['name' => 'Slovenia Locality 63'],
    124 => ['name' => 'Slovenia Locality 64'],
    125 => ['name' => 'Slovenia Locality 65'],
    126 => ['name' => 'Slovenia Locality 66'],
    127 => ['name' => 'Slovenia Locality 67'],
    128 => ['name' => 'Slovenia Locality 68'],
    129 => ['name' => 'Slovenia Locality 69'],
    130 => ['name' => 'Slovenia Locality 70'],
    131 => ['name' => 'Slovenia Locality 71'],
    132 => ['name' => 'Slovenia Locality 72'],
    133 => ['name' => 'Slovenia Locality 73'],
    134 => ['name' => 'Slovenia Locality 74'],
    135 => ['name' => 'Slovenia Locality 75'],
    136 => ['name' => 'Slovenia Locality 76'],
    137 => ['name' => 'Slovenia Locality 77'],
    138 => ['name' => 'Slovenia Locality 78'],
    139 => ['name' => 'Slovenia Locality 79'],
    140 => ['name' => 'Slovenia Locality 80'],
    141 => ['name' => 'Slovenia Locality 81'],
    142 => ['name' => 'Slovenia Locality 82'],
    143 => ['name' => 'Slovenia Locality 83'],
    144 => ['name' => 'Slovenia Locality 84'],
    145 => ['name' => 'Slovenia Locality 85'],
    146 => ['name' => 'Slovenia Locality 86'],
    147 => ['name' => 'Slovenia Locality 87'],
    148 => ['name' => 'Slovenia Locality 88'],
    149 => ['name' => 'Slovenia Locality 89'],
    150 => ['name' => 'Slovenia Locality 90'],
    151 => ['name' => 'Slovenia Locality 91'],
    152 => ['name' => 'Slovenia Locality 92'],
    153 => ['name' => 'Slovenia Locality 93'],
    154 => ['name' => 'Slovenia Locality 94'],
    155 => ['name' => 'Slovenia Locality 95'],
    156 => ['name' => 'Slovenia Locality 96'],
    157 => ['name' => 'Slovenia Locality 97'],
    158 => ['name' => 'Slovenia Locality 98'],
    159 => ['name' => 'Slovenia Locality 99'],
    160 => ['name' => 'Slovenia Locality 100'],
    161 => ['name' => 'Slovenia Locality 101'],
    162 => ['name' => 'Slovenia Locality 102'],
    163 => ['name' => 'Slovenia Locality 103'],
    164 => ['name' => 'Slovenia Locality 104'],
    165 => ['name' => 'Slovenia Locality 105'],
    166 => ['name' => 'Slovenia Locality 106'],
    167 => ['name' => 'Slovenia Locality 107'],
    168 => ['name' => 'Slovenia Locality 108'],
    169 => ['name' => 'Slovenia Locality 109'],
    170 => ['name' => 'Slovenia Locality 110'],
    171 => ['name' => 'Slovenia Locality 111'],
    172 => ['name' => 'Slovenia Locality 112'],
    173 => ['name' => 'Slovenia Locality 113'],
    174 => ['name' => 'Slovenia Locality 114'],
    175 => ['name' => 'Slovenia Locality 115'],
    176 => ['name' => 'Slovenia Locality 116'],
    177 => ['name' => 'Slovenia Locality 117'],
    178 => ['name' => 'Slovenia Locality 118'],
    179 => ['name' => 'Slovenia Locality 119'],
    180 => ['name' => 'Slovenia Locality 120'],
    181 => ['name' => 'Slovenia Locality 121'],
    182 => ['name' => 'Slovenia Locality 122'],
    183 => ['name' => 'Slovenia Locality 123'],
    184 => ['name' => 'Slovenia Locality 124'],
    185 => ['name' => 'Slovenia Locality 125'],
    186 => ['name' => 'Slovenia Locality 126'],
    187 => ['name' => 'Slovenia Locality 127'],
    188 => ['name' => 'Slovenia Locality 128'],
    189 => ['name' => 'Slovenia Locality 129'],
    190 => ['name' => 'Slovenia Locality 130'],
    191 => ['name' => 'Slovenia Locality 131'],
    192 => ['name' => 'Slovenia Locality 132'],
    193 => ['name' => 'Slovenia Locality 133'],
    194 => ['name' => 'Slovenia Locality 134'],
    195 => ['name' => 'Slovenia Locality 135'],
    196 => ['name' => 'Slovenia Locality 136'],
    197 => ['name' => 'Slovenia Locality 137'],
    198 => ['name' => 'Slovenia Locality 138'],
    199 => ['name' => 'Slovenia Locality 139'],
    200 => ['name' => 'Slovenia Locality 140'],
    201 => ['name' => 'Slovenia Locality 1 (2)'],
    202 => ['name' => 'Slovenia Locality 2 (2)'],
    203 => ['name' => 'Slovenia Locality 3 (2)'],
    204 => ['name' => 'Slovenia Locality 4 (2)'],
    205 => ['name' => 'Slovenia Locality 5 (2)'],
    206 => ['name' => 'Slovenia Locality 6 (2)'],
    207 => ['name' => 'Slovenia Locality 7 (2)'],
    208 => ['name' => 'Slovenia Locality 8 (2)'],
    209 => ['name' => 'Slovenia Locality 9 (2)'],
    210 => ['name' => 'Slovenia Locality 10 (2)'],
    211 => ['name' => 'Slovenia Locality 11 (2)'],
    212 => ['name' => 'Slovenia Locality 12 (2)'],
    213 => ['name' => 'Slovenia Locality 13 (2)'],
    214 => ['name' => 'Slovenia Locality 14 (2)'],
    215 => ['name' => 'Slovenia Locality 15 (2)'],
    216 => ['name' => 'Slovenia Locality 16 (2)'],
    217 => ['name' => 'Slovenia Locality 17 (2)'],
    218 => ['name' => 'Slovenia Locality 18 (2)'],
    219 => ['name' => 'Slovenia Locality 19 (2)'],
    220 => ['name' => 'Slovenia Locality 20 (2)'],
    221 => ['name' => 'Slovenia Locality 21 (2)'],
    222 => ['name' => 'Slovenia Locality 22 (2)'],
    223 => ['name' => 'Slovenia Locality 23 (2)'],
    224 => ['name' => 'Slovenia Locality 24 (2)'],
    225 => ['name' => 'Slovenia Locality 25 (2)'],
    226 => ['name' => 'Slovenia Locality 26 (2)'],
    227 => ['name' => 'Slovenia Locality 27 (2)'],
    228 => ['name' => 'Slovenia Locality 28 (2)'],
    229 => ['name' => 'Slovenia Locality 29 (2)'],
    230 => ['name' => 'Slovenia Locality 30 (2)'],
    231 => ['name' => 'Slovenia Locality 31 (2)'],
    232 => ['name' => 'Slovenia Locality 32 (2)'],
    233 => ['name' => 'Slovenia Locality 33 (2)'],
    234 => ['name' => 'Slovenia Locality 34 (2)'],
    235 => ['name' => 'Slovenia Locality 35 (2)'],
    236 => ['name' => 'Slovenia Locality 36 (2)'],
    237 => ['name' => 'Slovenia Locality 37 (2)'],
    238 => ['name' => 'Slovenia Locality 38 (2)'],
    239 => ['name' => 'Slovenia Locality 39 (2)'],
    240 => ['name' => 'Slovenia Locality 40 (2)'],
    241 => ['name' => 'Slovenia Locality 41 (2)'],
    242 => ['name' => 'Slovenia Locality 42 (2)'],
    243 => ['name' => 'Slovenia Locality 43 (2)'],
    244 => ['name' => 'Slovenia Locality 44 (2)'],
    245 => ['name' => 'Slovenia Locality 45 (2)'],
    246 => ['name' => 'Slovenia Locality 46 (2)'],
    247 => ['name' => 'Slovenia Locality 47 (2)'],
    248 => ['name' => 'Slovenia Locality 48 (2)'],
    249 => ['name' => 'Slovenia Locality 49 (2)'],
    250 => ['name' => 'Slovenia Locality 50 (2)'],
    251 => ['name' => 'Slovenia Locality 51 (2)'],
    252 => ['name' => 'Slovenia Locality 52 (2)'],
    253 => ['name' => 'Slovenia Locality 53 (2)'],
    254 => ['name' => 'Slovenia Locality 54 (2)'],
    255 => ['name' => 'Slovenia Locality 55 (2)'],
    256 => ['name' => 'Slovenia Locality 56 (2)'],
    257 => ['name' => 'Slovenia Locality 57 (2)'],
    258 => ['name' => 'Slovenia Locality 58 (2)'],
    259 => ['name' => 'Slovenia Locality 59 (2)'],
    260 => ['name' => 'Slovenia Locality 60 (2)']
];