<?php

return [
    1 => ['name' => 'Bratislava', 'region' => 'Bratislavský kraj'],
    2 => ['name' => 'Košice', 'region' => 'Košický kraj'],
    3 => ['name' => 'Prešov', 'region' => 'Prešovský kraj'],
    4 => ['name' => 'Žilina', 'region' => 'Žilinský kraj'],
    5 => ['name' => 'Nitra', 'region' => 'Nitriansky kraj'],
    6 => ['name' => 'Banská Bystrica', 'region' => 'Banskobystrický kraj'],
    7 => ['name' => 'Trnava', 'region' => 'Trnavský kraj'],
    8 => ['name' => 'Martin', 'region' => 'Žilinský kraj'],
    9 => ['name' => 'Trenčín', 'region' => 'Trenčiansky kraj'],
    10 => ['name' => 'Poprad', 'region' => 'Prešovský kraj'],
    11 => ['name' => 'Prievidza'],
    12 => ['name' => 'Zvolen'],
    13 => ['name' => 'Považská Bystrica'],
    14 => ['name' => 'Nové Zámky'],
    15 => ['name' => 'Michalovce'],
    16 => ['name' => 'Spišská Nová Ves'],
    17 => ['name' => 'Komárno'],
    18 => ['name' => 'Humenné'],
    19 => ['name' => 'Levice'],
    20 => ['name' => 'Bardejov'],
    21 => ['name' => 'Liptovský Mikuláš'],
    22 => ['name' => 'Lučenec'],
     23 => ['name' => 'Piešťany'],
     24 => ['name' => 'Ružomberok'],
     25 => ['name' => 'Topoľčany'],
     26 => ['name' => 'Trebišov'],
     27 => ['name' => 'Čadca'],
     28 => ['name' => 'Rimavská Sobota'],
     29 => ['name' => 'Dunajská Streda'],
     30 => ['name' => 'Pezinok'],
     31 => ['name' => 'Šaľa'],
     32 => ['name' => 'Partizánske'],
     33 => ['name' => 'Vranov nad Topľou'],
     34 => ['name' => 'Hlohovec'],
     35 => ['name' => 'Brezno'],
     36 => ['name' => 'Snina'],
     37 => ['name' => 'Senica'],
     38 => ['name' => 'Nové Mesto nad Váhom'],
     39 => ['name' => 'Kežmarok'],
     40 => ['name' => 'Rožňava'],
     41 => ['name' => 'Dolný Kubín'],
     42 => ['name' => 'Bánovce nad Bebravou'],
     43 => ['name' => 'Púchov'],
     44 => ['name' => 'Malacky'],
     45 => ['name' => 'Handlová'],
     46 => ['name' => 'Kysucké Nové Mesto'],
     47 => ['name' => 'Galanta'],
     48 => ['name' => 'Stará Ľubovňa'],
     49 => ['name' => 'Žiar nad Hronom'],
     50 => ['name' => 'Skalica'],
     51 => ['name' => 'Senec'],
     52 => ['name' => 'Stropkov'],
     53 => ['name' => 'Šamorín'],
     54 => ['name' => 'Stará Turá'],
     55 => ['name' => 'Fiľakovo'],
     56 => ['name' => 'Svidník'],
     57 => ['name' => 'Šurany'],
     58 => ['name' => 'Tvrdošín'],
     59 => ['name' => 'Veľký Krtíš'],
     60 => ['name' => 'Myjava'],
     61 => ['name' => 'Slovakia Locality 1'],
     62 => ['name' => 'Slovakia Locality 2'],
     63 => ['name' => 'Slovakia Locality 3'],
     64 => ['name' => 'Slovakia Locality 4'],
     65 => ['name' => 'Slovakia Locality 5'],
     66 => ['name' => 'Slovakia Locality 6'],
     67 => ['name' => 'Slovakia Locality 7'],
     68 => ['name' => 'Slovakia Locality 8'],
     69 => ['name' => 'Slovakia Locality 9'],
     70 => ['name' => 'Slovakia Locality 10'],
     71 => ['name' => 'Slovakia Locality 11'],
     72 => ['name' => 'Slovakia Locality 12'],
     73 => ['name' => 'Slovakia Locality 13'],
     74 => ['name' => 'Slovakia Locality 14'],
     75 => ['name' => 'Slovakia Locality 15'],
     76 => ['name' => 'Slovakia Locality 16'],
     77 => ['name' => 'Slovakia Locality 17'],
     78 => ['name' => 'Slovakia Locality 18'],
     79 => ['name' => 'Slovakia Locality 19'],
     80 => ['name' => 'Slovakia Locality 20'],
     81 => ['name' => 'Slovakia Locality 21'],
     82 => ['name' => 'Slovakia Locality 22'],
     83 => ['name' => 'Slovakia Locality 23'],
     84 => ['name' => 'Slovakia Locality 24'],
     85 => ['name' => 'Slovakia Locality 25'],
     86 => ['name' => 'Slovakia Locality 26'],
     87 => ['name' => 'Slovakia Locality 27'],
     88 => ['name' => 'Slovakia Locality 28'],
     89 => ['name' => 'Slovakia Locality 29'],
     90 => ['name' => 'Slovakia Locality 30'],
     91 => ['name' => 'Slovakia Locality 31'],
     92 => ['name' => 'Slovakia Locality 32'],
     93 => ['name' => 'Slovakia Locality 33'],
     94 => ['name' => 'Slovakia Locality 34'],
     95 => ['name' => 'Slovakia Locality 35'],
     96 => ['name' => 'Slovakia Locality 36'],
     97 => ['name' => 'Slovakia Locality 37'],
     98 => ['name' => 'Slovakia Locality 38'],
     99 => ['name' => 'Slovakia Locality 39'],
    100 => ['name' => 'Slovakia Locality 40'],
    101 => ['name' => 'Slovakia Locality 41'],
    102 => ['name' => 'Slovakia Locality 42'],
    103 => ['name' => 'Slovakia Locality 43'],
    104 => ['name' => 'Slovakia Locality 44'],
    105 => ['name' => 'Slovakia Locality 45'],
    106 => ['name' => 'Slovakia Locality 46'],
    107 => ['name' => 'Slovakia Locality 47'],
    108 => ['name' => 'Slovakia Locality 48'],
    109 => ['name' => 'Slovakia Locality 49'],
    110 => ['name' => 'Slovakia Locality 50'],
    111 => ['name' => 'Slovakia Locality 51'],
    112 => ['name' => 'Slovakia Locality 52'],
    113 => ['name' => 'Slovakia Locality 53'],
    114 => ['name' => 'Slovakia Locality 54'],
    115 => ['name' => 'Slovakia Locality 55'],
    116 => ['name' => 'Slovakia Locality 56'],
    117 => ['name' => 'Slovakia Locality 57'],
    118 => ['name' => 'Slovakia Locality 58'],
    119 => ['name' => 'Slovakia Locality 59'],
    120 => ['name' => 'Slovakia Locality 60'],
    121 => ['name' => 'Slovakia Locality 61'],
    122 => ['name' => 'Slovakia Locality 62'],
    123 => ['name' => 'Slovakia Locality 63'],
    124 => ['name' => 'Slovakia Locality 64'],
    125 => ['name' => 'Slovakia Locality 65'],
    126 => ['name' => 'Slovakia Locality 66'],
    127 => ['name' => 'Slovakia Locality 67'],
    128 => ['name' => 'Slovakia Locality 68'],
    129 => ['name' => 'Slovakia Locality 69'],
    130 => ['name' => 'Slovakia Locality 70'],
    131 => ['name' => 'Slovakia Locality 71'],
    132 => ['name' => 'Slovakia Locality 72'],
    133 => ['name' => 'Slovakia Locality 73'],
    134 => ['name' => 'Slovakia Locality 74'],
    135 => ['name' => 'Slovakia Locality 75'],
    136 => ['name' => 'Slovakia Locality 76'],
    137 => ['name' => 'Slovakia Locality 77'],
    138 => ['name' => 'Slovakia Locality 78'],
    139 => ['name' => 'Slovakia Locality 79'],
    140 => ['name' => 'Slovakia Locality 80'],
    141 => ['name' => 'Slovakia Locality 81'],
    142 => ['name' => 'Slovakia Locality 82'],
    143 => ['name' => 'Slovakia Locality 83'],
    144 => ['name' => 'Slovakia Locality 84'],
    145 => ['name' => 'Slovakia Locality 85'],
    146 => ['name' => 'Slovakia Locality 86'],
    147 => ['name' => 'Slovakia Locality 87'],
    148 => ['name' => 'Slovakia Locality 88'],
    149 => ['name' => 'Slovakia Locality 89'],
    150 => ['name' => 'Slovakia Locality 90'],
    151 => ['name' => 'Slovakia Locality 91'],
    152 => ['name' => 'Slovakia Locality 92'],
    153 => ['name' => 'Slovakia Locality 93'],
    154 => ['name' => 'Slovakia Locality 94'],
    155 => ['name' => 'Slovakia Locality 95'],
    156 => ['name' => 'Slovakia Locality 96'],
    157 => ['name' => 'Slovakia Locality 97'],
    158 => ['name' => 'Slovakia Locality 98'],
    159 => ['name' => 'Slovakia Locality 99'],
    160 => ['name' => 'Slovakia Locality 100'],
    161 => ['name' => 'Slovakia Locality 101'],
    162 => ['name' => 'Slovakia Locality 102'],
    163 => ['name' => 'Slovakia Locality 103'],
    164 => ['name' => 'Slovakia Locality 104'],
    165 => ['name' => 'Slovakia Locality 105'],
    166 => ['name' => 'Slovakia Locality 106'],
    167 => ['name' => 'Slovakia Locality 107'],
    168 => ['name' => 'Slovakia Locality 108'],
    169 => ['name' => 'Slovakia Locality 109'],
    170 => ['name' => 'Slovakia Locality 110'],
    171 => ['name' => 'Slovakia Locality 111'],
    172 => ['name' => 'Slovakia Locality 112'],
    173 => ['name' => 'Slovakia Locality 113'],
    174 => ['name' => 'Slovakia Locality 114'],
    175 => ['name' => 'Slovakia Locality 115'],
    176 => ['name' => 'Slovakia Locality 116'],
    177 => ['name' => 'Slovakia Locality 117'],
    178 => ['name' => 'Slovakia Locality 118'],
    179 => ['name' => 'Slovakia Locality 119'],
    180 => ['name' => 'Slovakia Locality 120'],
    181 => ['name' => 'Slovakia Locality 121'],
    182 => ['name' => 'Slovakia Locality 122'],
    183 => ['name' => 'Slovakia Locality 123'],
    184 => ['name' => 'Slovakia Locality 124'],
    185 => ['name' => 'Slovakia Locality 125'],
    186 => ['name' => 'Slovakia Locality 126'],
    187 => ['name' => 'Slovakia Locality 127'],
    188 => ['name' => 'Slovakia Locality 128'],
    189 => ['name' => 'Slovakia Locality 129'],
    190 => ['name' => 'Slovakia Locality 130'],
    191 => ['name' => 'Slovakia Locality 131'],
    192 => ['name' => 'Slovakia Locality 132'],
    193 => ['name' => 'Slovakia Locality 133'],
    194 => ['name' => 'Slovakia Locality 134'],
    195 => ['name' => 'Slovakia Locality 135'],
    196 => ['name' => 'Slovakia Locality 136'],
    197 => ['name' => 'Slovakia Locality 137'],
    198 => ['name' => 'Slovakia Locality 138'],
    199 => ['name' => 'Slovakia Locality 139'],
    200 => ['name' => 'Slovakia Locality 140'],
    201 => ['name' => 'Prievidza (2)'],
    202 => ['name' => 'Zvolen (2)'],
    203 => ['name' => 'Považská Bystrica (2)'],
    204 => ['name' => 'Nové Zámky (2)'],
    205 => ['name' => 'Michalovce (2)'],
    206 => ['name' => 'Spišská Nová Ves (2)'],
    207 => ['name' => 'Komárno (2)'],
    208 => ['name' => 'Humenné (2)'],
    209 => ['name' => 'Levice (2)'],
    210 => ['name' => 'Bardejov (2)']
];