<?php

return [
    1 => ['name' => 'Dushanbe'],
    2 => ['name' => 'Khujand'],
    3 => ['name' => 'Kulob'],
    4 => ['name' => 'Qurghonteppa'],
    5 => ['name' => 'Istaravshan'],
    6 => ['name' => 'Konibodom'],
    7 => ['name' => 'Kofarnihon'],
    8 => ['name' => 'Tursunzoda'],
    9 => ['name' => 'Isfara'],
    10 => ['name' => 'Panjakent'],
    11 => ['name' => 'Buston'],
    12 => ['name' => 'Danghara'],
    13 => ['name' => 'Farkhor'],
    14 => ['name' => 'Chkalovsk'],
    15 => ['name' => 'Rogun'],
    16 => ['name' => 'Hisor'],
    17 => ['name' => 'Norak'],
    18 => ['name' => 'Yovon'],
    19 => ['name' => 'Hulbuk'],
    20 => ['name' => 'Vahdat'],
    21 => ['name' => 'Gafurov'],
    22 => ['name' => 'Istiqlol'],
    23 => ['name' => 'Shahritus'],
    24 => ['name' => 'Tursunzoda'],
    25 => ['name' => 'Gharm'],
    26 => ['name' => 'Rasht'],
    27 => ['name' => 'Jirgatol'],
    28 => ['name' => 'Tavildara'],
    29 => ['name' => 'Murghob'],
    30 => ['name' => 'Khorugh'],
    31 => ['name' => 'Rushon'],
    32 => ['name' => 'Shughnon'],
    33 => ['name' => 'Roshtqal\'a'],
    34 => ['name' => 'Ishkoshim'],
    35 => ['name' => 'Darvoz'],
    36 => ['name' => 'Murgob'],
    37 => ['name' => 'Vanj'],
    38 => ['name' => 'Darvoz'],
    39 => ['name' => 'Rasht'],
    40 => ['name' => 'Jirgatol'],
    41 => ['name' => 'Tavildara'],
    42 => ['name' => 'Nurobod'],
    43 => ['name' => 'Tojikobod'],
    44 => ['name' => 'Lakhsh'],
    45 => ['name' => 'Sangvor'],
    46 => ['name' => 'Dushanbe'],
    47 => ['name' => 'Khujand'],
    48 => ['name' => 'Kulob'],
    49 => ['name' => 'Qurghonteppa'],
    50 => ['name' => 'Istaravshan'],
    51 => ['name' => 'Konibodom'],
    52 => ['name' => 'Isfara'],
    53 => ['name' => 'Panjakent'],
    54 => ['name' => 'Buston'],
    55 => ['name' => 'Chkalovsk'],
    56 => ['name' => 'Gafurov'],
    57 => ['name' => 'Vahdat'],
    58 => ['name' => 'Tursunzoda'],
    59 => ['name' => 'Hisor'],
    60 => ['name' => 'Norak'],
     61 => ['name' => 'Tajikistan Locality 1'],
     62 => ['name' => 'Tajikistan Locality 2'],
     63 => ['name' => 'Tajikistan Locality 3'],
     64 => ['name' => 'Tajikistan Locality 4'],
     65 => ['name' => 'Tajikistan Locality 5'],
     66 => ['name' => 'Tajikistan Locality 6'],
     67 => ['name' => 'Tajikistan Locality 7'],
     68 => ['name' => 'Tajikistan Locality 8'],
     69 => ['name' => 'Tajikistan Locality 9'],
     70 => ['name' => 'Tajikistan Locality 10'],
     71 => ['name' => 'Tajikistan Locality 11'],
     72 => ['name' => 'Tajikistan Locality 12'],
     73 => ['name' => 'Tajikistan Locality 13'],
     74 => ['name' => 'Tajikistan Locality 14'],
     75 => ['name' => 'Tajikistan Locality 15'],
     76 => ['name' => 'Tajikistan Locality 16'],
     77 => ['name' => 'Tajikistan Locality 17'],
     78 => ['name' => 'Tajikistan Locality 18'],
     79 => ['name' => 'Tajikistan Locality 19'],
     80 => ['name' => 'Tajikistan Locality 20'],
     81 => ['name' => 'Tajikistan Locality 21'],
     82 => ['name' => 'Tajikistan Locality 22'],
     83 => ['name' => 'Tajikistan Locality 23'],
     84 => ['name' => 'Tajikistan Locality 24'],
     85 => ['name' => 'Tajikistan Locality 25'],
     86 => ['name' => 'Tajikistan Locality 26'],
     87 => ['name' => 'Tajikistan Locality 27'],
     88 => ['name' => 'Tajikistan Locality 28'],
     89 => ['name' => 'Tajikistan Locality 29'],
     90 => ['name' => 'Tajikistan Locality 30'],
     91 => ['name' => 'Tajikistan Locality 31'],
     92 => ['name' => 'Tajikistan Locality 32'],
     93 => ['name' => 'Tajikistan Locality 33'],
     94 => ['name' => 'Tajikistan Locality 34'],
     95 => ['name' => 'Tajikistan Locality 35'],
     96 => ['name' => 'Tajikistan Locality 36'],
     97 => ['name' => 'Tajikistan Locality 37'],
     98 => ['name' => 'Tajikistan Locality 38'],
     99 => ['name' => 'Tajikistan Locality 39'],
    100 => ['name' => 'Tajikistan Locality 40'],
    101 => ['name' => 'Tajikistan Locality 41'],
    102 => ['name' => 'Tajikistan Locality 42'],
    103 => ['name' => 'Tajikistan Locality 43'],
    104 => ['name' => 'Tajikistan Locality 44'],
    105 => ['name' => 'Tajikistan Locality 45'],
    106 => ['name' => 'Tajikistan Locality 46'],
    107 => ['name' => 'Tajikistan Locality 47'],
    108 => ['name' => 'Tajikistan Locality 48'],
    109 => ['name' => 'Tajikistan Locality 49'],
    110 => ['name' => 'Tajikistan Locality 50'],
    111 => ['name' => 'Tajikistan Locality 51'],
    112 => ['name' => 'Tajikistan Locality 52'],
    113 => ['name' => 'Tajikistan Locality 53'],
    114 => ['name' => 'Tajikistan Locality 54'],
    115 => ['name' => 'Tajikistan Locality 55'],
    116 => ['name' => 'Tajikistan Locality 56'],
    117 => ['name' => 'Tajikistan Locality 57'],
    118 => ['name' => 'Tajikistan Locality 58'],
    119 => ['name' => 'Tajikistan Locality 59'],
    120 => ['name' => 'Tajikistan Locality 60'],
    121 => ['name' => 'Tajikistan Locality 61'],
    122 => ['name' => 'Tajikistan Locality 62'],
    123 => ['name' => 'Tajikistan Locality 63'],
    124 => ['name' => 'Tajikistan Locality 64'],
    125 => ['name' => 'Tajikistan Locality 65'],
    126 => ['name' => 'Tajikistan Locality 66'],
    127 => ['name' => 'Tajikistan Locality 67'],
    128 => ['name' => 'Tajikistan Locality 68'],
    129 => ['name' => 'Tajikistan Locality 69'],
    130 => ['name' => 'Tajikistan Locality 70'],
    131 => ['name' => 'Tajikistan Locality 71'],
    132 => ['name' => 'Tajikistan Locality 72'],
    133 => ['name' => 'Tajikistan Locality 73'],
    134 => ['name' => 'Tajikistan Locality 74'],
    135 => ['name' => 'Tajikistan Locality 75'],
    136 => ['name' => 'Tajikistan Locality 76'],
    137 => ['name' => 'Tajikistan Locality 77'],
    138 => ['name' => 'Tajikistan Locality 78'],
    139 => ['name' => 'Tajikistan Locality 79'],
    140 => ['name' => 'Tajikistan Locality 80'],
    141 => ['name' => 'Tajikistan Locality 81'],
    142 => ['name' => 'Tajikistan Locality 82'],
    143 => ['name' => 'Tajikistan Locality 83'],
    144 => ['name' => 'Tajikistan Locality 84'],
    145 => ['name' => 'Tajikistan Locality 85'],
    146 => ['name' => 'Tajikistan Locality 86'],
    147 => ['name' => 'Tajikistan Locality 87'],
    148 => ['name' => 'Tajikistan Locality 88'],
    149 => ['name' => 'Tajikistan Locality 89'],
    150 => ['name' => 'Tajikistan Locality 90'],
    151 => ['name' => 'Tajikistan Locality 91'],
    152 => ['name' => 'Tajikistan Locality 92'],
    153 => ['name' => 'Tajikistan Locality 93'],
    154 => ['name' => 'Tajikistan Locality 94'],
    155 => ['name' => 'Tajikistan Locality 95'],
    156 => ['name' => 'Tajikistan Locality 96'],
    157 => ['name' => 'Tajikistan Locality 97'],
    158 => ['name' => 'Tajikistan Locality 98'],
    159 => ['name' => 'Tajikistan Locality 99'],
    160 => ['name' => 'Tajikistan Locality 100'],
    161 => ['name' => 'Tajikistan Locality 101'],
    162 => ['name' => 'Tajikistan Locality 102'],
    163 => ['name' => 'Tajikistan Locality 103'],
    164 => ['name' => 'Tajikistan Locality 104'],
    165 => ['name' => 'Tajikistan Locality 105'],
    166 => ['name' => 'Tajikistan Locality 106'],
    167 => ['name' => 'Tajikistan Locality 107'],
    168 => ['name' => 'Tajikistan Locality 108'],
    169 => ['name' => 'Tajikistan Locality 109'],
    170 => ['name' => 'Tajikistan Locality 110'],
    171 => ['name' => 'Tajikistan Locality 111'],
    172 => ['name' => 'Tajikistan Locality 112'],
    173 => ['name' => 'Tajikistan Locality 113'],
    174 => ['name' => 'Tajikistan Locality 114'],
    175 => ['name' => 'Tajikistan Locality 115'],
    176 => ['name' => 'Tajikistan Locality 116'],
    177 => ['name' => 'Tajikistan Locality 117'],
    178 => ['name' => 'Tajikistan Locality 118'],
    179 => ['name' => 'Tajikistan Locality 119'],
    180 => ['name' => 'Tajikistan Locality 120'],
    181 => ['name' => 'Tajikistan Locality 121'],
    182 => ['name' => 'Tajikistan Locality 122'],
    183 => ['name' => 'Tajikistan Locality 123'],
    184 => ['name' => 'Tajikistan Locality 124'],
    185 => ['name' => 'Tajikistan Locality 125'],
    186 => ['name' => 'Tajikistan Locality 126'],
    187 => ['name' => 'Tajikistan Locality 127'],
    188 => ['name' => 'Tajikistan Locality 128'],
    189 => ['name' => 'Tajikistan Locality 129'],
    190 => ['name' => 'Tajikistan Locality 130'],
    191 => ['name' => 'Tajikistan Locality 131'],
    192 => ['name' => 'Tajikistan Locality 132'],
    193 => ['name' => 'Tajikistan Locality 133'],
    194 => ['name' => 'Tajikistan Locality 134'],
    195 => ['name' => 'Tajikistan Locality 135'],
    196 => ['name' => 'Tajikistan Locality 136'],
    197 => ['name' => 'Tajikistan Locality 137'],
    198 => ['name' => 'Tajikistan Locality 138'],
    199 => ['name' => 'Tajikistan Locality 139'],
    200 => ['name' => 'Tajikistan Locality 140'],
    201 => ['name' => 'Tajikistan Locality 1 (2)'],
    202 => ['name' => 'Tajikistan Locality 2 (2)'],
    203 => ['name' => 'Tajikistan Locality 3 (2)'],
    204 => ['name' => 'Tajikistan Locality 4 (2)'],
    205 => ['name' => 'Tajikistan Locality 5 (2)'],
    206 => ['name' => 'Tajikistan Locality 6 (2)'],
    207 => ['name' => 'Tajikistan Locality 7 (2)'],
    208 => ['name' => 'Tajikistan Locality 8 (2)'],
    209 => ['name' => 'Tajikistan Locality 9 (2)'],
    210 => ['name' => 'Tajikistan Locality 10 (2)'],
    211 => ['name' => 'Tajikistan Locality 11 (2)'],
    212 => ['name' => 'Tajikistan Locality 12 (2)'],
    213 => ['name' => 'Tajikistan Locality 13 (2)'],
    214 => ['name' => 'Tajikistan Locality 14 (2)'],
    215 => ['name' => 'Tajikistan Locality 15 (2)'],
    216 => ['name' => 'Tajikistan Locality 16 (2)'],
    217 => ['name' => 'Tajikistan Locality 17 (2)'],
    218 => ['name' => 'Tajikistan Locality 18 (2)'],
    219 => ['name' => 'Tajikistan Locality 19 (2)'],
    220 => ['name' => 'Tajikistan Locality 20 (2)'],
    221 => ['name' => 'Tajikistan Locality 21 (2)'],
    222 => ['name' => 'Tajikistan Locality 22 (2)'],
    223 => ['name' => 'Tajikistan Locality 23 (2)'],
    224 => ['name' => 'Tajikistan Locality 24 (2)'],
    225 => ['name' => 'Tajikistan Locality 25 (2)'],
    226 => ['name' => 'Tajikistan Locality 26 (2)'],
    227 => ['name' => 'Tajikistan Locality 27 (2)'],
    228 => ['name' => 'Tajikistan Locality 28 (2)'],
    229 => ['name' => 'Tajikistan Locality 29 (2)'],
    230 => ['name' => 'Tajikistan Locality 30 (2)'],
    231 => ['name' => 'Tajikistan Locality 31 (2)'],
    232 => ['name' => 'Tajikistan Locality 32 (2)'],
    233 => ['name' => 'Tajikistan Locality 33 (2)'],
    234 => ['name' => 'Tajikistan Locality 34 (2)'],
    235 => ['name' => 'Tajikistan Locality 35 (2)'],
    236 => ['name' => 'Tajikistan Locality 36 (2)'],
    237 => ['name' => 'Tajikistan Locality 37 (2)'],
    238 => ['name' => 'Tajikistan Locality 38 (2)'],
    239 => ['name' => 'Tajikistan Locality 39 (2)'],
    240 => ['name' => 'Tajikistan Locality 40 (2)'],
    241 => ['name' => 'Tajikistan Locality 41 (2)'],
    242 => ['name' => 'Tajikistan Locality 42 (2)'],
    243 => ['name' => 'Tajikistan Locality 43 (2)'],
    244 => ['name' => 'Tajikistan Locality 44 (2)'],
    245 => ['name' => 'Tajikistan Locality 45 (2)'],
    246 => ['name' => 'Tajikistan Locality 46 (2)'],
    247 => ['name' => 'Tajikistan Locality 47 (2)'],
    248 => ['name' => 'Tajikistan Locality 48 (2)'],
    249 => ['name' => 'Tajikistan Locality 49 (2)'],
    250 => ['name' => 'Tajikistan Locality 50 (2)'],
    251 => ['name' => 'Tajikistan Locality 51 (2)'],
    252 => ['name' => 'Tajikistan Locality 52 (2)'],
    253 => ['name' => 'Tajikistan Locality 53 (2)'],
    254 => ['name' => 'Tajikistan Locality 54 (2)'],
    255 => ['name' => 'Tajikistan Locality 55 (2)'],
    256 => ['name' => 'Tajikistan Locality 56 (2)'],
    257 => ['name' => 'Tajikistan Locality 57 (2)'],
    258 => ['name' => 'Tajikistan Locality 58 (2)'],
    259 => ['name' => 'Tajikistan Locality 59 (2)'],
    260 => ['name' => 'Tajikistan Locality 60 (2)']
];