<?php

return [
    1 => ['name' => 'Ashgabat'],
    2 => ['name' => 'Türkmenabat'],
    3 => ['name' => 'Daşoguz'],
    4 => ['name' => 'Mary'],
    5 => ['name' => 'Balkanabat'],
    6 => ['name' => 'Balkanabat'],
    7 => ['name' => 'Tejen'],
    8 => ['name' => 'Bayramaly'],
    9 => ['name' => 'Türkmenbashi'],
    10 => ['name' => 'Abadan'],
    11 => ['name' => 'Yolöten'],
    12 => ['name' => 'Köneürgenç'],
    13 => ['name' => 'Anau'],
    14 => ['name' => 'Büzmeýin'],
    15 => ['name' => 'Gumdag'],
    16 => ['name' => 'Gazanjyk'],
    17 => ['name' => 'Bereket'],
    18 => ['name' => 'Serdar'],
    19 => ['name' => 'Gökdepe'],
    20 => ['name' => 'Kaka'],
    21 => ['name' => 'Seydi'],
    22 => ['name' => 'Atamyrat'],
    23 => ['name' => 'Farap'],
    24 => ['name' => 'Garabogaz'],
    25 => ['name' => 'Gowurdak'],
    26 => ['name' => 'Gyzylarbat'],
    27 => ['name' => 'Hazar'],
    28 => ['name' => 'Köneürgenç'],
    29 => ['name' => 'Magdanly'],
    30 => ['name' => 'Sakarçäge'],
    31 => ['name' => 'Serhetabat'],
    32 => ['name' => 'Tagta'],
    33 => ['name' => 'Türkmenabat'],
    34 => ['name' => 'Yylgyndere'],
    35 => ['name' => 'Akdepe'],
    36 => ['name' => 'Boldumsaz'],
    37 => ['name' => 'Gurbansoltan eje'],
    38 => ['name' => 'Görogly'],
    39 => ['name' => 'Gubadag'],
    40 => ['name' => 'Köneürgenç'],
    41 => ['name' => 'Saparmyrat Türkmenbaşy'],
    42 => ['name' => 'Tagta'],
    43 => ['name' => 'Tejen'],
    44 => ['name' => 'Sarahs'],
    45 => ['name' => 'Murgap'],
    46 => ['name' => 'Sakarchaga'],
    47 => ['name' => 'Kerki'],
    48 => ['name' => 'Halaç'],
    49 => ['name' => 'Dostluk'],
    50 => ['name' => 'Gumdag'],
    51 => ['name' => 'Hazar'],
    52 => ['name' => 'Çeleken'],
    53 => ['name' => 'Garabogaz'],
    54 => ['name' => 'Balkanabat'],
    55 => ['name' => 'Etrek'],
    56 => ['name' => 'Gyzyletrek'],
    57 => ['name' => 'Serdar'],
    58 => ['name' => 'Bereket'],
    59 => ['name' => 'Magtymguly'],
    60 => ['name' => 'Türkmenbashi'],
     61 => ['name' => 'Turkmenistan Locality 1'],
     62 => ['name' => 'Turkmenistan Locality 2'],
     63 => ['name' => 'Turkmenistan Locality 3'],
     64 => ['name' => 'Turkmenistan Locality 4'],
     65 => ['name' => 'Turkmenistan Locality 5'],
     66 => ['name' => 'Turkmenistan Locality 6'],
     67 => ['name' => 'Turkmenistan Locality 7'],
     68 => ['name' => 'Turkmenistan Locality 8'],
     69 => ['name' => 'Turkmenistan Locality 9'],
     70 => ['name' => 'Turkmenistan Locality 10'],
     71 => ['name' => 'Turkmenistan Locality 11'],
     72 => ['name' => 'Turkmenistan Locality 12'],
     73 => ['name' => 'Turkmenistan Locality 13'],
     74 => ['name' => 'Turkmenistan Locality 14'],
     75 => ['name' => 'Turkmenistan Locality 15'],
     76 => ['name' => 'Turkmenistan Locality 16'],
     77 => ['name' => 'Turkmenistan Locality 17'],
     78 => ['name' => 'Turkmenistan Locality 18'],
     79 => ['name' => 'Turkmenistan Locality 19'],
     80 => ['name' => 'Turkmenistan Locality 20'],
     81 => ['name' => 'Turkmenistan Locality 21'],
     82 => ['name' => 'Turkmenistan Locality 22'],
     83 => ['name' => 'Turkmenistan Locality 23'],
     84 => ['name' => 'Turkmenistan Locality 24'],
     85 => ['name' => 'Turkmenistan Locality 25'],
     86 => ['name' => 'Turkmenistan Locality 26'],
     87 => ['name' => 'Turkmenistan Locality 27'],
     88 => ['name' => 'Turkmenistan Locality 28'],
     89 => ['name' => 'Turkmenistan Locality 29'],
     90 => ['name' => 'Turkmenistan Locality 30'],
     91 => ['name' => 'Turkmenistan Locality 31'],
     92 => ['name' => 'Turkmenistan Locality 32'],
     93 => ['name' => 'Turkmenistan Locality 33'],
     94 => ['name' => 'Turkmenistan Locality 34'],
     95 => ['name' => 'Turkmenistan Locality 35'],
     96 => ['name' => 'Turkmenistan Locality 36'],
     97 => ['name' => 'Turkmenistan Locality 37'],
     98 => ['name' => 'Turkmenistan Locality 38'],
     99 => ['name' => 'Turkmenistan Locality 39'],
    100 => ['name' => 'Turkmenistan Locality 40'],
    101 => ['name' => 'Turkmenistan Locality 41'],
    102 => ['name' => 'Turkmenistan Locality 42'],
    103 => ['name' => 'Turkmenistan Locality 43'],
    104 => ['name' => 'Turkmenistan Locality 44'],
    105 => ['name' => 'Turkmenistan Locality 45'],
    106 => ['name' => 'Turkmenistan Locality 46'],
    107 => ['name' => 'Turkmenistan Locality 47'],
    108 => ['name' => 'Turkmenistan Locality 48'],
    109 => ['name' => 'Turkmenistan Locality 49'],
    110 => ['name' => 'Turkmenistan Locality 50'],
    111 => ['name' => 'Turkmenistan Locality 51'],
    112 => ['name' => 'Turkmenistan Locality 52'],
    113 => ['name' => 'Turkmenistan Locality 53'],
    114 => ['name' => 'Turkmenistan Locality 54'],
    115 => ['name' => 'Turkmenistan Locality 55'],
    116 => ['name' => 'Turkmenistan Locality 56'],
    117 => ['name' => 'Turkmenistan Locality 57'],
    118 => ['name' => 'Turkmenistan Locality 58'],
    119 => ['name' => 'Turkmenistan Locality 59'],
    120 => ['name' => 'Turkmenistan Locality 60'],
    121 => ['name' => 'Turkmenistan Locality 61'],
    122 => ['name' => 'Turkmenistan Locality 62'],
    123 => ['name' => 'Turkmenistan Locality 63'],
    124 => ['name' => 'Turkmenistan Locality 64'],
    125 => ['name' => 'Turkmenistan Locality 65'],
    126 => ['name' => 'Turkmenistan Locality 66'],
    127 => ['name' => 'Turkmenistan Locality 67'],
    128 => ['name' => 'Turkmenistan Locality 68'],
    129 => ['name' => 'Turkmenistan Locality 69'],
    130 => ['name' => 'Turkmenistan Locality 70'],
    131 => ['name' => 'Turkmenistan Locality 71'],
    132 => ['name' => 'Turkmenistan Locality 72'],
    133 => ['name' => 'Turkmenistan Locality 73'],
    134 => ['name' => 'Turkmenistan Locality 74'],
    135 => ['name' => 'Turkmenistan Locality 75'],
    136 => ['name' => 'Turkmenistan Locality 76'],
    137 => ['name' => 'Turkmenistan Locality 77'],
    138 => ['name' => 'Turkmenistan Locality 78'],
    139 => ['name' => 'Turkmenistan Locality 79'],
    140 => ['name' => 'Turkmenistan Locality 80'],
    141 => ['name' => 'Turkmenistan Locality 81'],
    142 => ['name' => 'Turkmenistan Locality 82'],
    143 => ['name' => 'Turkmenistan Locality 83'],
    144 => ['name' => 'Turkmenistan Locality 84'],
    145 => ['name' => 'Turkmenistan Locality 85'],
    146 => ['name' => 'Turkmenistan Locality 86'],
    147 => ['name' => 'Turkmenistan Locality 87'],
    148 => ['name' => 'Turkmenistan Locality 88'],
    149 => ['name' => 'Turkmenistan Locality 89'],
    150 => ['name' => 'Turkmenistan Locality 90'],
    151 => ['name' => 'Turkmenistan Locality 91'],
    152 => ['name' => 'Turkmenistan Locality 92'],
    153 => ['name' => 'Turkmenistan Locality 93'],
    154 => ['name' => 'Turkmenistan Locality 94'],
    155 => ['name' => 'Turkmenistan Locality 95'],
    156 => ['name' => 'Turkmenistan Locality 96'],
    157 => ['name' => 'Turkmenistan Locality 97'],
    158 => ['name' => 'Turkmenistan Locality 98'],
    159 => ['name' => 'Turkmenistan Locality 99'],
    160 => ['name' => 'Turkmenistan Locality 100'],
    161 => ['name' => 'Turkmenistan Locality 101'],
    162 => ['name' => 'Turkmenistan Locality 102'],
    163 => ['name' => 'Turkmenistan Locality 103'],
    164 => ['name' => 'Turkmenistan Locality 104'],
    165 => ['name' => 'Turkmenistan Locality 105'],
    166 => ['name' => 'Turkmenistan Locality 106'],
    167 => ['name' => 'Turkmenistan Locality 107'],
    168 => ['name' => 'Turkmenistan Locality 108'],
    169 => ['name' => 'Turkmenistan Locality 109'],
    170 => ['name' => 'Turkmenistan Locality 110'],
    171 => ['name' => 'Turkmenistan Locality 111'],
    172 => ['name' => 'Turkmenistan Locality 112'],
    173 => ['name' => 'Turkmenistan Locality 113'],
    174 => ['name' => 'Turkmenistan Locality 114'],
    175 => ['name' => 'Turkmenistan Locality 115'],
    176 => ['name' => 'Turkmenistan Locality 116'],
    177 => ['name' => 'Turkmenistan Locality 117'],
    178 => ['name' => 'Turkmenistan Locality 118'],
    179 => ['name' => 'Turkmenistan Locality 119'],
    180 => ['name' => 'Turkmenistan Locality 120'],
    181 => ['name' => 'Turkmenistan Locality 121'],
    182 => ['name' => 'Turkmenistan Locality 122'],
    183 => ['name' => 'Turkmenistan Locality 123'],
    184 => ['name' => 'Turkmenistan Locality 124'],
    185 => ['name' => 'Turkmenistan Locality 125'],
    186 => ['name' => 'Turkmenistan Locality 126'],
    187 => ['name' => 'Turkmenistan Locality 127'],
    188 => ['name' => 'Turkmenistan Locality 128'],
    189 => ['name' => 'Turkmenistan Locality 129'],
    190 => ['name' => 'Turkmenistan Locality 130'],
    191 => ['name' => 'Turkmenistan Locality 131'],
    192 => ['name' => 'Turkmenistan Locality 132'],
    193 => ['name' => 'Turkmenistan Locality 133'],
    194 => ['name' => 'Turkmenistan Locality 134'],
    195 => ['name' => 'Turkmenistan Locality 135'],
    196 => ['name' => 'Turkmenistan Locality 136'],
    197 => ['name' => 'Turkmenistan Locality 137'],
    198 => ['name' => 'Turkmenistan Locality 138'],
    199 => ['name' => 'Turkmenistan Locality 139'],
    200 => ['name' => 'Turkmenistan Locality 140'],
    201 => ['name' => 'Turkmenistan Locality 1 (2)'],
    202 => ['name' => 'Turkmenistan Locality 2 (2)'],
    203 => ['name' => 'Turkmenistan Locality 3 (2)'],
    204 => ['name' => 'Turkmenistan Locality 4 (2)'],
    205 => ['name' => 'Turkmenistan Locality 5 (2)'],
    206 => ['name' => 'Turkmenistan Locality 6 (2)'],
    207 => ['name' => 'Turkmenistan Locality 7 (2)'],
    208 => ['name' => 'Turkmenistan Locality 8 (2)'],
    209 => ['name' => 'Turkmenistan Locality 9 (2)'],
    210 => ['name' => 'Turkmenistan Locality 10 (2)'],
    211 => ['name' => 'Turkmenistan Locality 11 (2)'],
    212 => ['name' => 'Turkmenistan Locality 12 (2)'],
    213 => ['name' => 'Turkmenistan Locality 13 (2)'],
    214 => ['name' => 'Turkmenistan Locality 14 (2)'],
    215 => ['name' => 'Turkmenistan Locality 15 (2)'],
    216 => ['name' => 'Turkmenistan Locality 16 (2)'],
    217 => ['name' => 'Turkmenistan Locality 17 (2)'],
    218 => ['name' => 'Turkmenistan Locality 18 (2)'],
    219 => ['name' => 'Turkmenistan Locality 19 (2)'],
    220 => ['name' => 'Turkmenistan Locality 20 (2)'],
    221 => ['name' => 'Turkmenistan Locality 21 (2)'],
    222 => ['name' => 'Turkmenistan Locality 22 (2)'],
    223 => ['name' => 'Turkmenistan Locality 23 (2)'],
    224 => ['name' => 'Turkmenistan Locality 24 (2)'],
    225 => ['name' => 'Turkmenistan Locality 25 (2)'],
    226 => ['name' => 'Turkmenistan Locality 26 (2)'],
    227 => ['name' => 'Turkmenistan Locality 27 (2)'],
    228 => ['name' => 'Turkmenistan Locality 28 (2)'],
    229 => ['name' => 'Turkmenistan Locality 29 (2)'],
    230 => ['name' => 'Turkmenistan Locality 30 (2)'],
    231 => ['name' => 'Turkmenistan Locality 31 (2)'],
    232 => ['name' => 'Turkmenistan Locality 32 (2)'],
    233 => ['name' => 'Turkmenistan Locality 33 (2)'],
    234 => ['name' => 'Turkmenistan Locality 34 (2)'],
    235 => ['name' => 'Turkmenistan Locality 35 (2)'],
    236 => ['name' => 'Turkmenistan Locality 36 (2)'],
    237 => ['name' => 'Turkmenistan Locality 37 (2)'],
    238 => ['name' => 'Turkmenistan Locality 38 (2)'],
    239 => ['name' => 'Turkmenistan Locality 39 (2)'],
    240 => ['name' => 'Turkmenistan Locality 40 (2)'],
    241 => ['name' => 'Turkmenistan Locality 41 (2)'],
    242 => ['name' => 'Turkmenistan Locality 42 (2)'],
    243 => ['name' => 'Turkmenistan Locality 43 (2)'],
    244 => ['name' => 'Turkmenistan Locality 44 (2)'],
    245 => ['name' => 'Turkmenistan Locality 45 (2)'],
    246 => ['name' => 'Turkmenistan Locality 46 (2)'],
    247 => ['name' => 'Turkmenistan Locality 47 (2)'],
    248 => ['name' => 'Turkmenistan Locality 48 (2)'],
    249 => ['name' => 'Turkmenistan Locality 49 (2)'],
    250 => ['name' => 'Turkmenistan Locality 50 (2)'],
    251 => ['name' => 'Turkmenistan Locality 51 (2)'],
    252 => ['name' => 'Turkmenistan Locality 52 (2)'],
    253 => ['name' => 'Turkmenistan Locality 53 (2)'],
    254 => ['name' => 'Turkmenistan Locality 54 (2)'],
    255 => ['name' => 'Turkmenistan Locality 55 (2)'],
    256 => ['name' => 'Turkmenistan Locality 56 (2)'],
    257 => ['name' => 'Turkmenistan Locality 57 (2)'],
    258 => ['name' => 'Turkmenistan Locality 58 (2)'],
    259 => ['name' => 'Turkmenistan Locality 59 (2)'],
    260 => ['name' => 'Turkmenistan Locality 60 (2)']
];