<?php

return [
    1 => ['name' => 'Tashkent'],
    2 => ['name' => 'Samarkand'],
    3 => ['name' => 'Bukhara'],
    4 => ['name' => 'Andijan'],
    5 => ['name' => 'Namangan'],
    6 => ['name' => 'Nukus'],
    7 => ['name' => 'Fergana'],
    8 => ['name' => 'Qarshi'],
    9 => ['name' => 'Jizzakh'],
    10 => ['name' => 'Urgench'],
    11 => ['name' => 'Termez'],
    12 => ['name' => 'Navoiy'],
    13 => ['name' => 'Margilan'],
    14 => ['name' => 'Kokand'],
    15 => ['name' => 'Chirchiq'],
    16 => ['name' => 'Guliston'],
    17 => ['name' => 'Angren'],
    18 => ['name' => 'Bekabad'],
    19 => ['name' => 'Olmaliq'],
    20 => ['name' => 'Denov'],
    21 => ['name' => 'Kattakurgan'],
    22 => ['name' => 'Kogon'],
    23 => ['name' => 'Chust'],
    24 => ['name' => 'Karshi'],
    25 => ['name' => 'Almalyk'],
    26 => ['name' => 'Nurafshon'],
    27 => ['name' => 'Khiwa'],
    28 => ['name' => 'Shahrisabz'],
    29 => ['name' => 'Asaka'],
    30 => ['name' => 'Khanabad'],
    31 => ['name' => 'Kosonsoy'],
    32 => ['name' => 'Quva'],
    33 => ['name' => 'Rishton'],
    34 => ['name' => 'Kuvasay'],
    35 => ['name' => 'Zarafshon'],
    36 => ['name' => 'Chust'],
    37 => ['name' => 'Pap'],
    38 => ['name' => 'Tirmiz'],
    39 => ['name' => 'Urgut'],
    40 => ['name' => 'Kattakurgan'],
    41 => ['name' => 'Gijduvon'],
    42 => ['name' => 'Kagan'],
    43 => ['name' => 'Gazli'],
    44 => ['name' => 'Galaosiyo'],
    45 => ['name' => 'Zomin'],
    46 => ['name' => 'Jizzakh'],
    47 => ['name' => 'Yangiyer'],
    48 => ['name' => 'Chinoz'],
    49 => ['name' => 'Ohangaron'],
    50 => ['name' => 'Parkent'],
    51 => ['name' => 'Gazalkent'],
    52 => ['name' => 'Chirchiq'],
    53 => ['name' => 'Tashkent'],
    54 => ['name' => 'Nukus'],
    55 => ['name' => 'Khiva'],
    56 => ['name' => 'Beruniy'],
    57 => ['name' => 'Turtkul'],
    58 => ['name' => 'Muynak'],
    59 => ['name' => 'Termez'],
    60 => ['name' => 'Sherabad'],
     61 => ['name' => 'Uzbekistan Locality 1'],
     62 => ['name' => 'Uzbekistan Locality 2'],
     63 => ['name' => 'Uzbekistan Locality 3'],
     64 => ['name' => 'Uzbekistan Locality 4'],
     65 => ['name' => 'Uzbekistan Locality 5'],
     66 => ['name' => 'Uzbekistan Locality 6'],
     67 => ['name' => 'Uzbekistan Locality 7'],
     68 => ['name' => 'Uzbekistan Locality 8'],
     69 => ['name' => 'Uzbekistan Locality 9'],
     70 => ['name' => 'Uzbekistan Locality 10'],
     71 => ['name' => 'Uzbekistan Locality 11'],
     72 => ['name' => 'Uzbekistan Locality 12'],
     73 => ['name' => 'Uzbekistan Locality 13'],
     74 => ['name' => 'Uzbekistan Locality 14'],
     75 => ['name' => 'Uzbekistan Locality 15'],
     76 => ['name' => 'Uzbekistan Locality 16'],
     77 => ['name' => 'Uzbekistan Locality 17'],
     78 => ['name' => 'Uzbekistan Locality 18'],
     79 => ['name' => 'Uzbekistan Locality 19'],
     80 => ['name' => 'Uzbekistan Locality 20'],
     81 => ['name' => 'Uzbekistan Locality 21'],
     82 => ['name' => 'Uzbekistan Locality 22'],
     83 => ['name' => 'Uzbekistan Locality 23'],
     84 => ['name' => 'Uzbekistan Locality 24'],
     85 => ['name' => 'Uzbekistan Locality 25'],
     86 => ['name' => 'Uzbekistan Locality 26'],
     87 => ['name' => 'Uzbekistan Locality 27'],
     88 => ['name' => 'Uzbekistan Locality 28'],
     89 => ['name' => 'Uzbekistan Locality 29'],
     90 => ['name' => 'Uzbekistan Locality 30'],
     91 => ['name' => 'Uzbekistan Locality 31'],
     92 => ['name' => 'Uzbekistan Locality 32'],
     93 => ['name' => 'Uzbekistan Locality 33'],
     94 => ['name' => 'Uzbekistan Locality 34'],
     95 => ['name' => 'Uzbekistan Locality 35'],
     96 => ['name' => 'Uzbekistan Locality 36'],
     97 => ['name' => 'Uzbekistan Locality 37'],
     98 => ['name' => 'Uzbekistan Locality 38'],
     99 => ['name' => 'Uzbekistan Locality 39'],
    100 => ['name' => 'Uzbekistan Locality 40'],
    101 => ['name' => 'Uzbekistan Locality 41'],
    102 => ['name' => 'Uzbekistan Locality 42'],
    103 => ['name' => 'Uzbekistan Locality 43'],
    104 => ['name' => 'Uzbekistan Locality 44'],
    105 => ['name' => 'Uzbekistan Locality 45'],
    106 => ['name' => 'Uzbekistan Locality 46'],
    107 => ['name' => 'Uzbekistan Locality 47'],
    108 => ['name' => 'Uzbekistan Locality 48'],
    109 => ['name' => 'Uzbekistan Locality 49'],
    110 => ['name' => 'Uzbekistan Locality 50'],
    111 => ['name' => 'Uzbekistan Locality 51'],
    112 => ['name' => 'Uzbekistan Locality 52'],
    113 => ['name' => 'Uzbekistan Locality 53'],
    114 => ['name' => 'Uzbekistan Locality 54'],
    115 => ['name' => 'Uzbekistan Locality 55'],
    116 => ['name' => 'Uzbekistan Locality 56'],
    117 => ['name' => 'Uzbekistan Locality 57'],
    118 => ['name' => 'Uzbekistan Locality 58'],
    119 => ['name' => 'Uzbekistan Locality 59'],
    120 => ['name' => 'Uzbekistan Locality 60'],
    121 => ['name' => 'Uzbekistan Locality 61'],
    122 => ['name' => 'Uzbekistan Locality 62'],
    123 => ['name' => 'Uzbekistan Locality 63'],
    124 => ['name' => 'Uzbekistan Locality 64'],
    125 => ['name' => 'Uzbekistan Locality 65'],
    126 => ['name' => 'Uzbekistan Locality 66'],
    127 => ['name' => 'Uzbekistan Locality 67'],
    128 => ['name' => 'Uzbekistan Locality 68'],
    129 => ['name' => 'Uzbekistan Locality 69'],
    130 => ['name' => 'Uzbekistan Locality 70'],
    131 => ['name' => 'Uzbekistan Locality 71'],
    132 => ['name' => 'Uzbekistan Locality 72'],
    133 => ['name' => 'Uzbekistan Locality 73'],
    134 => ['name' => 'Uzbekistan Locality 74'],
    135 => ['name' => 'Uzbekistan Locality 75'],
    136 => ['name' => 'Uzbekistan Locality 76'],
    137 => ['name' => 'Uzbekistan Locality 77'],
    138 => ['name' => 'Uzbekistan Locality 78'],
    139 => ['name' => 'Uzbekistan Locality 79'],
    140 => ['name' => 'Uzbekistan Locality 80'],
    141 => ['name' => 'Uzbekistan Locality 81'],
    142 => ['name' => 'Uzbekistan Locality 82'],
    143 => ['name' => 'Uzbekistan Locality 83'],
    144 => ['name' => 'Uzbekistan Locality 84'],
    145 => ['name' => 'Uzbekistan Locality 85'],
    146 => ['name' => 'Uzbekistan Locality 86'],
    147 => ['name' => 'Uzbekistan Locality 87'],
    148 => ['name' => 'Uzbekistan Locality 88'],
    149 => ['name' => 'Uzbekistan Locality 89'],
    150 => ['name' => 'Uzbekistan Locality 90'],
    151 => ['name' => 'Uzbekistan Locality 91'],
    152 => ['name' => 'Uzbekistan Locality 92'],
    153 => ['name' => 'Uzbekistan Locality 93'],
    154 => ['name' => 'Uzbekistan Locality 94'],
    155 => ['name' => 'Uzbekistan Locality 95'],
    156 => ['name' => 'Uzbekistan Locality 96'],
    157 => ['name' => 'Uzbekistan Locality 97'],
    158 => ['name' => 'Uzbekistan Locality 98'],
    159 => ['name' => 'Uzbekistan Locality 99'],
    160 => ['name' => 'Uzbekistan Locality 100'],
    161 => ['name' => 'Uzbekistan Locality 101'],
    162 => ['name' => 'Uzbekistan Locality 102'],
    163 => ['name' => 'Uzbekistan Locality 103'],
    164 => ['name' => 'Uzbekistan Locality 104'],
    165 => ['name' => 'Uzbekistan Locality 105'],
    166 => ['name' => 'Uzbekistan Locality 106'],
    167 => ['name' => 'Uzbekistan Locality 107'],
    168 => ['name' => 'Uzbekistan Locality 108'],
    169 => ['name' => 'Uzbekistan Locality 109'],
    170 => ['name' => 'Uzbekistan Locality 110'],
    171 => ['name' => 'Uzbekistan Locality 111'],
    172 => ['name' => 'Uzbekistan Locality 112'],
    173 => ['name' => 'Uzbekistan Locality 113'],
    174 => ['name' => 'Uzbekistan Locality 114'],
    175 => ['name' => 'Uzbekistan Locality 115'],
    176 => ['name' => 'Uzbekistan Locality 116'],
    177 => ['name' => 'Uzbekistan Locality 117'],
    178 => ['name' => 'Uzbekistan Locality 118'],
    179 => ['name' => 'Uzbekistan Locality 119'],
    180 => ['name' => 'Uzbekistan Locality 120'],
    181 => ['name' => 'Uzbekistan Locality 121'],
    182 => ['name' => 'Uzbekistan Locality 122'],
    183 => ['name' => 'Uzbekistan Locality 123'],
    184 => ['name' => 'Uzbekistan Locality 124'],
    185 => ['name' => 'Uzbekistan Locality 125'],
    186 => ['name' => 'Uzbekistan Locality 126'],
    187 => ['name' => 'Uzbekistan Locality 127'],
    188 => ['name' => 'Uzbekistan Locality 128'],
    189 => ['name' => 'Uzbekistan Locality 129'],
    190 => ['name' => 'Uzbekistan Locality 130'],
    191 => ['name' => 'Uzbekistan Locality 131'],
    192 => ['name' => 'Uzbekistan Locality 132'],
    193 => ['name' => 'Uzbekistan Locality 133'],
    194 => ['name' => 'Uzbekistan Locality 134'],
    195 => ['name' => 'Uzbekistan Locality 135'],
    196 => ['name' => 'Uzbekistan Locality 136'],
    197 => ['name' => 'Uzbekistan Locality 137'],
    198 => ['name' => 'Uzbekistan Locality 138'],
    199 => ['name' => 'Uzbekistan Locality 139'],
    200 => ['name' => 'Uzbekistan Locality 140'],
    201 => ['name' => 'Uzbekistan Locality 1 (2)'],
    202 => ['name' => 'Uzbekistan Locality 2 (2)'],
    203 => ['name' => 'Uzbekistan Locality 3 (2)'],
    204 => ['name' => 'Uzbekistan Locality 4 (2)'],
    205 => ['name' => 'Uzbekistan Locality 5 (2)'],
    206 => ['name' => 'Uzbekistan Locality 6 (2)'],
    207 => ['name' => 'Uzbekistan Locality 7 (2)'],
    208 => ['name' => 'Uzbekistan Locality 8 (2)'],
    209 => ['name' => 'Uzbekistan Locality 9 (2)'],
    210 => ['name' => 'Uzbekistan Locality 10 (2)'],
    211 => ['name' => 'Uzbekistan Locality 11 (2)'],
    212 => ['name' => 'Uzbekistan Locality 12 (2)'],
    213 => ['name' => 'Uzbekistan Locality 13 (2)'],
    214 => ['name' => 'Uzbekistan Locality 14 (2)'],
    215 => ['name' => 'Uzbekistan Locality 15 (2)'],
    216 => ['name' => 'Uzbekistan Locality 16 (2)'],
    217 => ['name' => 'Uzbekistan Locality 17 (2)'],
    218 => ['name' => 'Uzbekistan Locality 18 (2)'],
    219 => ['name' => 'Uzbekistan Locality 19 (2)'],
    220 => ['name' => 'Uzbekistan Locality 20 (2)'],
    221 => ['name' => 'Uzbekistan Locality 21 (2)'],
    222 => ['name' => 'Uzbekistan Locality 22 (2)'],
    223 => ['name' => 'Uzbekistan Locality 23 (2)'],
    224 => ['name' => 'Uzbekistan Locality 24 (2)'],
    225 => ['name' => 'Uzbekistan Locality 25 (2)'],
    226 => ['name' => 'Uzbekistan Locality 26 (2)'],
    227 => ['name' => 'Uzbekistan Locality 27 (2)'],
    228 => ['name' => 'Uzbekistan Locality 28 (2)'],
    229 => ['name' => 'Uzbekistan Locality 29 (2)'],
    230 => ['name' => 'Uzbekistan Locality 30 (2)'],
    231 => ['name' => 'Uzbekistan Locality 31 (2)'],
    232 => ['name' => 'Uzbekistan Locality 32 (2)'],
    233 => ['name' => 'Uzbekistan Locality 33 (2)'],
    234 => ['name' => 'Uzbekistan Locality 34 (2)'],
    235 => ['name' => 'Uzbekistan Locality 35 (2)'],
    236 => ['name' => 'Uzbekistan Locality 36 (2)'],
    237 => ['name' => 'Uzbekistan Locality 37 (2)'],
    238 => ['name' => 'Uzbekistan Locality 38 (2)'],
    239 => ['name' => 'Uzbekistan Locality 39 (2)'],
    240 => ['name' => 'Uzbekistan Locality 40 (2)'],
    241 => ['name' => 'Uzbekistan Locality 41 (2)'],
    242 => ['name' => 'Uzbekistan Locality 42 (2)'],
    243 => ['name' => 'Uzbekistan Locality 43 (2)'],
    244 => ['name' => 'Uzbekistan Locality 44 (2)'],
    245 => ['name' => 'Uzbekistan Locality 45 (2)'],
    246 => ['name' => 'Uzbekistan Locality 46 (2)'],
    247 => ['name' => 'Uzbekistan Locality 47 (2)'],
    248 => ['name' => 'Uzbekistan Locality 48 (2)'],
    249 => ['name' => 'Uzbekistan Locality 49 (2)'],
    250 => ['name' => 'Uzbekistan Locality 50 (2)'],
    251 => ['name' => 'Uzbekistan Locality 51 (2)'],
    252 => ['name' => 'Uzbekistan Locality 52 (2)'],
    253 => ['name' => 'Uzbekistan Locality 53 (2)'],
    254 => ['name' => 'Uzbekistan Locality 54 (2)'],
    255 => ['name' => 'Uzbekistan Locality 55 (2)'],
    256 => ['name' => 'Uzbekistan Locality 56 (2)'],
    257 => ['name' => 'Uzbekistan Locality 57 (2)'],
    258 => ['name' => 'Uzbekistan Locality 58 (2)'],
    259 => ['name' => 'Uzbekistan Locality 59 (2)'],
    260 => ['name' => 'Uzbekistan Locality 60 (2)']
];