<?php

return [
    // === European Union ===
    1  => ['name' => 'Austria',       'iso' => 'AT', 'phone_code' => '+43'],
    2  => ['name' => 'Belgium',       'iso' => 'BE', 'phone_code' => '+32'],
    3  => ['name' => 'Bulgaria',      'iso' => 'BG', 'phone_code' => '+359'],
    4  => ['name' => 'Croatia',       'iso' => 'HR', 'phone_code' => '+385'],
    5  => ['name' => 'Cyprus',        'iso' => 'CY', 'phone_code' => '+357'],
    6  => ['name' => 'Czech Republic','iso' => 'CZ', 'phone_code' => '+420'],
    7  => ['name' => 'Denmark',       'iso' => 'DK', 'phone_code' => '+45'],
    8  => ['name' => 'Estonia',       'iso' => 'EE', 'phone_code' => '+372'],
    9  => ['name' => 'Finland',       'iso' => 'FI', 'phone_code' => '+358'],
    10 => ['name' => 'France',        'iso' => 'FR', 'phone_code' => '+33'],
    11 => ['name' => 'Germany',       'iso' => 'DE', 'phone_code' => '+49'],
    12 => ['name' => 'Greece',        'iso' => 'GR', 'phone_code' => '+30'],
    13 => ['name' => 'Hungary',       'iso' => 'HU', 'phone_code' => '+36'],
    14 => ['name' => 'Ireland',       'iso' => 'IE', 'phone_code' => '+353'],
    15 => ['name' => 'Italy',         'iso' => 'IT', 'phone_code' => '+39'],
    16 => ['name' => 'Latvia',        'iso' => 'LV', 'phone_code' => '+371'],
    17 => ['name' => 'Lithuania',     'iso' => 'LT', 'phone_code' => '+370'],
    18 => ['name' => 'Luxembourg',    'iso' => 'LU', 'phone_code' => '+352'],
    19 => ['name' => 'Malta',         'iso' => 'MT', 'phone_code' => '+356'],
    20 => ['name' => 'Netherlands',   'iso' => 'NL', 'phone_code' => '+31'],
    21 => ['name' => 'Poland',        'iso' => 'PL', 'phone_code' => '+48'],
    22 => ['name' => 'Portugal',      'iso' => 'PT', 'phone_code' => '+351'],
    23 => ['name' => 'Romania',       'iso' => 'RO', 'phone_code' => '+40'],
    24 => ['name' => 'Slovakia',      'iso' => 'SK', 'phone_code' => '+421'],
    25 => ['name' => 'Slovenia',      'iso' => 'SI', 'phone_code' => '+386'],
    26 => ['name' => 'Spain',         'iso' => 'ES', 'phone_code' => '+34'],
    27 => ['name' => 'Sweden',        'iso' => 'SE', 'phone_code' => '+46'],

    // === CIS (Commonwealth of Independent States) ===
    28 => ['name' => 'Russia',        'iso' => 'RU', 'phone_code' => '+7'],
    29 => ['name' => 'Belarus',       'iso' => 'BY', 'phone_code' => '+375'],
    30 => ['name' => 'Ukraine',       'iso' => 'UA', 'phone_code' => '+380'],
    31 => ['name' => 'Kazakhstan',    'iso' => 'KZ', 'phone_code' => '+7'],
    32 => ['name' => 'Uzbekistan',    'iso' => 'UZ', 'phone_code' => '+998'],
    33 => ['name' => 'Turkmenistan',  'iso' => 'TM', 'phone_code' => '+993'],
    34 => ['name' => 'Kyrgyzstan',    'iso' => 'KG', 'phone_code' => '+996'],
    35 => ['name' => 'Tajikistan',    'iso' => 'TJ', 'phone_code' => '+992'],
    36 => ['name' => 'Azerbaijan',    'iso' => 'AZ', 'phone_code' => '+994'],
    37 => ['name' => 'Armenia',       'iso' => 'AM', 'phone_code' => '+374'],
    38 => ['name' => 'Moldova',       'iso' => 'MD', 'phone_code' => '+373'],
    39 => ['name' => 'Georgia',       'iso' => 'GE', 'phone_code' => '+995'],
    40 => ['name' => 'United Arab Emirates', 'iso' => 'AE', 'phone_code' => '+971'],
];
